### ISSUE TITLE
No such extension com.alibaba.dubbo.remoting.Codec by name dubbo

### ISSUE THREAD

**Issue by xubing88** [apache/incubator-dubbo#105]
启动provider报错：

``` java
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2015-2-4 15:35:24 org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
信息: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@1d6a56e: defining beans [hello-world-app,com.alibaba.dubbo.config.RegistryConfig,dubbo,com.alibaba.dubbo.demo.DemoService,demoService]; root of factory hierarchy
Exception in thread "main" java.lang.IllegalStateException: No such extension com.alibaba.dubbo.remoting.Codec by name dubbo
    at com.alibaba.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:494)
    at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:501)
    at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:319)
    at com.alibaba.dubbo.remoting.transport.AbstractEndpoint.getChannelCodec(AbstractEndpoint.java:107)
    at com.alibaba.dubbo.remoting.transport.AbstractEndpoint.<init>(AbstractEndpoint.java:46)
    at com.alibaba.dubbo.remoting.transport.AbstractServer.<init>(AbstractServer.java:58)
    at com.alibaba.dubbo.remoting.transport.netty.NettyServer.<init>(NettyServer.java:63)
    at com.alibaba.dubbo.remoting.transport.netty.NettyTransporter.bind(NettyTransporter.java:33)
    at com.alibaba.dubbo.remoting.Transporter$Adpative.bind(Transporter$Adpative.java)
    at com.alibaba.dubbo.remoting.Transporters.bind(Transporters.java:48)
```

下面是配置文件，请问是什么原因

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:dubbo="http://code.alibabatech.com/schema/dubbo"
    xsi:schemaLocation="http://www.springframework.org/schema/beans        http://www.springframework.org/schema/beans/spring-beans.xsd        http://code.alibabatech.com/schema/dubbo        http://code.alibabatech.com/schema/dubbo/dubbo.xsd">

    <!-- 提供方应用信息，用于计算依赖关系 -->
    <dubbo:application name="hello-world-app"  />

    <!-- 使用zookeeper广播注册中心暴露服务地址 -->
    <dubbo:registry address="zookeeper://127.0.0.1:2181" />

    <!-- 用dubbo协议在20880端口暴露服务 -->
    <dubbo:protocol name="dubbo" port="20880" />

    <!-- 声明需要暴露的服务接口 -->
    <dubbo:service interface="com.alibaba.dubbo.demo.DemoService" ref="demoService" />

    <!-- 和本地bean一样实现服务 -->
    <bean id="demoService" class="com.alibaba.dubbo.demo.DemoServiceImpl" />

</beans>
```

**Comment by ralf0131** [comment]
Hi, 

Please check the latest code, I run the dubbo-demo locally and it works fine. 
I am going to close this issue, feel free to reopen it if the issue still exists.
