### ISSUE TITLE
When I use thrift protocol,  the classes generated from idls in version libthrift 0.10.0  will not run,  does dubbo just support libthrift  version 0.8.0?

### ISSUE THREAD

**Issue by willlau0524** [apache/incubator-dubbo#1080]
目前是thrift IDL定义方法，输入和输出
一个服务注册了之后，另外一个服务访问这个服务会报错（用的都是libthrift 0.10.0 版本编译和运行）：
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
        at com.alibaba.dubbo.rpc.protocol.thrift.ThriftCodec.encodeRequest(ThriftCodec.java:410)
        at com.alibaba.dubbo.rpc.protocol.thrift.ThriftCodec.encode(ThriftCodec.java:102)
        at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:81)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:66)
        at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:99)
        at org.jboss.netty.channel.Channels.write(Channels.java:611)
        at org.jboss.netty.channel.Channels.write(Channels.java:578)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:251)
        at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:98)

如果改成 0.8.0 之后（编译还是用的 0.10.0）：
Caused by: com.alibaba.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2017-12-21 07:24:00.570, end time: 2017-12-21 07:24:05.587, client elapsed: 0 ms, server elapsed: 5017 ms, timeout: 5000 ms, request: Request [id=2, version=2.0.0, twoway=true, 
        at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:218)
        at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:139)
        at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:113)
        at com.alibaba.dubbo.rpc.protocol.thrift.ThriftInvoker.doInvoke(ThriftInvoker.java:88)
        at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
        at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
        at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:69)
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
        at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
        ... 33 more

感觉是必须编译和运行都在 0.8.0 下面进行

**Comment by lovepoem** [comment]
now the thrift version is 0.0.8 ，
`<thrift_version>0.8.0</thrift_version>`，then we can upgrade the jar version to the newest

**Comment by willlau0524** [comment]
## thanks , looking forward to the newest version

**Comment by lovepoem** [comment]
I think we can discuss it in https://github.com/dubbo/dubbo-rpc-native-thrift , I'll close it now
