### ISSUE TITLE
demo例子和README问题：demo中的monitor和admin共用了jetty的8080端口，导致启动失败

### ISSUE THREAD

**Issue by fantaxy025025** [apache/incubator-dubbo#125]
run了一下demo，如下：
- 完全按照README操作的没有其他代码改动
- 用的zookeeper注册的
- 同一台机器（ubuntu）
- 版本是最新的2.5.4-SNAPSHOT（git checkout master）

发现问题如下，刚入手，如有不对请告知，感谢！
- demo中的monitor和admin共用了jetty的8080端口，导致其中一个肯定启动失败（README中是如此的）
  <p>
  错误提示就是端口占用错误了，不粘贴了。
  </p>
- mvn进行build的时候，若改动了源文件test下的properties文件，build完后，依然没有成功
  =>这个去掉了，因为编译的时候加入了-Dmaven.test.skip参数
- 如果不启动monitor，本来应该不报错，但是provider和consumer后台都会报错。
  
  <p>
  ==> logs/dubbo-demo-provider.log <==
  2015-04-30 15:21:28,302 [DubboMonitorSendTimer-thread-1] ERROR com.alibaba.dubbo.monitor.dubbo.DubboMonitor$1 (DubboMonitor.java:72) -  [DUBBO] Unexpected error occur at send statistic, cause: Forbid consumer 10.0.3.15 access service com.alibaba.dubbo.monitor.MonitorService from registry 127.0.0.1:2181 use dubbo version 2.5.4-SNAPSHOT, Please check registry access list (whitelist/blacklist)., dubbo version: 2.5.4-SNAPSHOT, current host: 10.0.3.15
  com.alibaba.dubbo.rpc.RpcException: Forbid consumer 10.0.3.15 access service com.alibaba.dubbo.monitor.MonitorService from registry 127.0.0.1:2181 use dubbo version 2.5.4-SNAPSHOT, Please check registry access list (whitelist/blacklist).
  at com.alibaba.dubbo.registry.integration.RegistryDirectory.doList(RegistryDirectory.java:579)
  at com.alibaba.dubbo.rpc.cluster.directory.AbstractDirectory.list(AbstractDirectory.java:73)
  at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.list(AbstractClusterInvoker.java:260)
  at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:219)
  at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
  at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
  at com.alibaba.dubbo.common.bytecode.proxy0.collect(proxy0.java)
  at com.alibaba.dubbo.monitor.dubbo.DubboMonitor.send(DubboMonitor.java:113)
  at com.alibaba.dubbo.monitor.dubbo.DubboMonitor$1.run(DubboMonitor.java:70)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
  at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
  at java.lang.Thread.run(Thread.java:662)
  </p>

**Comment by dengly** [comment]
如果使用tomcat作容器，而且端口设置8080的话也会报错

**Comment by nzomkxia** [comment]
now dubbo admin uses spring boot and the port is 7001, so you can start it with dubbo monitor at the same time.
