### ISSUE TITLE
dubbo admin 用resin启动的问题

### ISSUE THREAD

**Issue by carlosli** [apache/incubator-dubbo#132]
为啥dubbo admin控制台用resin启动会报错，而用tomcat就没事儿呢？
resin错误如下：
java.net.ConnectException: Connection refused: no further information
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:599)
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1143)

**Comment by javahongxi** [comment]
现在还有人用resin吗

**Comment by htynkn** [comment]
I test latest `dubbo-admin` with `resin-pro-4.0.56` in `java8`. All good.

I suggest close this issue for now. 
If there is any future issue, please move to [dubbo-ops](https://github.com/apache/incubator-dubbo-ops/) repo to open a new issue
