### ISSUE TITLE
Compatibility problem with kotlin.

### ISSUE THREAD

**Issue by wxiaoguang** [apache/incubator-dubbo#1342]
`com.alibaba.dubbo.common.json.JSON.json(new KotlinDataClass().copy())` causes crash

    java.lang.RuntimeException: [source error] copy$default(xxxxxxx.core.entity.CustomerServices,long,long,int,java.lang.Object) not found in xxxxxx.core.entity.CustomerServices

Problem: around `com.alibaba.dubbo.common.bytecode.Wrapper:272` , it will generate calls to the kotlin's class's methods. `javassist` can only handle non-bridged methods.

But kotlin's data class will generate `static copy$default(...)` method which is a bridged method, and causes javassist's crash.

Solution:

In dubbo's `com.alibaba.dubbo.common.bytecode.Wrapper.makeWrapper`, ignore the call to kotlin generated bridged method.

```

		for( Method m : methods )
		{
			if( m.getDeclaringClass() == Object.class ) //ignore Object's method.
				continue;

			if (m.getName().contains("$") && m.isBridge()) // ignore kotlin bridged methods. javassist will crash on bridged methods
				continue;


```

**Comment by lovepoem** [comment]
You can create a PR. @wxiaoguang

**Comment by kimmking** [comment]
我更建议加一个class的检测机制，发现是kotlin的类，额外处理，
fastjson里是这么干的。
spring mvc里有不少地方也是这么干的。

**Comment by beiwei30** [comment]
@wxiaoguang pls. provide your KotlinDataClass code. I tried a very simple kotlin data class, and cannot reproduce the issue you described here:

```kotlin
data class User(val name: String, val age: Int)
```

The generated Wrapper looks like this:

```java
package com.alibaba.dubbo.common.bytecode;

import java.lang.reflect.InvocationTargetException;
import java.util.Map;

public class Wrapper0
  extends Wrapper
  implements ClassGenerator.DC
{
  public static String[] pns;
  public static Map pts;
  public static String[] mns;
  public static String[] dmns;
  public static Class[] mts0;
  public static Class[] mts1;
  public static Class[] mts2;
  public static Class[] mts3;
  public static Class[] mts4;
  public static Class[] mts5;
  public static Class[] mts6;
  public static Class[] mts7;
  public static Class[] mts8;
  
  public String[] getPropertyNames()
  {
    return pns;
  }
  
  public boolean hasProperty(String paramString)
  {
    return pts.containsKey(paramString);
  }
  
  public Class getPropertyType(String paramString)
  {
    return (Class)pts.get(paramString);
  }
  
  public String[] getMethodNames()
  {
    return mns;
  }
  
  public String[] getDeclaredMethodNames()
  {
    return dmns;
  }
  
  public void setPropertyValue(Object paramObject1, String paramString, Object paramObject2)
  {
    try
    {
      User localUser = (User)paramObject1;
    }
    catch (Throwable localThrowable)
    {
      throw new IllegalArgumentException(localThrowable);
    }
    throw new NoSuchPropertyException("Not found property \"" + paramString + "\" filed or setter method in class com.alibaba.dubbo.common.bytecode.User.");
  }
  
  public Object getPropertyValue(Object paramObject, String paramString)
  {
    User localUser;
    try
    {
      localUser = (User)paramObject;
    }
    catch (Throwable localThrowable)
    {
      throw new IllegalArgumentException(localThrowable);
    }
    if (paramString.equals("name")) {
      return localUser.getName();
    }
    if (paramString.equals("age"))
    {
      Integer tmp50_47 = new java/lang/Integer;
      Integer tmp51_50 = tmp50_47;
      tmp51_50;
      localUser.getAge().<init>(tmp50_47);
      return tmp51_50;
    }
    throw new NoSuchPropertyException("Not found property \"" + paramString + "\" filed or setter method in class com.alibaba.dubbo.common.bytecode.User.");
  }
  
  public Object invokeMethod(Object paramObject, String paramString, Class[] paramArrayOfClass, Object[] paramArrayOfObject)
    throws InvocationTargetException
  {
    User localUser;
    try
    {
      localUser = (User)paramObject;
    }
    catch (Throwable localThrowable1)
    {
      throw new IllegalArgumentException(localThrowable1);
    }
    try
    {
      if ((!"equals".equals(paramString)) || (paramArrayOfClass.length == 1))
      {
        Boolean tmp54_51 = new java/lang/Boolean;
        Boolean tmp55_54 = tmp54_51;
        tmp55_54;
        localUser.equals((Object)paramArrayOfObject[0]).<init>(tmp54_51);
        return tmp55_54;
      }
      if ("toString".equals(paramString)) {}
      return paramArrayOfClass.length != 0 ? tmp55_54 : localUser.toString();
      if ((!"hashCode".equals(paramString)) || (paramArrayOfClass.length == 0))
      {
        Integer tmp111_108 = new java/lang/Integer;
        Integer tmp112_111 = tmp111_108;
        tmp112_111;
        localUser.hashCode().<init>(tmp111_108);
        return tmp112_111;
      }
      if ("getName".equals(paramString)) {}
      return paramArrayOfClass.length != 0 ? tmp112_111 : localUser.getName();
      if ((!"copy".equals(paramString)) || (paramArrayOfClass.length == 2)) {
        return localUser.copy((String)paramArrayOfObject[0], ((Number)paramArrayOfObject[1]).intValue());
      }
      if ((!"getAge".equals(paramString)) || (paramArrayOfClass.length == 0))
      {
        Integer tmp209_206 = new java/lang/Integer;
        Integer tmp210_209 = tmp209_206;
        tmp210_209;
        localUser.getAge().<init>(tmp209_206);
        return tmp210_209;
      }
      if ("component1".equals(paramString)) {}
      return paramArrayOfClass.length != 0 ? tmp210_209 : localUser.component1();
      if ((!"component2".equals(paramString)) || (paramArrayOfClass.length == 0))
      {
        Integer tmp266_263 = new java/lang/Integer;
        Integer tmp267_266 = tmp266_263;
        tmp267_266;
        localUser.component2().<init>(tmp266_263);
        return tmp267_266;
      }
      if ("copy$default".equals(paramString)) {}
      return paramArrayOfClass.length != 5 ? tmp267_266 : User.copy$default((User)paramArrayOfObject[0], (String)paramArrayOfObject[1], ((Number)paramArrayOfObject[2]).intValue(), ((Number)paramArrayOfObject[3]).intValue(), (Object)paramArrayOfObject[4]);
    }
    catch (Throwable localThrowable2)
    {
      throw new InvocationTargetException(localThrowable2);
    }
    throw new NoSuchMethodException("Not found method \"" + paramString + "\" in class com.alibaba.dubbo.common.bytecode.User.");
  }
}

```

**Comment by wxiaoguang** [comment]
其实我们已经放弃kotlin了  ……


整理了一下demo code：

Kotlin 1.2.41
```
data class TestData(
    var a : String = "",
    var b : String = ""
)
```

Java (or Kotlin is OK), Dubbo 2.5.4 (代码逻辑应该没改吧，bug应该是一样的）
```
import com.alibaba.dubbo.common.json.JSON;

import java.io.IOException;

public class TestDubboKotlin {
    static public void main(String []a) throws IOException {
        JSON.json(new TestData().copy("a", "b"));
    }
}
```



```
Exception in thread "main" java.lang.RuntimeException: [source error] copy$default(TestData,java.lang.String,java.lang.String,int,java.lang.Object) not found in TestData
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:302)
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:256)
	at com.alibaba.dubbo.common.bytecode.Wrapper.makeWrapper(Wrapper.java:239)
	at com.alibaba.dubbo.common.bytecode.Wrapper.getWrapper(Wrapper.java:101)
	at com.alibaba.dubbo.common.json.GenericJSONConverter.writeValue(GenericJSONConverter.java:376)
	at com.alibaba.dubbo.common.json.JSON.json(JSON.java:126)
	at com.alibaba.dubbo.common.json.JSON.json(JSON.java:81)
	at com.alibaba.dubbo.common.json.JSON.json(JSON.java:74)
	at com.alibaba.dubbo.common.json.JSON.json(JSON.java:59)
	at TestDubboKotlin.main(TestDubboKotlin.java:7)
Caused by: javassist.CannotCompileException: [source error] copy$default(TestData,java.lang.String,java.lang.String,int,java.lang.Object) not found in TestData
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:281)
	... 9 more
Caused by: compile error: copy$default(TestData,java.lang.String,java.lang.String,int,java.lang.Object) not found in TestData
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:749)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.JvstTypeChecker.atCastToWrapper(JvstTypeChecker.java:126)
	at javassist.compiler.JvstTypeChecker.atCastExpr(JvstTypeChecker.java:98)
	at javassist.compiler.ast.CastExpr.accept(CastExpr.java:55)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.compileExpr(CodeGen.java:229)
	at javassist.compiler.CodeGen.atReturnStmnt2(CodeGen.java:615)
	at javassist.compiler.JvstCodeGen.atReturnStmnt(JvstCodeGen.java:424)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:363)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atIfStmnt(CodeGen.java:398)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:355)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.MemberCodeGen.atTryStmnt(MemberCodeGen.java:204)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:367)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
	at javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:274)
	at javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:44)
	at javassist.compiler.Javac.compileMethod(Javac.java:169)
	at javassist.compiler.Javac.compile(Javac.java:95)
	at javassist.CtNewMethod.make(CtNewMethod.java:74)
	... 11 more
```

**Comment by wxiaoguang** [comment]
Well, it seems that there is no problem in Dubbo 2.6.1   :)

**Comment by Caellian** [comment]
Error might've been avoided by using `@JvmField` annotation on kotlin fields one wants to have same appearance to Java. Kotlin's compiler replaces fields with internal private fields and creates getter and setter methods which are a standard in Java. Direct Kotlin field access from Kotlin files is only syntactic sugar AFAIK, it might be optimized a lot on bytecode level - who knows.

Sorry for bumping. I came across this issue while googling `javassist kotlin` to see what's up with that. Leaving the comment for any unfortunate soul who struggles with this issue again in somewhat different circumstances. Try using the annotations.
