### ISSUE TITLE
here is a StackOverflow bug?  dubbo version 2.5.9, FailsafeLogger.appendContextMessage() > NetUtils.getLocalAddress()

### ISSUE THREAD

**Issue by limingwei** [apache/incubator-dubbo#1431]
`
2018-03-07 22:24:52
Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.75-b04 mixed mode):

"pool-2-thread-1" prio=10 tid=0x00007f24402a1000 nid=0x36bd in Object.wait() [0x00007f247a161000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000742ca3ab8> (a java.util.HashMap)
	at java.lang.Object.wait(Object.java:503)
	at java.net.InetAddress.checkLookupTable(InetAddress.java:1363)
	- locked <0x0000000742ca3ab8> (a java.util.HashMap)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1280)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
	- locked <0x0000000742ca3aa8> (a java.lang.Object)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress0(NetUtils.java:193)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress(NetUtils.java:180)
	at com.alibaba.dubbo.common.utils.NetUtils.getLogHost(NetUtils.java:186)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.appendContextMessage(FailsafeLogger.java:40)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.warn(FailsafeLogger.java:101)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress0(NetUtils.java:225)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress(NetUtils.java:180)
	at com.alibaba.dubbo.common.utils.NetUtils.getLogHost(NetUtils.java:186)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.appendContextMessage(FailsafeLogger.java:40)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.warn(FailsafeLogger.java:101)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress0(NetUtils.java:198)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress(NetUtils.java:180)
	at com.alibaba.dubbo.common.utils.NetUtils.getLogHost(NetUtils.java:186)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.appendContextMessage(FailsafeLogger.java:40)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.warn(FailsafeLogger.java:101)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress0(NetUtils.java:198)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress(NetUtils.java:180)
	at com.alibaba.dubbo.common.utils.NetUtils.getLogHost(NetUtils.java:186)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.appendContextMessage(FailsafeLogger.java:40)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.warn(FailsafeLogger.java:101)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress0(NetUtils.java:198)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress(NetUtils.java:180)
	at com.alibaba.dubbo.common.utils.NetUtils.getLogHost(NetUtils.java:186)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.appendContextMessage(FailsafeLogger.java:40)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.warn(FailsafeLogger.java:101)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress0(NetUtils.java:198)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress(NetUtils.java:180)
	at com.alibaba.dubbo.common.utils.NetUtils.getLogHost(NetUtils.java:186)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.appendContextMessage(FailsafeLogger.java:40)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.warn(FailsafeLogger.java:101)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress0(NetUtils.java:198)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress(NetUtils.java:180)
	at com.alibaba.dubbo.common.utils.NetUtils.getLogHost(NetUtils.java:186)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.appendContextMessage(FailsafeLogger.java:40)
	at com.alibaba.dubbo.common.logger.support.FailsafeLogger.warn(FailsafeLogger.java:101)
	at com.alibaba.dubbo.common.utils.NetUtils.getLocalAddress0(NetUtils.java:198)
`

**Comment by limingwei** [comment]
# maybe yes

![_20180307223736](https://user-images.githubusercontent.com/1704535/37098176-35648e64-2258-11e8-8392-f4694ac1d355.png)
![_20180307223705](https://user-images.githubusercontent.com/1704535/37098183-365dd50a-2258-11e8-8baf-563f0fb3268b.png)

**Comment by vangoleo** [comment]
It's a bug. when NetUtils.getLocalHost() raise an exception, the invoke chain will go to an endless loop:
NetUtils.getLocalHost() -> FailsafeLogger.appendContextMessage() -> NetUtils.getLocalHost()

@kimmking there are some conflict in your PR #1435. Could you please update the PR.
