### ISSUE TITLE
使用java代码配置，先启动consumer，后启动provider。消费端引用对象没有注入

### ISSUE THREAD

**Issue by jklasd** [apache/incubator-dubbo#1468]
配置代码
`@Configuration
@DubboComponentScan(basePackages = "bbkj.org.cn")
public class DubboConfiguration {
	
	@Value("${dubbo.registry.protocol}")
	private String protocol;
	@Value("${dubbo.registry.connections}")
	private String connections;
	@Value("${dubbo.registry.applicationName}")
	private String applicationName;
	
	@Value("${dubbo.protocol.name}")
	private String protocolName;
	@Value("${dubbo.protocol.port}")
	private Integer port;
	
	@Value("${dubbo.consumer.defaultTimeOut:100000}")
	private Integer timeOut;
	
	@Bean
	public RegistryConfig registConfig(){
		RegistryConfig registryConfig = new RegistryConfig();
        registryConfig.setAddress(connections);
        registryConfig.setProtocol("zookeeper");
        return registryConfig;
	}
	
	@Bean
	public ProtocolConfig protocolConfig(){
		ProtocolConfig config = new ProtocolConfig();
		config.setName(protocolName);
		config.setPort(port);
		return config;
	}
	
	@Bean
    public ApplicationConfig applicationConfig() {
        ApplicationConfig applicationConfig = new ApplicationConfig();
        applicationConfig.setName(applicationName);
        return applicationConfig;
    }
	
	/**
	 * 消费端配置
	 * @return
	 */
	@Bean
	public ConsumerConfig consumerConfig(){
		ConsumerConfig consumerConfig = new ConsumerConfig();
		consumerConfig.setTimeout(timeOut);//超时100s
		consumerConfig.setCluster("failfast");//快速失败，只调用一次
        return consumerConfig;
	}
}`

启动类
`@SpringBootApplication
public class FootBallSimulatorLaunch {

	public static void main(String[] args) {
		SpringApplication.run(FootBallSimulatorLaunch.class, args);
		 Main.main(args);
	}
}`

导致结果

消费端引用对象为空

**Comment by jklasd** [comment]
没有其他配置了，是否是因为java代码配置时，没有提供默认配置。还是我的配置少了什么参数

**Comment by jklasd** [comment]
配置日志打印后，
`Caused by: java.lang.IllegalStateException: Failed to check the status of the service bbkj.org.cn.service.FootBallService. No provider available for the service bbkj.org.cn.service.FootBallService:1.0.0 from the url zookeeper://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=footballSimulator&default.cluster=failfast&dubbo=2.5.8&interface=bbkj.org.cn.service.FootBallService&logger=slf4j&methods=updateLeagueInfo,loadLeague,loadLeagueTeam,loadLeagueMatch,loadLeagueConfig,getMatchInfo,recentlyMatch&pid=29068&register.ip=172.21.5.151&revision=1.0.0&side=consumer&timestamp=1521082465590&version=1.0.0 to the consumer 172.21.5.151 use dubbo version 2.5.8
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:423) ~[dubbo-2.5.8.jar:2.5.8]
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:334) ~[dubbo-2.5.8.jar:2.5.8]
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:163) ~[dubbo-2.5.8.jar:2.5.8]
	at com.alibaba.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:59) ~[dubbo-2.5.8.jar:2.5.8]
	... 30 common frames omitted`

**Comment by jklasd** [comment]
知道原因了是因为我没有设置check 为false。
但这里测试出另外一个问题。
`@EnableDubboConfigBindings({
	@EnableDubboConfigBinding(prefix = "dubbo.registry.",type = RegistryConfig.class)
	,@EnableDubboConfigBinding(prefix = "dubbo.application.",type = ApplicationConfig.class)
	,@EnableDubboConfigBinding(prefix = "dubbo.protocol.",type = ProtocolConfig.class)
	,@EnableDubboConfigBinding(prefix = "dubbo.consumer.",type = ConsumerConfig.class)
})
public class CopyOfDubboConfiguration {
}`

以这种方式注入配置
`2018-03-15 11:24:47.706  INFO 30872 --- [           main] .f.a.DubboConfigBindingBeanPostProcessor : The properties of bean [name : com.alibaba.dubbo.config.ConsumerConfig#0] have been binding by values : [bean property 'cluster']`

只能注入cluster ，不能注入check

**Comment by jklasd** [comment]
额，原因找到了。
 `PropertySources propertySources = environment.getPropertySources();
Map<String, String> properties = getSubProperties(propertySources, prefix);`

DubboConfigBindingRegistrar，读取配置时只读string 类型。
我使用的是yml配置，需要对值进行指定类型
`  consumer:
    check: "false"
    timeout: "100000"
    cluster: failfast`
