### ISSUE TITLE
Upgrade Dubbo from 2.6.0 to 2.6.1 Faild

### ISSUE THREAD

**Issue by xiaomaijiang** [apache/incubator-dubbo#1532]
When i use Dubbo 2.6.0,everythin work fine,but when i upgrade to 2.6.1,i get this error

```
com.alibaba.dubbo.rpc.RpcException: Failed to register consumer://192.168.202.1/com.smart.sso.rpc.AuthenticationRpcService?application=spl-service&category=consumers&check=false&dubbo=2.6.1&interface=com.smart.sso.rpc.AuthenticationRpcService&methods=findAuthInfo,findPermissionList,validate&pid=5090&revision=2.0.3&side=consumer&timestamp=1522401784111 to zookeeper zookeeper://192.168.202.128:2181/com.alibaba.dubbo.registry.RegistryService?application=spl-service&dubbo=2.6.1&interface=com.alibaba.dubbo.registry.RegistryService&pid=5090&timestamp=1522401784137, cause: KeeperErrorCode = Unimplemented for /dubbo/com.smart.sso.rpc.AuthenticationRpcService/consumers/consumer%3A%2F%2F192.168.202.1%2Fcom.smart.sso.rpc.AuthenticationRpcService%3Fapplication%3Dspl-service%26category%3Dconsumers%26check%3Dfalse%26dubbo%3D2.6.1%26interface%3Dcom.smart.sso.rpc.AuthenticationRpcService%26methods%3DfindAuthInfo%2CfindPermissionList%2Cvalidate%26pid%3D5090%26revision%3D2.0.3%26side%3Dconsumer%26timestamp%3D1522401784111
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doRegister(ZookeeperRegistry.java:112)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:130)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:299)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:283)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:63)
	at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:63)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:98)
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:394)
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:333)
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:163)
	at com.alibaba.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:65)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:161)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1645)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1178)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:258)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:225)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1015)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:339)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:334)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1103)
	at org.guiltycrown.configurations.CasAuthFilter.init(CasAuthFilter.java:21)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:285)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:112)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4599)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5241)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

here is my pom

```

        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>4.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-client</artifactId>
            <version>4.0.1</version>
        </dependency>
 <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.6.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>spring</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by kimmking** [comment]
remove all data of zk，then try again

**Comment by xiaomaijiang** [comment]
i remove all zk data ,but still has this error 
```
Caused by: com.alibaba.dubbo.rpc.RpcException: Failed to register dubbo://192.168.202.1:20880/com.smart.sso.rpc.AuthenticationRpcService?anyhost=true&application=smart-sso-server&default.accepts=1000&default.threadpool=fixed&default.threads=100&default.timeout=10000&dubbo=2.6.1&generic=false&interface=com.smart.sso.rpc.AuthenticationRpcService&methods=findAuthInfo,findPermissionList,validate&pid=51933&retries=0&revision=2.0.6&side=provider&timestamp=1523165131451 to zookeeper zookeeper://192.168.202.128:2181/com.alibaba.dubbo.registry.RegistryService?application=smart-sso-server&dubbo=2.6.1&interface=com.alibaba.dubbo.registry.RegistryService&pid=51933&timestamp=1523165131446, cause: KeeperErrorCode = Unimplemented for /dubbo
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doRegister(ZookeeperRegistry.java:112)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:130)
	... 74 more
Caused by: java.lang.IllegalStateException: KeeperErrorCode = Unimplemented for /dubbo
	at com.alibaba.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.createPersistent(CuratorZookeeperClient.java:77)
	at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:63)
	at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:57)
	at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:57)
	at com.alibaba.dubbo.remoting.zookeeper.support.AbstractZookeeperClient.create(AbstractZookeeperClient.java:57)
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doRegister(ZookeeperRegistry.java:110)
	... 75 more
Caused by: org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /dubbo
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:103)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1525)
	at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1181)
	at org.apache.curator.framework.imps.CreateBuilderImpl$17.call(CreateBuilderImpl.java:1158)
	at org.apache.curator.connection.StandardConnectionHandlingPolicy.callWithRetry(StandardConnectionHandlingPolicy.java:64)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:100)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:1155)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:605)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:595)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:573)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:49)
	at com.alibaba.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.createPersistent(CuratorZookeeperClient.java:74)
	... 80 more
```

**Comment by xiaomaijiang** [comment]
i change curator version...It work =。=
```
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>2.12.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-client</artifactId>
            <version>2.12.0</version>
        </dependency>
```
i think it shoud be write to the document

**Comment by zonghaishang** [comment]
@xiaomaijiang 
Here is default version: 
 <curator_version>2.12.0</curator_version>
