### ISSUE TITLE
dubbo 2.5.3  启动报错

### ISSUE THREAD

**Issue by fooololo** [apache/incubator-dubbo#158]
使用dubbo 2.5.3, spring mvc 4.1.5RELEASE ，在本地jetty正常启动，部署到服务器tomcat时报错：
    at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85) ~[spring-2.5.6.SEC03.jar:2.5.6.SEC03]
    at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:80) ~[spring-2.5.6.SEC03.jar:2.5.6.SEC03]
    at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.error(BeanDefinitionParserDelegate.java:281) ~[spring-2.5.6.SEC03.jar:2.5.6.SEC03]
    at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parsePropertySubElement(BeanDefinitionParserDelegate.java:999) ~[spring-2.5.6.SEC03.jar:2.5.6.SEC03]
    at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parsePropertySubElement(BeanDefinitionParserDelegate.java:927) ~[spring-2.5.6.SEC03.jar:2.5.6.SEC03]
    at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parsePropertyValue(BeanDefinitionParserDelegate.java:917) ~[spring-2.5.6.SEC03.jar:2.5.6.SEC03]
    at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseConstructorArgElement(BeanDefinitionParserDelegate.java:786) ~[spring-2.5.6.SEC03.jar:2.5.6.SEC03]
    at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseConstructorArgElements(BeanDefinitionParserDelegate.java:678) ~[spring-2.5.6.SEC03.jar:2.5.6.SEC03]
    at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseBeanDefinitionElement(BeanDefinitionParserDelegate.java:474) ~[spring-2.5.6.SEC03.jar:2.5.6.SEC03]
    ... 34 common frames omitted

Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Unknown property sub-element: [array]
Offending resource: URL [jar:file:/home/mamahao/tomcatXXX/webapps/app-api/WEB-INF/lib/gd-common-1.0.jar!/config/spring/applicationContext-dao.xml]

不知道错误里怎么会出现spring 2.5.6的信息。。

**Comment by justein** [comment]
因为dubbo2.5.3是基于spring2.5.6SEC这个版本来构建的，构建工程时需要将dubbo本身对spring的依赖exclude掉，然后加入高版本的spring。

**Comment by secsea** [comment]
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.5.3</version>
            <exclusions>
                <exclusion>
                    <artifactId>spring</artifactId>
                    <groupId>org.springframework</groupId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by ralf0131** [comment]
Please tested on the latest version 2.6.3. I am closing this issue, please feel free to reopen if the issue still exist.
