### ISSUE TITLE
provider  report failed monitor

### ISSUE THREAD

**Issue by cdma** [apache/incubator-dubbo#1583]
version:2.6.1
registry:zookeep
<dubbo:monitor  protocol="registry" />
monitor: dubbo-monitor-simple
[zk: localhost:2181(CONNECTED) 6] ls /dubbo/com.alibaba.dubbo.monitor.MonitorService/providers
[dubbo%3A%2F%2F192.168.10.50%3A7070%2Fcom.alibaba.dubbo.monitor.MonitorService%3Fanyhost%3Dtrue%26application%3Dsimple-monitor%26delay%3D-1%26dubbo%3D2.6.0%26generic%3Dfalse%26interface%3Dcom.alibaba.dubbo.monitor.MonitorService%26methods%3Dlookup%2Ccollect%26owner%3Ddubbo%26pid%3D14916%26revision%3D2.6.0%26side%3Dprovider%26timestamp%3D1523365434532]

2018-04-10 21:06:05,038 [DubboServerHandler-192.168.10.50:28080-thread-2] ERROR com.alibaba.dubbo.monitor.support.MonitorFilter (MonitorFilter.java:126) -  [DUBBO] Failed to monitor count service dubbo://192.168.10.50:28080/com.dubbobase.api.DemoService?accesslog=true&anyhost=true&application=dubbodemo-provider&bind.ip=192.168.10.50&bind.port=28080&default.accepts=100&default.threadpool=fixed&default.threads=2&default.token=false&dubbo=2.6.1&generic=false&interface=com.dubbobase.api.DemoService&loadbalance=leastactive&methods=updateUserState,sayHello,testException,getLastUser,createUser,getFirstUser&monitor=dubbo%3A%2F%2Flocalhost%3A2181%2Fcom.alibaba.dubbo.registry.RegistryService%3Fapplication%3Ddubbodemo-provider%26client%3Dcurator%26dubbo%3D2.6.1%26pid%3D14537%26protocol%3Dregistry%26refer%3Ddubbo%253D2.6.1%2526interface%253Dcom.alibaba.dubbo.monitor.MonitorService%2526pid%253D14537%2526timestamp%253D1523365277058%26registry%3Dzookeeper%26shutdown.timeout%3D10000%26timestamp%3D1523365276947&pid=14537&revision=2.5.3&service.filter=activelimit&shutdown.timeout=10000&side=provider&timeout=3000&timestamp=1523365276959&validation=true, cause: null, dubbo version: 2.6.1, current host: 192.168.10.50
java.lang.NullPointerException
	at com.alibaba.dubbo.monitor.support.MonitorFilter.collect(MonitorFilter.java:88)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:65)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:41)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.AccessLogFilter.invoke(AccessLogFilter.java:154)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:71)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:131)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:37)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:37)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.telnet.InvokeTelnetHandler.telnet(InvokeTelnetHandler.java:141)
	at com.alibaba.dubbo.remoting.telnet.support.TelnetHandlerAdapter.telnet(TelnetHandlerAdapter.java:52)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:181)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:50)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:79)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kimmking** [comment]
you can use the latest version.

**Comment by cdma** [comment]
clone latest dubbo, delete maven repo dubbo, mvn clean install
The issue happened yet

**Comment by chickenlj** [comment]
```java
 Monitor monitor = monitorFactory.getMonitor(url);
```

monitorFactory seems to be NULL, how do you use dubbo? I doubt that you didn't use a fat jar dependency and  forget to add `dubbo-monitor-default` dependency.

**Comment by chickenlj** [comment]
monitorFactory IOC injection failed, cannot find a monitorFactory instance, cause there's no extension of MonitorFactory. I think we should add some logs for this scenario.
