### ISSUE TITLE
How to use standard cxf client to invoke Dubbo Webservice?

### ISSUE THREAD

**Issue by lixiaguang** [apache/incubator-dubbo#1585]
I got a  Dubbo Webservice WSDL Address. I want to use cxf client toinvoke.But when i run my code,I got some error "NullPointerException".
here is my client code:
-----------------------------------------
import javax.xml.namespace.QName;
import javax.xml.ws.WebServiceClient;

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.jaxws.endpoint.dynamic.JaxWsDynamicClientFactory;
import org.apache.log4j.Logger;

import cn.com.shenhuagroup.xxgs.bigdata.test.builddata.BuildTestData;

public class Test1 {
	Logger log = Logger.getLogger(Test1.class);

	public Object[] callWebService(String wsdl, String targetNamespace, String methodName, Object args[]) {
		Object[] res = null;
		try {
			log.info("动态调用webservice开始，wsdl:" + wsdl + ",methodName:" + methodName + ",args:" + args);
			JaxWsDynamicClientFactory dcf = JaxWsDynamicClientFactory.newInstance();
			Client client = dcf.createClient(wsdl);
			if (targetNamespace == null) {
				res = client.invoke(methodName, args);
			} else {
				res = client.invoke(new QName(targetNamespace, methodName), args);
			}

		} catch (Exception e) {
			log.error("动态调用webservice 失败,wsdl:" + wsdl + ",targetNamespace:" + targetNamespace + ",methodName:"
					+ methodName + ",args:" + args, e);
		}
		return res;
	}

	public static void main(String[] args) {
		String wsdl = "http://xxxxxxxxxx:8080/TestService?wsdl"; // WSDL
		String targetNamespace = "http://xxxxxxxxxx.com/"; // WSDL
		String methodName = "getUserInfo";
		Object params[] = {"id","1" };
		Test1 client = new Test1();
		Object[] res = client.callWebService(wsdl, targetNamespace, methodName, params);
		System.out.println(res.toString());
	}
}

Here is error:
---------------------------------------
java.lang.NullPointerException
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit.createConnection(URLConnectionHTTPConduit.java:109)
	at org.apache.cxf.transport.http.URLConnectionHTTPConduit.setupConnection(URLConnectionHTTPConduit.java:122)
	at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:499)
	at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:46)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:297)

**Comment by kimmking** [comment]
please show the wsdl file, I guess its endpoint address is missing

**Comment by lixiaguang** [comment]
yes,it's missing endpoint address. provide configuration is here. How to add endpoint address? use annotation or user configution?
-------------------------------
    <dubbo:application name="dataservice-provider-app"/> 
    <dubbo:registry protocol="zookeeper" address="10.212.141.40:2181,10.212.141.41:2181,10.212.141.39:2181"  group="dubbo" /> 
    <dubbo:protocol name="dubbo" port="20880"  /> 
    <dubbo:protocol name="webservice" port="8080" server="servlet" contextpath="webservices" />
    <dubbo:service interface="com.test.TestService" ref="testService" protocol="dubbo,webservice" timeout="1200000"  />
    <bean id="testService" class="com.test.TestServiceImpl" />


here is wsdl
-----------------------------
<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://test.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="TestService" targetNamespace="http://test.com/">
  <wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://test.com/" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://test.com/">
  <xsd:element name="getUserInfo" type="tns:getUserInfo"/>
  <xsd:complexType name="getUserInfo">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="arg0" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="getUserInfoResponse" type="tns:getUserInfoResponse"/>
  <xsd:complexType name="getUserInfoResponse">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="return" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="getUserInfo">
    <wsdl:part element="tns:getUserInfo" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getUserInfoResponse">
    <wsdl:part element="tns:getUserInfoResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="TestServicePortType">
    <wsdl:operation name="getUserInfo">
      <wsdl:input message="tns:getUserInfo" name="getUserInfo">
    </wsdl:input>
      <wsdl:output message="tns:getUserInfoResponse" name="getUserInfoResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="TestServiceSoapBinding" type="tns:TestServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getUserInfo">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getUserInfo">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getUserInfoResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TestService">
    <wsdl:port binding="tns:TestServiceSoapBinding" name="TestServicePort">
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>

**Comment by chickenlj** [comment]
Shouldn't the endpoint address be added on your customized client?

**Comment by kimmking** [comment]
I think this is a bug.
I will fix it later.
