### ISSUE TITLE
无参数 method dubbo api  error

### ISSUE THREAD

**Issue by mahe0924** [apache/incubator-dubbo#1587]
public interface SceneTaskServiceApi {
    void getAvailableDomain();
}
@Service
public class SceneTaskServiceApiImpl implements SceneTaskServiceApi{
    @Override
    public void getAvailableDomain() {
         //some code
     }
}

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-04-11 14:17:27.219 [main] ERROR o.s.boot.SpringApplication - Application startup failed
java.lang.RuntimeException: [source error] getPropertyValue (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object; in com.alibaba.dubbo.common.bytecode.Wrapper55: inconsistent stack height -1
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:354) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:293) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.common.bytecode.Wrapper.makeWrapper(Wrapper.java:346) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.common.bytecode.Wrapper.getWrapper(Wrapper.java:89) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:430) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:285) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:246) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:145) ~[dubbo-2.8.4.jar:2.8.4]
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:110) ~[dubbo-2.8.4.jar:2.8.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at com.eqxiu.boot.EQXIUApplication.run(EQXIUApplication.java:145) [eqxiu-boot-1.2.1.jar:na]
	at com.eqxiu.boot.EQXIUApplication.run(EQXIUApplication.java:36) [eqxiu-boot-1.2.1.jar:na]
	at com.eqxiu.scene.SceneServiceProviderBoot.main(SceneServiceProviderBoot.java:29) [classes/:na]
Caused by: javassist.CannotCompileException: [source error] getPropertyValue (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object; in com.alibaba.dubbo.common.bytecode.Wrapper55: inconsistent stack height -1
	at javassist.CtNewMethod.make(CtNewMethod.java:79) ~[javassist-3.20.0-GA.jar:na]
	at javassist.CtNewMethod.make(CtNewMethod.java:45) ~[javassist-3.20.0-GA.jar:na]
	at com.alibaba.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:322) ~[dubbo-2.8.4.jar:2.8.4]
	... 22 common frames omitted
Caused by: javassist.compiler.CompileError: getPropertyValue (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object; in com.alibaba.dubbo.common.bytecode.Wrapper55: inconsistent stack height -1
	at javassist.compiler.Javac.compile(Javac.java:104) ~[javassist-3.20.0-GA.jar:na]
	at javassist.CtNewMethod.make(CtNewMethod.java:74) ~[javassist-3.20.0-GA.jar:na]
	... 24 common frames omitted

**Comment by chickenlj** [comment]
#245 #627, check if these issues can help.

Please reopen this issue if necessary.

**Comment by chickenlj** [comment]
Are you using dubbox, highly recommend upgrade to the official version.
