### ISSUE TITLE
Exception during demo provider start

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo#1619]
When running the provider demo (com.alibaba.dubbo.demo.provider.Provider#main), there is an warn message with an exception stack trace as follows:

```sh
[17/04/18 04:30:35:035 CST] main  INFO config.AbstractConfig:  [DUBBO] The service ready on spring started. service: com.alibaba.dubbo.demo.DemoService, dubbo version: 2.0.0, current host: 30.5.96.22
[17/04/18 04:33:28:028 CST] main  WARN config.AbstractConfig:  [DUBBO] Address family not supported by protocol family (connect failed), dubbo version: 2.0.0, current host: 30.5.96.22
java.net.ConnectException: Address family not supported by protocol family (connect failed)
  at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
  at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400)
  at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243)
  at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225)
  at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)
  at java.base/java.net.Socket.connect(Socket.java:591)
  at com.alibaba.dubbo.config.ServiceConfig.findConfigedHosts(ServiceConfig.java:577)
  at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:469)
  at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:357)
  at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:316)
  at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:215)
  at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:121)
  at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:50)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
  at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
  at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
  at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
  at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
  at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
  at com.alibaba.dubbo.demo.provider.Provider.main(Provider.java:27)
```

The functionality works fine. However, this will make user confused. We need to avoid this stack trace to be printed.

**Comment by chickenlj** [comment]
Done.
