### ISSUE TITLE
HessianProtocolTest is unstable

### ISSUE THREAD

**Issue by beiwei30** [apache/incubator-dubbo#1727]
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
Running com.alibaba.dubbo.rpc.protocol.hessian.HessianProtocolTest
log4j:WARN No appenders could be found for logger (com.alibaba.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2018-05-02 09:42:39.952:INFO::Logging to STDERR via org.mortbay.log.StdErrLog
2018-05-02 09:42:40.111:INFO::jetty-6.1.26
2018-05-02 09:42:40.334:INFO::Started SelectChannelConnector@0.0.0.0:5342
2018-05-02 09:42:41.284:WARN::/com.alibaba.dubbo.rpc.protocol.hessian.HessianService: com.caucho.hessian.io.HessianProtocolException: sayHello: expected int at 0x7a (z)
2018-05-02 09:42:41.409:WARN::/com.alibaba.dubbo.rpc.protocol.hessian.HessianService: com.caucho.hessian.io.HessianProtocolException: sayHello: expected int at 0x7a (z)
Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.58 sec <<< FAILURE! - in com.alibaba.dubbo.rpc.protocol.hessian.HessianProtocolTest
testHttpClient(com.alibaba.dubbo.rpc.protocol.hessian.HessianProtocolTest)  Time elapsed: 0.746 sec  <<< ERROR!
com.caucho.hessian.client.HessianRuntimeException: com.caucho.hessian.io.HessianProtocolException: 'ï¿¿' is an unknown code
	at com.alibaba.dubbo.rpc.protocol.hessian.HessianProtocolTest.testHttpClient(HessianProtocolTest.java:83)
Caused by: com.caucho.hessian.io.HessianProtocolException: 'ï¿¿' is an unknown code
	at com.alibaba.dubbo.rpc.protocol.hessian.HessianProtocolTest.testHttpClient(HessianProtocolTest.java:83)

testHessianProtocol(com.alibaba.dubbo.rpc.protocol.hessian.HessianProtocolTest)  Time elapsed: 0.002 sec  <<< ERROR!
com.caucho.hessian.client.HessianRuntimeException: com.caucho.hessian.io.HessianProtocolException: 'ï¿¿' is an unknown code
	at com.alibaba.dubbo.rpc.protocol.hessian.HessianProtocolTest.testHessianProtocol(HessianProtocolTest.java:48)
Caused by: com.caucho.hessian.io.HessianProtocolException: 'ï¿¿' is an unknown code
	at com.alibaba.dubbo.rpc.protocol.hessian.HessianProtocolTest.testHessianProtocol(HessianProtocolTest.java:48)


Results :

Tests in error: 
  HessianProtocolTest.testHessianProtocol:48 Â» HessianRuntime com.caucho.hessian...
  HessianProtocolTest.testHttpClient:83 Â» HessianRuntime com.caucho.hessian.io.H...

Tests run: 5, Failures: 0, Errors: 2, Skipped: 0
```

**Comment by htynkn** [comment]
link to #1667

**Comment by ralf0131** [comment]
It is a duplicated issue.
