### ISSUE TITLE
com.alibaba.dubbo.common.json.JSON.parse 方法无法转换setter方法有返回值的类

### ISSUE THREAD

**Issue by summer9989** [apache/incubator-dubbo#1754]
问题描述：
当一个bean 的setter为非void，有返回值时。com.alibaba.dubbo.common.json.JSON下的将String 转换为具体class的类就会报错，比如public static <T> T parse(String json, Class<T> type) throws ParseException 或 
public static Object[] parse(String json, Class<?>[] types) throws ParseException 方法，bean的setter方法（本示例无业务意义）：
public int setStatus(int status){
 this.status = status;
 return status;
}

报错信息：
com.alibaba.dubbo.common.bytecode.NoSuchPropertyException: Not found property "name" filed or setter method in class com.alibaba.dubbo.common.json.JSONTest$Bean.

	at com.alibaba.dubbo.common.bytecode.Wrapper0.setPropertyValue(Wrapper0.java)
	at com.alibaba.dubbo.common.json.J2oVisitor.objectItemValue(J2oVisitor.java:287)
	at com.alibaba.dubbo.common.json.JSON.parse(JSON.java:658)
	at com.alibaba.dubbo.common.json.JSON.parse(JSON.java:208)
	at com.alibaba.dubbo.common.json.JSON.parse(JSON.java:189)
	at com.alibaba.dubbo.common.json.JSONTest.testParse2Class(JSONTest.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

具体重现类可到源码的test case：
com.alibaba.dubbo.common.json.JSONTest#testParse2Class，将Bean的任意属性setter方法修改为有返回值

**Comment by summer9989** [comment]
可以先确认是不是一个问题吗？

**Comment by carryxyh** [comment]
org.apache.dubbo.common.json.JSON is Deprecated. :)

And it is not a problem.
Setter method should be void.

NEED-CLOSE
