### ISSUE TITLE
使用@Reference注解，如果对应服务没有实例，报错之后这个对象一直为空

### ISSUE THREAD

**Issue by willlau0524** [apache/incubator-dubbo#1765]
最近服务上线的时候发现，使用@Reference 注解去引用某个服务，如果这个服务没有实例在zk，那么会抛出一个 IllegalStateException， 信息是 No provider available for the service  xxxx。 此时使用这个注解修饰的对象会置为空，那么后续就算有实例上线注册到zk了，运行到使用这个对象的代码的时候会报空指针。
只有在引用服务有实例的时候重启，这样这个引用对象才会正确构建，不知道是故意这么设计的还是一个bug?  经过测试，使用API构建 ReferenceConfig 没有这个问题

**Comment by willlau0524** [comment]
异常栈：
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
        at com.alibaba.dubbo.config.AbstractConfig.toString(AbstractConfig.java:473) [dubbo-2.5.8.jar:2.5.8]
        at java.lang.String.valueOf(String.java:2994) [?:1.8.0_131]
        at java.lang.StringBuilder.append(StringBuilder.java:131) [?:1.8.0_131]
        at com.alibaba.dubbo.config.spring.beans.factory.annotation.AbstractAnnotationConfigBeanBuilder.build(AbstractAnnotationConfigBeanBuilder.java:61) [dubbo-2.5.8.jar:2.5.8]
        at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.buildReferenceBean(ReferenceAnnotationBeanPostProcessor.java:318) [dubbo-2.5.8.jar:2.5.8]
        at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.access$100(ReferenceAnnotationBeanPostProcessor.java:45) [dubbo-2.5.8.jar:2.5.8]
        at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceFieldElement.inject(ReferenceAnnotationBeanPostProcessor.java:296) [dubbo-2.5.8.jar:2.5.8]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) [spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.postProcessPropertyValues(ReferenceAnnotationBeanPostProcessor.java:72) [dubbo-2.5.8.jar:2.5.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) [spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) [spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) [spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) [spring-beans-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) [spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) [spring-context-4.3.12.RELEASE.jar:4.3.12.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.8.RELEASE.jar:1.5.8.RELEASE]

**Comment by jimwarewj** [comment]
我猜应该是没有配置<dubbo:annotation package=“”/>

**Comment by willlau0524** [comment]
不是楼上那个问题，正常有实例是没有问题的
最近发现，就算是用 ReferenceConfig如果是在第一次 get()的时候也报错，那么还是会出现这样的问题
猜想应该是dubbo的机制？初始化的时候必须有实例，否则就直接报错

**Comment by foreveryang321** [comment]
dubbo.consumer.check=false
or the same
<dubbo:reference check="false"></dubbo:reference>

**Comment by joooohnli** [comment]
同样遇到该问题。这是dubbo的启动时检查（```dubbo.consumer.check=true```）导致的：初始化时提供方接口检查不通过，则之后该引用都是null。

我感觉这算是个bug。启动时检查的初衷应该是：检查不通过，应用启动失败。

**Comment by zonghaishang** [comment]
fixed, refer: https://github.com/apache/incubator-dubbo/pull/1999

**Comment by FisherYu-CN** [comment]
这个问题在最新的2.6.5版本上依然存在，查了下代码，都这么久了，#1999竟然没有被合并到新版本里。虽然在最新的2.6.x分支上已经看到了修改，但是什么时候发布下一个版本呢？
