### ISSUE TITLE
启动 dubbo-admin时报错

### ISSUE THREAD

**Issue by jimwarewj** [apache/incubator-dubbo#1767]
什么原因呢？
ERROR dubbo.DubboRegistry -  [DUBBO] Failed to subscribe consumer://127.0.0.1/com.alibaba.dubbo.registry.RegistryService?application=dubbo-admin&callbacks=10000&check=false&connect.timeout=10000&dubbo=2.5.8&file=false&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,unsubscribe,subscribe,unregister,register&pid=13296&reconnect=false&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1525917740262&unsubscribe.1.callback=false, waiting for retry, cause: Failed to invoke the method subscribe in the service com.alibaba.dubbo.registry.RegistryService. Tried 3 times of the providers [127.0.0.1:2181] (1/1) from the registry 127.0.0.1:2181 on the consumer 127.0.0.1 using the dubbo version 2.5.8. Last error is: Invoke remote method timeout. method: subscribe, provider: dubbo://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=dubbo-admin&callbacks=10000&check=false&connect.timeout=10000&dubbo=2.5.8&file=false&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,unsubscribe,subscribe,unregister,register&pid=13296&reconnect=false&remote.timestamp=1525917740262&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1525917740262&unsubscribe.1.callback=false, cause: Waiting server-side response timeout by scan timer. start time: 2018-05-10 10:02:42.834, end time: 2018-05-10 10:02:52.839, client elapsed: 80 ms, server elapsed: 9922 ms, timeout: 10000 ms, request: Request [id=4, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=subscribe, parameterTypes=[class com.alibaba.dubbo.common.URL, interface com.alibaba.dubbo.registry.NotifyListener], arguments=[consumer://127.0.0.1/com.alibaba.dubbo.registry.RegistryService?application=dubbo-admin&callbacks=10000&check=false&connect.timeout=10000&dubbo=2.5.8&file=false&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,unsubscribe,subscribe,unregister,register&pid=13296&reconnect=false&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1525917740262&unsubscribe.1.callback=false, com.alibaba.dubbo.registry.integration.RegistryDirectory@6552c628], attachments={path=com.alibaba.dubbo.registry.RegistryService, sys_callback_arg-1=1699923496, interface=com.alibaba.dubbo.registry.RegistryService, version=0.0.0, timeout=10000}]], channel: 127.0.0.1:0 -> 127.0.0.1/10.6.217.103:2181, dubbo version: 2.5.8, current host: 127.0.0.1
com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method subscribe in the service com.alibaba.dubbo.registry.RegistryService. Tried 3 times of the providers [127.0.0.1:2181] (1/1) from the registry 127.0.0.1:2181 on the consumer 127.0.0.1 using the dubbo version 2.5.8. Last error is: Invoke remote method timeout. method: subscribe, provider: dubbo://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=dubbo-admin&callbacks=10000&check=false&connect.timeout=10000&dubbo=2.5.8&file=false&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,unsubscribe,subscribe,unregister,register&pid=13296&reconnect=false&remote.timestamp=1525917740262&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1525917740262&unsubscribe.1.callback=false, cause: Waiting server-side response timeout by scan timer. start time: 2018-05-10 10:02:42.834, end time: 2018-05-10 10:02:52.839, client elapsed: 80 ms, server elapsed: 9922 ms, timeout: 10000 ms, request: Request [id=4, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=subscribe, parameterTypes=[class com.alibaba.dubbo.common.URL, interface com.alibaba.dubbo.registry.NotifyListener], arguments=[consumer://127.0.0.1/com.alibaba.dubbo.registry.RegistryService?application=dubbo-admin&callbacks=10000&check=false&connect.timeout=10000&dubbo=2.5.8&file=false&interface=com.alibaba.dubbo.registry.RegistryService&lazy=true&methods=lookup,unsubscribe,subscribe,unregister,register&pid=13296&reconnect=false&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1525917740262&unsubscribe.1.callback=false, com.alibaba.dubbo.registry.integration.RegistryDirectory@6552c628], attachments={path=com.alibaba.dubbo.registry.RegistryService, sys_callback_arg-1=1699923496, interface=com.alibaba.dubbo.registry.RegistryService, version=0.0.0, timeout=10000}]], channel: 127.0.0.1:0 -> 127.0.0.1/127.0.0.1:2181
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:108)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:229)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)

**Comment by jimwarewj** [comment]
解决
