### ISSUE TITLE
qos-server can not bind localhost:22222

### ISSUE THREAD

**Issue by zhuguoming** [apache/incubator-dubbo#1826]
```
 ERROR com.alibaba.dubbo.qos.server.Server -  [DUBBO] qos-server can not bind localhost:22222, dubbo version: 2.0.1, current host: 192.168.50.230 java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_101]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_101]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_101]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_101]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:127) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:512) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:497) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:363) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[netty-all-4.1.6.Final.jar:4.1.6.Final]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_101]
```

**Comment by ralf0131** [comment]
> Address already in use.

Do you have multiple process in one single machine?

**Comment by sunshinebaby00** [comment]
Are you running the dubbo-test program?You can delete the dependency of dubbo-qos in the pom.xml.
```
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo-qos</artifactId>
</dependency>
```

**Comment by zhuguoming** [comment]
no,how to set qos port in spring? @KissSai

**Comment by YoungHu** [comment]
now we can't rewrite the default port in spring, just change it by dubbo.properties

**Comment by ralf0131** [comment]
QOS can be disabled by programmable API in ApplicationConfig#setQosEnable, therefore is should be configurable if you are using Java API.

If you are running Dubbo in [spring-boot](https://github.com/apache/incubator-dubbo-spring-boot-project), you can configure in application.properties:

```
dubbo.application.qos.enable=false
```

For XML configuration, I think we can't disabled for now, that is task to be fixed.

You can work it around by specifying another port in dubbo.properties.

```
dubbo.application.qos.port=33333
```
