### ISSUE TITLE
dubbo-test缺失依赖，运行时报错

### ISSUE THREAD

**Issue by sunshinebaby00** [apache/incubator-dubbo#1840]
运行dubbo-test内的项目时报错
```
Caused by: java.lang.IllegalStateException: No such extension com.alibaba.dubbo.common.serialize.Serialization by name hessian2
	at com.alibaba.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:482)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:489)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:309)
	at com.alibaba.dubbo.remoting.transport.CodecSupport.getSerialization(CodecSupport.java:63)
	at com.alibaba.dubbo.remoting.transport.AbstractCodec.getSerialization(AbstractCodec.java:51)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encodeRequest(ExchangeCodec.java:208)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:70)
```
dubbo-test的pom文件添加依赖解决问题
```
    <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo-serialization-hessian2</artifactId>
        </dependency>
```

**Comment by diecui1202** [comment]
Hi, are you running examples in dubbo-test? 

Now we transfer examples to http://github.com/dubbo/dubbo-samples 

You can get more information from there.

**Comment by sunshinebaby00** [comment]
It is helpful for me. I will try,soon.
Thank you!
