### ISSUE TITLE
Could not start com.alibaba.dubbo.container.Main#main from IDE

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo#1844]
Could not found an easy way to run `com.alibaba.dubbo.container.Main#main` from IDE.

```
log4j:WARN No appenders could be found for logger (com.alibaba.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.IllegalStateException: No such extension com.alibaba.dubbo.container.Container by name spring
	at com.alibaba.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:482)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:489)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:309)
	at com.alibaba.dubbo.container.Main.main(Main.java:59)
Disconnected from the target VM, address: '127.0.0.1:63787', transport: 'socket'

Process finished with exit code 1
```

I think we should not place `com.alibaba.dubbo.container.Main` under `dubbo-container-api`

**Comment by diecui1202** [comment]
I think `com.alibaba.dubbo.container.Main#main` is not used for IDE, you need to add this dependency to your application, and run it with the bash script within META-INF/assembly/bin
