### ISSUE TITLE
dubbo 使用Kryo和FST 调用异常  版本2.6.1

### ISSUE THREAD

**Issue by abocode** [apache/incubator-dubbo#1871]
```
cause: Could not initialize class com.alibaba.dubbo.common.serialize.kryo.utils.KryoUtils
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:106) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.remoting.transport.AbstractClient.send(AbstractClient.java:256) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:52) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeChannel.request(HeaderExchangeChannel.java:111) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeClient.request(HeaderExchangeClient.java:86) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.request(ReferenceCountExchangeClient.java:77) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:95) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:142) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:74) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:47) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:73) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:52) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:233) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:70) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:51) ~[dubbo-2.6.1.jar:2.6.1]
	at com.alibaba.dubbo.common.bytecode.proxy0.findOneWithAll(proxy0.java) ~[dubbo-2.6.1.jar:2.6.1]
```

**Comment by diecui1202** [comment]
hi, @abocode Could you please provider a demo for us to check this problem?
