### ISSUE TITLE
dubbo invoke a method has :HessianProtocolException: '￿' is an unknown code

### ISSUE THREAD

**Issue by lvhongfen** [apache/incubator-dubbo#1901]
Search Engines told me that error may cased by "hessian" is not support override method default.So i try to set this property ,"isOverloadEnabled".But i can not find the way to set

**Comment by lvhongfen** [comment]
com.caucho.hessian.client.HessianRuntimeException: com.caucho.hessian.io.HessianProtocolException: '￿' is an unknown code
	at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:222) ~[hessian-4.0.38.jar:na]
	at com.sun.proxy.$Proxy159.uploadFile(Unknown Source) ~[na:na]
	at com.alibaba.dubbo.common.bytecode.Wrapper19.invokeMethod(Wrapper19.java) ~[na:2.5.3]
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.AbstractProxyProtocol$2.doInvoke(AbstractProxyProtocol.java:93) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144) ~[dubbo-2.5.3.jar:2.5.3]
	at cn.gov.wu.biz.common.interceptor.ConsumerDubboFilter.invoke(ConsumerDubboFilter.java:31) ~[cloud-commons-biz-1.0.0.jar:na]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:65) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74) [dubbo-2.5.3.jar:2.5.3]

**Comment by ralf0131** [comment]
duplicated issue to #1136

**Comment by lvhongfen** [comment]
<dubbo:application name="${greenline.dubbo.application.name}" />
    
    <dubbo:registry address="${greenline.dubbo.registry.address}"/>
    
    <dubbo:consumer filter="default,consumerDubboFilter" />
    
    <dubbo:reference id="kanoFileService" interface="com.greenline.kano.service.share.file.KanoFileService" check="false"/>


this is my XML ,How to set overloadEnabled=true ?

**Comment by ralf0131** [comment]
Please check the documentation: http://dubbo.apache.org/books/dubbo-user-book/references/protocol/hessian.html. 

```xml
<dubbo:reference id="helloService" interface="HelloWorld" url="hessian://10.20.153.10:8080/helloWorld" />
```

You can config `hessian.overload.method=true` in url.

**Comment by lvhongfen** [comment]
服务是在注册中心调用的请求也不一定是分配到哪台服务器上，
不能在配置里面把url写死呀

**Comment by lvhongfen** [comment]
能否有配置的方式解决？

**Comment by chickenlj** [comment]
@lvhongfen Try use `dubbo.properties` and add the following item:
```properties
dubbo.service.hessian.overload.method
```

**Comment by lvhongfen** [comment]
文件上传没有问题，自定义filter报错

**Comment by lvhongfen** [comment]
其他使用了hession的dubbo服务也报错

**Comment by lvhongfen** [comment]
服务没问题，filter 中invoke的result结果异常

**Comment by braveCS** [comment]
注册中心配置成zookeeper://xxx.xxx.xxx.xx:xxx?hessian.overload.method=true
