### ISSUE TITLE
GenericService.$invoke Parameter support problem

### ISSUE THREAD

**Issue by ningyu1** [apache/incubator-dubbo#2003]
char[] type parameter support issues.

Use Dubbo version: V2.6.2 (consumer and provider versions are the same)
Use Protocol: dubbo
Use Serialize: hessian2

Consumer debug information:

![image](https://user-images.githubusercontent.com/3387548/42010363-e944cb86-7ac0-11e8-8c27-6695d8f2681b.png)
![image](https://user-images.githubusercontent.com/3387548/42016165-1b7e2e1e-7add-11e8-8e71-ad1b30a635e5.png)

Provider code:

```
public String sayHello(long[] num, int[] arg, char[] name);
```

Provider error:
```
2018-06-28 10:45:02.377 [DubboServerHandler-192.168.6.47:20880-thread-102] ERROR com.alibaba.dubbo.rpc.filter.ExceptionFilter -  [DUBBO] Got unchecked and undeclared exception which called by 192.168.6.47. service: com.jiuyescm.dubbo.test.api.MyClassService, method: sayHello, exception: java.lang.ClassCastException: java.lang.String cannot be cast to [C, dubbo version: 2.6.2, current host: 192.168.6.47
java.lang.ClassCastException: java.lang.String cannot be cast to [C
	at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:76) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:52) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:62) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:105) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:103) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) [dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80) [dubbo-2.6.2.jar:2.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
```

Provider debug information: 

![image](https://user-images.githubusercontent.com/3387548/42017939-3290ae64-7ae3-11e8-931f-090430da7219.png)
![image](https://user-images.githubusercontent.com/3387548/42017951-39d588a2-7ae3-11e8-868f-39cc5de5f39e.png)

Consumer send message: 

![image](https://user-images.githubusercontent.com/3387548/42023421-54ee635c-7af2-11e8-994a-a5393c9865f4.png)
![image](https://user-images.githubusercontent.com/3387548/42023381-494e9f76-7af2-11e8-83ad-16c03c7645eb.png)

Provider receive and decoded: 

in is `com.alibaba.dubbo.common.serialize.hessian2.Hessian2ObjectInput`

![image](https://user-images.githubusercontent.com/3387548/42023488-8a018ea2-7af2-11e8-9c7f-91ae61a99e2c.png)

**Comment by diecui1202** [comment]
May be you need use the following value as the parameterTypes
* long[].class.getName()
* int[].class.getName()
* char[].class.getName()

You can try it out.

**Comment by ningyu1** [comment]
@diecui1202 thanks.
Tried it, but still reported the wrong.

**Comment by diecui1202** [comment]
@ningyu1 I got the same exception. 

Sample is here: https://github.com/diecui1202/dubbo-samples/tree/samples-2.7.x/dubbo-samples-genericinvoke

**Comment by zonghaishang** [comment]
fixed, refer: https://github.com/apache/incubator-dubbo/commit/0882c83bb9c772966d57cbf161a60ec3633f1e1e

**Comment by ningyu1** [comment]
@diecui1202 @zonghaishang thanks
