### ISSUE TITLE
xsd not found

### ISSUE THREAD

**Issue by wingyiu** [apache/incubator-dubbo#2027]
````
org.xml.sax.SAXParseException; lineNumber: 11; columnNumber: 37; schema_reference.4: Failed to read schema document 'http://dubbo.apache.org/schema/dubbo/dubbo.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.warning(ErrorHandlerWrapper.java:99)
````

**Comment by ralf0131** [comment]
Hi, this is caused by the new website transition. I am working on it.

**Comment by ralf0131** [comment]
Please try again. It is fixed.
