### ISSUE TITLE
get started docs sucks

### ISSUE THREAD

**Issue by wingyiu** [apache/incubator-dubbo#2028]
````
INFO:  [DUBBO] Start NettyServer bind /0.0.0.0:20880, export /172.20.206.64:20880, dubbo version: 2.0.1, current host: 172.20.206.64
Exception in thread "main" java.lang.IllegalArgumentException: Invalid multicast address 172.20.10.222, scope: 224.0.0.0 - 239.255.255.255
	at com.alibaba.dubbo.registry.multicast.MulticastRegistry.<init>(MulticastRegistry.java:82)
	at com.alibaba.dubbo.registry.multicast.MulticastRegistryFactory.createRegistry(MulticastRegistryFactory.java:30)
````

**Comment by luyuanwan** [comment]
Your multicast address is invalid, the valid score is 224.0.0.0 - 239.255.255.255.   You see ?

**Comment by wingyiu** [comment]
@luyuanwan no, i mean to use zookeeper。but no examples or docs mention

**Comment by kimmking** [comment]
@wingyiu
I got it, but you can submit a PR to fix/add some details such as docs or sample-codes for this.

**Comment by ralf0131** [comment]
Please check out the examples here: https://github.com/dubbo/dubbo-samples

Most of them are using embedded zookeeper.
