### ISSUE TITLE
Dubbo should pre check if serialization had already been failed.

### ISSUE THREAD

**Issue by chutian52** [apache/incubator-dubbo#2050]
### Environment

* Dubbo version: 2.6.1
* Operating System version: Fedora 27
* Java version: openjdk 1.8.0_171

### Step to reproduce this issue
* protocol: dubbo
* server: netty4
* serialization: kryo
 when we use `java.util.ArrayList` method `subList`, kyro use `com.esotericsoftware.kryo.serializers.JavaSerializer` to serialize `java.util.ArrayList$SubList`
2. NettyCodecAdapter$InternalEncoder had been throw `io.netty.handler.codec.EncoderException: com.esotericsoftware.kryo.KryoException: Error during Java serialization.`
3. Dubbo did not throw EncoderException, it throwed TimeoutException.
```
Caused by: com.alibaba.dubbo.remoting.TimeoutException: Waiting server-side response timeout. start time: 2018-07-09 09:55:58.203, end time: 2018-07-09 09:56:00.204, client elapsed: 13 ms, server elapsed: 1988 ms, timeout: 2000 ms, request: Request [id=1, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=getProductTaxFinance, parameterTypes=[interface java.util.List], arguments=[[100000, 14594]], attachments={path=com.xx.product.micro.service.IProductService, interface=com.xx.product.micro.service.IProductService, version=0.0.1, timeout=2000}]], channel: /10.1.14.108:55760 -> /10.1.62.230:19025
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:134)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:111)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:95)
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:142)
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:73)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:74)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:47)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:52)
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
	... 92 common frames omitted
```

### Expected Result

Dubbo should pre check if DefaultChannelPromise had already been failed.

**Comment by web1992** [comment]
I agree this. Sometimes I forget `implements Serializable`. I get `TimeoutException` it confused for me.

**Comment by beiwei30** [comment]
this is a known issue, I will fix it soon.

**Comment by lovepoem** [comment]
>https://github.com/apache/incubator-dubbo/commit/d2ae941502410fbbf937e654b25f1399eedd3fbf should fix this issue.

@chutian52 Would you please have a try?

**Comment by chutian52** [comment]
@lovepoem It works. Thanks  all of you. Should I close this or depends on you?
