### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by zhaijw** [apache/incubator-dubbo#2064]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/wiki/FAQ) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: x86_64 GNU/Linux
* Java version: 1.7.0_80

### Step to reproduce this issue

1. IPV6-zookeeper 连接地址：修改provide端连接zookeeper-IPV6的地址
2.启动错误信息：

```
java.lang.NumberFormatException: For input string: ":d243:1eff:fefa:8a47]:12189"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.7.0_80]
        at java.lang.Integer.parseInt(Integer.java:492) ~[?:1.7.0_80]
        at java.lang.Integer.parseInt(Integer.java:527) ~[?:1.7.0_80]
        at com.alibaba.dubbo.common.URL.valueOf(URL.java:239) ~[dubbo-2.6.2.jar:2.6.2]
        at com.alibaba.dubbo.common.utils.UrlUtils.parseURL(UrlUtils.java:68) ~[dubbo-2.6.2.jar:2.6.2]
        at com.alibaba.dubbo.common.utils.UrlUtils.parseURLs(UrlUtils.java:137) ~[dubbo-2.6.2.jar:2.6.2]
        at com.alibaba.dubbo.config.AbstractInterfaceConfig.loadRegistries(AbstractInterfaceConfig.java:190) ~[dubbo-2.6.2.jar:2.6.2]
        at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:356) ~[dubbo-2.6.2.jar:2.6.2]
        at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:317) ~[dubbo-2.6.2.jar:2.6.2]
        at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:216) ~[dubbo-2.6.2.jar:2.6.2]
        at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:123) ~[dubbo-2.6.2.jar:2.6.2]
        at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:49) ~[dubbo-2.6.2.jar:2.6.2]
```

**Comment by zhaijw** [comment]
@justinmclean

**Comment by ralf0131** [comment]
I am looking at this issue. I have a fix already, and I am doing some test locally.

**Comment by zonghaishang** [comment]
fixed, closed it now.
