### ISSUE TITLE
dubbo 2.6.3 is not compatible with dubbo >= 2.5.9

### ISSUE THREAD

**Issue by jasonjoo2010** [apache/incubator-dubbo#2174]
- [X] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [X] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.9~2.5.10
* Operating System version: any
* Java version: any

### Step to reproduce this issue

response with attachments is a new feature in release 2.6.3.

but its compatible versions are set to ![2.0.10 ~ 2.6.2] while the "ProtocolVersion" had bean changed to 2.0.1 (implementation version) and 2.0.0 (specification version).

the priority of "implementation version" is greater than other in Version.getVersion.

this will cause dubbo rpc request failing from >2.5.9 to 2.6.3.

So is that a good idea to upgrade the lowest protocol version of attachment-feature to 2.0.2?

it's a big problem

### Expected Result

compatible

### Actual Result

fail

**Comment by jasonjoo2010** [comment]
You can switch the consumer's dubbo to 2.5.9 or 2.5.10 and make rpc calling to provider which dubbo version is 2.6.3, it will fail.

```
Caused by: com.alibaba.dubbo.remoting.RemotingException: java.io.IOException: Unknown result flag, expect '0' '1' '2', get 4
java.io.IOException: Unknown result flag, expect '0' '1' '2', get 4
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:98)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult.decode(DecodeableRpcResult.java:106)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:88)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:120)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:81)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:44)
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalDecoder.messageReceived(NettyCodecAdapter.java:133)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:218)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:137)
	at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:111)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:95)
	at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:142)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:74)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:47)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:73)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:52)
	at com.alibaba.dubbo.rpc.cluster.support.FailfastClusterInvoker.doInvoke(FailfastClusterInvoker.java:47)
	... 54 more
```

**Comment by diecui1202** [comment]
@jasonjoo2010 I do have reproduce it. Thanks.

Now I suggest cancel the release for 2.6.3, then fix it, and start a new release.

**Comment by chickenlj** [comment]
Hi @jasonjoo2010 , would you mind to send a PR to solve this compatible problem?

**Comment by jasonjoo2010** [comment]
@chickenlj patch to which branch?

2.6.3-release/2.6.x/master ?

**Comment by edwardlee03** [comment]
RPC调用场景：2.5.8-consumer -> 2.6.5-provider
Dubbo版本明明是2.6.5，结果URL里却是dubbo=2.0.2，和先前实现逻辑不一样。
为什么把这个调整了呢？这样做不能向下兼容，大坑啊

**Comment by lastboy1228** [comment]
> 调用场景：2.5.8-consumer -> 2.6.5-provider
> Dubbo版本明明是2.6.5，结果URL里却是dubbo协议版本(`dubbo=2.0.2`)，和先前实现逻辑不一样。
> 请问这样调整后是否向前兼容？能否做到增量平滑升级？

The client always registried itself as dubbo=2.0.2, from version 2.6.3 to version 2.6.7.

**Comment by jasonjoo2010** [comment]
> 调用场景：2.5.8-consumer -> 2.6.5-provider
> Dubbo版本明明是2.6.5，结果URL里却是dubbo协议版本(`dubbo=2.0.2`)，和先前实现逻辑不一样。
> 请问这样调整后是否向前兼容？能否做到增量平滑升级？

And more, 2.0.2 is `protocol` version, while 2.6.5 is `implementation` version. They are not the same.

`dubbo=` in url is exactly the protocol version and it indeed is backward compatible.

**Comment by edwardlee03** [comment]
> > 调用场景：2.5.8-consumer -> 2.6.5-provider
> > Dubbo版本明明是2.6.5，结果URL里却是dubbo协议版本(`dubbo=2.0.2`)，和先前实现逻辑不一样。
> > 请问这样调整后是否向前兼容？能否做到增量平滑升级？
> 
> And more, 2.0.2 is `protocol` version, while 2.6.5 is `implementation` version. They are not the same.
> 
> `dubbo=` in url is exactly the protocol version and it indeed is backward compatible.

I know you say, but before `2.6.0` version, `dubbo=` in url is `implementation` version, not the `protocol` version. As in fact, from `2.5.10` to `2.6.2`, dubbo protocol is not backward compatible, our colleagues have encountered this problem. I'm responsible for the dubbo in our compony.

**Comment by jasonjoo2010** [comment]
> 
> @jasonjoo2010 @lastboy1228
> Thanks for you answer, but before `2.6.0` version, `dubbo=` in url is `implementation` version, not the `protocol` version. As in fact, from `2.5.10` to `2.6.2`, dubbo protocol is not backward compatible, our colleagues have encountered this problem. I'm responsible for the dubbo in our compony. 😃

Yes indeed.
The implementation version in previous dubbo will be treated as `2.0.1` automatically. So invocation should not be affected.

Do you suffer some kinds of failure or just use the value in `dubbo=` to do other things?

**Comment by jasonjoo2010** [comment]
> 
> @jasonjoo2010 @lastboy1228
> Thanks for you answer, but before `2.6.0` version, `dubbo=` in url is `implementation` version, not the `protocol` version. As in fact, from `2.5.10` to `2.6.2`, dubbo protocol is not backward compatible, our colleagues have encountered this problem. I'm responsible for the dubbo in our compony. 😃

Oh I am sorry I just notice the version you mentioned is 2.5.10. The two releases (2.5.9, 2.5.10) may be the issued version so they are not recommended to use in production. (It can be downgrade to 2.5.8)

And because there are also some issue in 2.6.x it's recommended to upgrade to 2.7.x ASAP.
