### ISSUE TITLE
Unsupported protocol hessian when using API Configuration and Generic Reference

### ISSUE THREAD

**Issue by cwt9562** [apache/incubator-dubbo#2181]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.5.10
* Operating System version: win10
* Java version: 10

### Step to reproduce this issue

1. add dependency hessian into maven

```
<dependency>
    <groupId>com.caucho</groupId>
    <artifactId>hessian</artifactId>
    <version>4.0.7</version>
</dependency>
```

2. Use API Configuration to setup a consumer, with spring-boot
3. Use Generic Reference to invoke a remote provider, using protocol hessian

### Actual Result

got a error:

```
java.lang.IllegalStateException: Unsupported protocol hessian in notified url: hessian://x.x.x.x:8081/com.xx.xx.xx.mock.dubbo.provider.dubbo.GenericReferenceHessianProtocolProvider?accesslog=true&anyhost=true&application=mock-dubbo-provider&default.delay=-1&delay=-1&dubbo=2.0.1&generic=false&interface=com.xx.xx.xx.mock.dubbo.provider.dubbo.GenericReferenceHessianProtocolProvider&methods=getInputStreamByUrl,getInputStream&pid=15020&server=jetty&side=provider&timestamp=1533283864686 from registry localhost:2181 to consumer x.x.x.x, supported protocol: [dubbo, http, injvm, mock, redis, registry, rmi, thrift]
```

If there is an exception, please attach the exception trace:

```
2018-08-03 17:28:45.564 ERROR 26132 --- [           main] c.a.d.r.integration.RegistryDirectory    : Unsupported protocol hessian in notified url: hessian://x.x.x.x:8081/com.xx.xx.xx.mock.dubbo.provider.dubbo.GenericReferenceHessianProtocolProvider?accesslog=true&anyhost=true&application=mock-dubbo-provider&default.delay=-1&delay=-1&dubbo=2.0.1&generic=false&interface=com.xx.xx.xx.mock.dubbo.provider.dubbo.GenericReferenceHessianProtocolProvider&methods=getInputStreamByUrl,getInputStream&pid=15020&server=jetty&side=provider&timestamp=1533283864686 from registry localhost:2181 to consumer x.x.x.x, supported protocol: [dubbo, http, injvm, mock, redis, registry, rmi, thrift]

java.lang.IllegalStateException: Unsupported protocol hessian in notified url: hessian://x.x.x.x:8081/com.xx.xx.xx.mock.dubbo.provider.dubbo.GenericReferenceHessianProtocolProvider?accesslog=true&anyhost=true&application=mock-dubbo-provider&default.delay=-1&delay=-1&dubbo=2.0.1&generic=false&interface=com.xx.xx.xx.mock.dubbo.provider.dubbo.GenericReferenceHessianProtocolProvider&methods=getInputStreamByUrl,getInputStream&pid=15020&server=jetty&side=provider&timestamp=1533283864686 from registry localhost:2181 to consumer x.x.x.x, supported protocol: [dubbo, http, injvm, mock, redis, registry, rmi, thrift]
    at com.alibaba.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:362)
    at com.alibaba.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:251)
    at com.alibaba.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:221)
    at com.alibaba.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:407)
    at com.alibaba.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:273)
    at com.alibaba.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:259)
    at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:182)
    at com.alibaba.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:189)
    at com.alibaba.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:159)
    at com.alibaba.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:302)
    at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:283)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:98)
    at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:63)
    at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:63)
    at com.alibaba.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
    at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:394)
    at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:333)
    at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:163)
    at com.xx.xx.api.gateway.gateway.config.test.DubboHessianGenericDomeTest.getGenericService(DubboHessianGenericDomeTest.java:60)
    at com.xx.xx.api.gateway.gateway.config.test.DubboHessianGenericDomeTest.testInputStream(DubboHessianGenericDomeTest.java:44)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
    at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
    at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

2018-08-03 17:28:45.565 ERROR 26132 --- [           main] c.a.d.r.integration.RegistryDirectory    : urls to invokers error .invokerUrls.size :1, invoker.size :0. urls :[hessian://x.x.x.x:8081/com.xx.xx.xx.mock.dubbo.provider.dubbo.GenericReferenceHessianProtocolProvider?accesslog=true&anyhost=true&application=mock-dubbo-provider&default.delay=-1&delay=-1&dubbo=2.0.1&generic=false&interface=com.xx.xx.xx.mock.dubbo.provider.dubbo.GenericReferenceHessianProtocolProvider&methods=getInputStreamByUrl,getInputStream&pid=15020&server=jetty&side=provider&timestamp=1533283864686]

java.lang.IllegalStateException: urls to invokers error .invokerUrls.size :1, invoker.size :0. urls :[hessian://x.x.x.x:8081/com.xx.xx.xx.mock.dubbo.provider.dubbo.GenericReferenceHessianProtocolProvider?accesslog=true&anyhost=true&application=mock-dubbo-provider&default.delay=-1&delay=-1&dubbo=2.0.1&generic=false&interface=com.xx.xx.xx.mock.dubbo.provider.dubbo.GenericReferenceHessianProtocolProvider&methods=getInputStreamByUrl,getInputStream&pid=15020&server=jetty&side=provider&timestamp=1533283864686]
    at com.alibaba.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:256)
    at com.alibaba.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:221)
    at com.alibaba.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:407)
    at com.alibaba.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:273)
    at com.alibaba.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:259)
    at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:182)
    at com.alibaba.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:189)
    at com.alibaba.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:159)
    at com.alibaba.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:302)
    at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:283)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:98)
    at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:63)
    at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:63)
    at com.alibaba.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
    at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:394)
    at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:333)
    at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:163)
    at com.xx.xx.api.gateway.gateway.config.test.DubboHessianGenericDomeTest.getGenericService(DubboHessianGenericDomeTest.java:60)
    at com.xx.xx.api.gateway.gateway.config.test.DubboHessianGenericDomeTest.testInputStream(DubboHessianGenericDomeTest.java:44)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
    at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
    at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
    at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
    at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
    at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by diecui1202** [comment]
@cwt9562 Could you please provider a demo for us to reproduce the problem ?

**Comment by chickenlj** [comment]
Did you specify the protocols to consume on the Consumer side? If so, make sure `hessian` included.
For example:
```xml
<dubbo:reference protocol="dubbo"/>
<!-- or -->
<dubbo:consumer protocol="dubbo"/>
```

**Comment by cwt9562** [comment]
I reimport maven dependencies 
then system dont throw this exception
so, no bug
