### ISSUE TITLE
dubbo(2.5.3),jdk7 .启动tomcat服务的时候报错。

### ISSUE THREAD

**Issue by coolearn** [apache/incubator-dubbo#221]
java.lang.RuntimeException: Inconsistent args count operand in invokeinterface
Exception Details:
  Location:
    com/alibaba/dubbo/common/bytecode/Wrapper6.invokeMethod(Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Class;[Ljava/lang/Object;)Ljava/lang/Object; @405: invokeinterface
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2bc0 003b 3a05 a700 0f3a 06bb 003f 5919
    0000010: 06b7 0043 bf12 602c b600 6599 0009 2dbe
    0000020: 059f 0006 a700 1919 0519 0403 32c0 0062
    0000030: 1904 0432 c000 67b9 006a 0300 b012 6c2c
    0000040: b600 6599 0009 2dbe 059f 0006 a700 2219
    0000050: 0519 0403 32c0 0062 1904 0432 c000 6eb9
    0000060: 0071 0300 bb00 7359 5d58 b700 76b0 1278
    0000070: 2cb6 0065 9900 092d be05 9f00 06a7 0022
    0000080: 1905 1904 0332 c000 6219 0404 32c0 006e
    0000090: b900 7a03 00bb 0073 595d 58b7 0076 b012
    00000a0: 7c2c b600 6599 0009 2dbe 059f 0006 a700
    00000b0: 1a19 0519 0403 32c0 0062 1904 0432 c000
    00000c0: 6eb9 007f 0300 01b0 1281 2cb6 0065 9900
    00000d0: 092d be05 9f00 06a7 0019 1905 1904 0332
    00000e0: c000 6219 0404 32c0 0083 b900 8603 00b0
    00000f0: 1288 2cb6 0065 9900 092d be05 9f00 06a7
    0000100: 0019 1905 1904 0332 c000 6219 0404 32c0
    0000110: 0067 b900 8b03 00b0 128d 2cb6 0065 9900
    0000120: 092d be05 9f00 06a7 0019 1905 1904 0332
    0000130: c000 6219 0404 32c0 006e b900 9003 00b0
    0000140: 1292 2cb6 0065 9900 092d be05 9f00 06a7
    0000150: 001a 1905 1904 0332 c000 6219 0404 32c0
    0000160: 0083 b900 9503 0001 b012 972c b600 6599
    0000170: 0009 2dbe 069f 0006 a700 2319 0519 0403
    0000180: 32c0 0062 1904 0432 c000 6719 0405 32c0
    0000190: 0099 b600 9db9 00a0 0500 b0a7 000f 3a07
    00001a0: bb00 a259 1907 b700 a3bf bb00 a559 bb00
    00001b0: 4759 b700 4a12 a7b6 0050 2cb6 0050 12a9
    00001c0: b600 50b6 0056 b700 aabf  
  Exception Handler Table:
    bci [0, 6] => handler: 9
    bci [21, 411] => handler: 414
  Stackmap Table:
    same_locals_1_stack_item_frame(@9,Object[#61])
    append_frame(@21,Object[#59])
    same_frame(@36)
    same_frame(@39)
    same_frame(@61)
    same_frame(@76)
    same_frame(@79)
    same_frame(@110)
    same_frame(@125)
    same_frame(@128)
    same_frame(@159)
    same_frame(@174)
    same_frame(@177)
    same_frame(@200)
    same_frame(@215)
    same_frame(@218)
    same_frame(@240)
    same_frame(@255)
    same_frame(@258)
    same_frame(@280)
    same_frame(@295)
    same_frame(@298)
    same_frame(@320)
    same_frame(@335)
    same_frame(@338)
    same_frame(@361)
    same_frame(@376)
    same_frame(@379)
    same_frame(@411)
    same_locals_1_stack_item_frame(@414,Object[#61])
    same_frame(@426)

```
at com.alibaba.dubbo.common.bytecode.Wrapper.makeWrapper(Wrapper.java:363) ~[dubbo-2.5.3.jar:2.5.3]
at com.alibaba.dubbo.common.bytecode.Wrapper.getWrapper(Wrapper.java:89) ~[dubbo-2.5.3.jar:2.5.3]
at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:426) ~[dubbo-2.5.3.jar:2.5.3]
at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:281) ~[dubbo-2.5.3.jar:2.5.3]
at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:242) ~[dubbo-2.5.3.jar:2.5.3]
at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:143) ~[dubbo-2.5.3.jar:2.5.3]
at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:109) ~[dubbo-2.5.3.jar:2.5.3]
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97) ~[spring-context-3.1.1.RELEASE.jar:3.1.1.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:324) ~[spring-context-3.1.1.RELEASE.jar:3.1.1.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:929) ~[spring-context-3.1.1.RELEASE.jar:3.1.1.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:467) ~[spring-context-3.1.1.RELEASE.jar:3.1.1.RELEASE]
at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:385) ~[spring-web-3.1.1.RELEASE.jar:3.1.1.RELEASE]
at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:284) ~[spring-web-3.1.1.RELEASE.jar:3.1.1.RELEASE]
at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111) [spring-web-3.1.1.RELEASE.jar:3.1.1.RELEASE]
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4887) [catalina.jar:7.0.39]
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5381) [catalina.jar:7.0.39]
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.39]
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [catalina.jar:7.0.39]
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [catalina.jar:7.0.39]
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633) [catalina.jar:7.0.39]
at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:657) [catalina.jar:7.0.39]
at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1637) [catalina.jar:7.0.39]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_55]
at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_55]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_55]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_55]
at java.lang.Thread.run(Thread.java:745) [na:1.7.0_55]
```

Caused by: java.lang.VerifyError: Inconsistent args count operand in invokeinterface
Exception Details:
  Location:
    com/alibaba/dubbo/common/bytecode/Wrapper6.invokeMethod(Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Class;[Ljava/lang/Object;)Ljava/lang/Object; @405: invokeinterface
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2bc0 003b 3a05 a700 0f3a 06bb 003f 5919
    0000010: 06b7 0043 bf12 602c b600 6599 0009 2dbe
    0000020: 059f 0006 a700 1919 0519 0403 32c0 0062
    0000030: 1904 0432 c000 67b9 006a 0300 b012 6c2c
    0000040: b600 6599 0009 2dbe 059f 0006 a700 2219
    0000050: 0519 0403 32c0 0062 1904 0432 c000 6eb9
    0000060: 0071 0300 bb00 7359 5d58 b700 76b0 1278
    0000070: 2cb6 0065 9900 092d be05 9f00 06a7 0022
    0000080: 1905 1904 0332 c000 6219 0404 32c0 006e
    0000090: b900 7a03 00bb 0073 595d 58b7 0076 b012
    00000a0: 7c2c b600 6599 0009 2dbe 059f 0006 a700
    00000b0: 1a19 0519 0403 32c0 0062 1904 0432 c000
    00000c0: 6eb9 007f 0300 01b0 1281 2cb6 0065 9900
    00000d0: 092d be05 9f00 06a7 0019 1905 1904 0332
    00000e0: c000 6219 0404 32c0 0083 b900 8603 00b0
    00000f0: 1288 2cb6 0065 9900 092d be05 9f00 06a7
    0000100: 0019 1905 1904 0332 c000 6219 0404 32c0
    0000110: 0067 b900 8b03 00b0 128d 2cb6 0065 9900
    0000120: 092d be05 9f00 06a7 0019 1905 1904 0332
    0000130: c000 6219 0404 32c0 006e b900 9003 00b0
    0000140: 1292 2cb6 0065 9900 092d be05 9f00 06a7
    0000150: 001a 1905 1904 0332 c000 6219 0404 32c0
    0000160: 0083 b900 9503 0001 b012 972c b600 6599
    0000170: 0009 2dbe 069f 0006 a700 2319 0519 0403
    0000180: 32c0 0062 1904 0432 c000 6719 0405 32c0
    0000190: 0099 b600 9db9 00a0 0500 b0a7 000f 3a07
    00001a0: bb00 a259 1907 b700 a3bf bb00 a559 bb00
    00001b0: 4759 b700 4a12 a7b6 0050 2cb6 0050 12a9
    00001c0: b600 50b6 0056 b700 aabf  
  Exception Handler Table:
    bci [0, 6] => handler: 9
    bci [21, 411] => handler: 414
  Stackmap Table:
    same_locals_1_stack_item_frame(@9,Object[#61])
    append_frame(@21,Object[#59])
    same_frame(@36)
    same_frame(@39)
    same_frame(@61)
    same_frame(@76)
    same_frame(@79)
    same_frame(@110)
    same_frame(@125)
    same_frame(@128)
    same_frame(@159)
    same_frame(@174)
    same_frame(@177)
    same_frame(@200)
    same_frame(@215)
    same_frame(@218)
    same_frame(@240)
    same_frame(@255)
    same_frame(@258)
    same_frame(@280)
    same_frame(@295)
    same_frame(@298)
    same_frame(@320)
    same_frame(@335)
    same_frame(@338)
    same_frame(@361)
    same_frame(@376)
    same_frame(@379)
    same_frame(@411)
    same_locals_1_stack_item_frame(@414,Object[#61])
    same_frame(@426)

```
at java.lang.Class.getDeclaredFields0(Native Method) ~[na:1.7.0_55]
at java.lang.Class.privateGetDeclaredFields(Class.java:2397) ~[na:1.7.0_55]
at java.lang.Class.getField0(Class.java:2722) ~[na:1.7.0_55]
at java.lang.Class.getField(Class.java:1577) ~[na:1.7.0_55]
at com.alibaba.dubbo.common.bytecode.Wrapper.makeWrapper(Wrapper.java:348) ~[dubbo-2.5.3.jar:2.5.3]
... 26 common frames omitted
```

**Comment by Xiaobaxi** [comment]
贴一下具体的类吧

**Comment by ralf0131** [comment]
Hi, 

Please try the latest version, if you still encounter this issue, please provide a step by step guide to reproduce this issue.

I am closing it for now.

**Comment by 298** [comment]
您好 我不知道为什么我会收到这封邮件？是我使用了什么APP吗？我也没有在github关注这个帖子。我也收到过类似的邮件，看起来是其他软件崩溃产生的错误报告。 rzx0311 邮箱：rzx0311@gmail.com 签名由 网易邮箱大师 定制 在2018年07月16日 22:35，Huxing Zhang 写道： Closed #221. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by htynkn** [comment]
@298 hey your github user name is 298. some error stack also contains this number. And if it has @ before 298, github will consider this is a notification for you, and send a email to you.
