### ISSUE TITLE
Got an exception when debugging

### ISSUE THREAD

**Issue by shuaijunlan** [apache/incubator-dubbo#2431]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0-SNAPSHOT
* Operating System version: Ubuntu 18.04 LTS
* Java version: 1.8.0_181

### Step to reproduce this issue

1. Making a breakpoint in the 83th line of class `org.apache.dubbo.config.spring.ReferenceBean`
2. Debugging `dubbo-consumer-demo`

### Got an exception

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.dubbo.config.AbstractConfig.toString(AbstractConfig.java:465)
	at org.apache.dubbo.config.spring.ReferenceBean.afterPropertiesSet(ReferenceBean.java:83)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:742)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at cn.shuaijunlan.dubbo.learning.main.Main.main(Main.java:14)
Caused by: java.lang.IllegalStateException: No such application config! Please add <dubbo:application name="..." /> to your spring config.
	at org.apache.dubbo.config.AbstractInterfaceConfig.checkApplication(AbstractInterfaceConfig.java:143)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:280)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:165)
	at org.apache.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:66)
	... 20 more
```

**Comment by diecui1202** [comment]
@shuaijunlan  Make sure `<dubbo:application name="..." />` has been configured.

**Comment by zonghaishang** [comment]
`Intellij Idea -> Prefrencence -> Build -> Debuger -> Data Views -> Java` uncheck  Enable 'toString' object view:

![image](https://user-images.githubusercontent.com/15549777/45010892-4b275880-b042-11e8-99b9-74d8bf38ad37.png)


If you have any questions, feel free to open
