### ISSUE TITLE
master ut not stable

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo#2462]
oracle JDK9, linux

```
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 15.229 sec <<< FAILURE! - in org.apache.dubbo.rpc.protocol.dubbo.telnet.PortTelnetHandlerTest
testListAllPort(org.apache.dubbo.rpc.protocol.dubbo.telnet.PortTelnetHandlerTest)  Time elapsed: 0.012 sec  <<< ERROR!
org.apache.dubbo.rpc.RpcException: Fail to start server(url: dubbo://127.0.0.1:20887/demo?channel.readonly.sent=true&codec=dubbo&heartbeat=60000) Failed to bind NettyServer on /127.0.0.1:20887, cause: Address already in use
	at org.apache.dubbo.rpc.protocol.dubbo.telnet.PortTelnetHandlerTest.before(PortTelnetHandlerTest.java:53)
Caused by: org.apache.dubbo.remoting.RemotingException: Failed to bind NettyServer on /127.0.0.1:20887, cause: Address already in use
	at org.apache.dubbo.rpc.protocol.dubbo.telnet.PortTelnetHandlerTest.before(PortTelnetHandlerTest.java:53)
Caused by: java.net.BindException: Address already in use
```

Tests in error: 
  PortTelnetHandlerTest.before:53 Â» Rpc Fail to start server(url: dubbo://127.0....

**Comment by diecui1202** [comment]
try to use other port.

**Comment by diecui1202** [comment]
change @Before to @BeforeClass.
