### ISSUE TITLE
2.5.3版本。出现No such extension com.alibaba.dubbo.container.Container by name spring

### ISSUE THREAD

**Issue by Chanel-Li** [apache/incubator-dubbo#2478]
`log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.IllegalStateException: No such extension com.alibaba.dubbo.container.Container by name spring
	at com.alibaba.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:507)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:514)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:332)
	at com.alibaba.dubbo.container.Main.main(Main.java:56)`

**Comment by Chanel-Li** [comment]
2.5.3版本

**Comment by carryxyh** [comment]
Hi, @Chanel-Li 
Pls try again with what @lexburner said.
Close this issue. Reopen if it still has some problems.
