### ISSUE TITLE
WebserviceProtocolTest.testDemoProtocol failed

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo#2482]
JDK8

Tests in error: 
  WebserviceProtocolTest.testDemoProtocol:41 Â» Rpc Failed to invoke remote servi...

```
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.476 sec <<< FAILURE! - in org.apache.dubbo.rpc.protocol.webservice.WebserviceProtocolTest
testDemoProtocol(org.apache.dubbo.rpc.protocol.webservice.WebserviceProtocolTest)  Time elapsed: 5.147 sec  <<< ERROR!
org.apache.dubbo.rpc.RpcException: Failed to invoke remote service: interface org.apache.dubbo.rpc.protocol.webservice.DemoService, method: getSize, cause: Could not receive Message.
	at org.apache.dubbo.rpc.protocol.webservice.WebserviceProtocolTest.testDemoProtocol(WebserviceProtocolTest.java:41)
Caused by: org.apache.cxf.interceptor.Fault: Could not receive Message.
	at org.apache.dubbo.rpc.protocol.webservice.WebserviceProtocolTest.testDemoProtocol(WebserviceProtocolTest.java:41)
Caused by: java.net.SocketTimeoutException: SocketTimeoutException invoking http://127.0.0.1:9019/org.apache.dubbo.rpc.protocol.webservice.DemoService: Read timed out
	at org.apache.dubbo.rpc.protocol.webservice.WebserviceProtocolTest.testDemoProtocol(WebserviceProtocolTest.java:41)
Caused by: java.net.SocketTimeoutException: Read timed out
	at org.apache.dubbo.rpc.protocol.webservice.WebserviceProtocolTest.testDemoProtocol(WebserviceProtocolTest.java:41)
```

**Comment by lexburner** [comment]
It works well on my pc. Can you provide more description about how to reproduce this exception? Did it happen during a Travis CI?
@kimmking may know very clearly about `WebserviceProtocol`.

**Comment by diecui1202** [comment]
@lexburner It happens just on travis CI. Very suspicious.

**Comment by diecui1202** [comment]
I try to set timeout longer.
