### ISSUE TITLE
GenericServiceTest.testGenericSerializationJava failed

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo#2490]
JDK8

```
Tests in error: 
  GenericServiceTest.testGenericSerializationJava:159 Â» Rpc Invoke remote method...

Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.634 sec <<< FAILURE! - in org.apache.dubbo.config.GenericServiceTest
testGenericSerializationJava(org.apache.dubbo.config.GenericServiceTest)  Time elapsed: 6.965 sec  <<< ERROR!
org.apache.dubbo.rpc.RpcException: Invoke remote method timeout. method: $invoke, provider: dubbo://127.0.0.1:29581/org.apache.dubbo.config.api.DemoService?application=generic-consumer&dubbo=2.0.2&generic=nativejava&interface=org.apache.dubbo.config.api.DemoService&pid=4653&register.ip=172.17.0.25&scope=remote&side=consumer&timestamp=1536687085410, cause: Sending request timeout in client-side by scan timer. start time: 2018-09-11 17:31:27.527, end time: 2018-09-11 17:31:28.551, elapsed: 1024 ms, timeout: 1000 ms, request: Request [id=0, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=$invoke, parameterTypes=[class java.lang.String, class [Ljava.lang.String;, class [Ljava.lang.Object;], arguments=[sayName, [Ljava.lang.String;@688bd1e4, [Ljava.lang.Object;@e6f4550], attachments={path=org.apache.dubbo.config.api.DemoService, interface=org.apache.dubbo.config.api.DemoService, version=0.0.0, generic=nativejava}]], channel: /172.17.0.25:57036 -> /172.17.0.25:29581
	at org.apache.dubbo.config.GenericServiceTest.testGenericSerializationJava(GenericServiceTest.java:159)
Caused by: org.apache.dubbo.remoting.TimeoutException: Sending request timeout in client-side by scan timer. start time: 2018-09-11 17:31:27.527, end time: 2018-09-11 17:31:28.551, elapsed: 1024 ms, timeout: 1000 ms, request: Request [id=0, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=$invoke, parameterTypes=[class java.lang.String, class [Ljava.lang.String;, class [Ljava.lang.Object;], arguments=[sayName, [Ljava.lang.String;@688bd1e4, [Ljava.lang.Object;@e6f4550], attachments={path=org.apache.dubbo.config.api.DemoService, interface=org.apache.dubbo.config.api.DemoService, version=0.0.0, generic=nativejava}]], channel: /172.17.0.25:57036 -> /172.17.0.25:29581
	at org.apache.dubbo.config.GenericServiceTest.testGenericSerializationJava(GenericServiceTest.java:159)
```
The log is: https://api.travis-ci.org/v3/job/427288378/log.txt

**Comment by diecui1202** [comment]
How about set timeout value to 3000?

**Comment by carryxyh** [comment]
Agree.
There are some instability in our ut (especially on CI machines), it is recommended to adjust the timeout. We only need to ensure that the results are correct.
