### ISSUE TITLE
CacheTest.testCache failed

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo#2492]
JDK8

```
Tests in error: 
  CacheTest.testCache:101->testCache:81 Â» Rpc Invoke remote method timeout. meth...

Tests run: 263, Failures: 0, Errors: 1, Skipped: 2

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.454 sec <<< FAILURE! - in org.apache.dubbo.config.cache.CacheTest
testCache(org.apache.dubbo.config.cache.CacheTest)  Time elapsed: 2.441 sec  <<< ERROR!
org.apache.dubbo.rpc.RpcException: Invoke remote method timeout. method: findCache, provider: dubbo://127.0.0.1:29582/org.apache.dubbo.config.cache.CacheService?application=cache-consumer&cache=true&dubbo=2.0.2&findCache.cache=lru&interface=org.apache.dubbo.config.cache.CacheService&methods=findCache&pid=4807&register.ip=172.17.0.9&scope=remote&side=consumer&timestamp=1536716680587, cause: Waiting server-side response timeout. start time: 2018-09-12 01:44:40.983, end time: 2018-09-12 01:44:42.961, client elapsed: 0 ms, server elapsed: 1978 ms, timeout: 1000 ms, request: Request [id=27, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=findCache, parameterTypes=[class java.lang.String], arguments=[17], attachments={path=org.apache.dubbo.config.cache.CacheService, interface=org.apache.dubbo.config.cache.CacheService, version=0.0.0}]], channel: /172.17.0.9:38182 -> /172.17.0.9:29582
	at org.apache.dubbo.config.cache.CacheTest.testCache(CacheTest.java:81)
	at org.apache.dubbo.config.cache.CacheTest.testCache(CacheTest.java:101)
Caused by: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout. start time: 2018-09-12 01:44:40.983, end time: 2018-09-12 01:44:42.961, client elapsed: 0 ms, server elapsed: 1978 ms, timeout: 1000 ms, request: Request [id=27, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=findCache, parameterTypes=[class java.lang.String], arguments=[17], attachments={path=org.apache.dubbo.config.cache.CacheService, interface=org.apache.dubbo.config.cache.CacheService, version=0.0.0}]], channel: /172.17.0.9:38182 -> /172.17.0.9:29582
	at org.apache.dubbo.config.cache.CacheTest.testCache(CacheTest.java:81)
	at org.apache.dubbo.config.cache.CacheTest.testCache(CacheTest.java:101)
```
The log is: https://api.travis-ci.org/v3/job/427482504/log.txt

**Comment by diecui1202** [comment]
I've check the code, it uses dubbo protocol. Maybe injvm is more suitable ?
