### ISSUE TITLE
dubbo List序列化问题【路过的好汉看下~】

### ISSUE THREAD

**Issue by xryg2276287715** [apache/incubator-dubbo#2493]
接口和接口入参的定义如下：

public interface SimpleProvider {
 boolean cxtest(SimpleDTO dto);
}

`@Data`
public class SimpleDTO implements Serializable {
private static final long serialVersionUID = 3491623810140922257L;
private Long id;
`private List<Byte> levels;`
}

服务协议走的是dubbo://,服务正常注册，消费方也能发现服务。
消费方传入的值如下：
SimpleDTO dto=new SimpleDTO();
dto.setId(12);
List<Byte> byteList=new ArrayList<>();
byteList.add((byte)-1);
byteList.add((byte)5);
dto.setLevels(byteList);
boolean res=simpleProvider.cxtest(dto);

调用时，由于服务端需要取出Levels进行遍历，然后就抛出异常：
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte

调试后发现，服务端收到的levels已经是List<Integer>了.

大家有什么建议么？

**Comment by elmar-chen** [comment]
我试了一下，没有出错。
![image](https://user-images.githubusercontent.com/1620432/45413407-b5c43e00-b6ab-11e8-9b78-8cb43f001812.png)

**Comment by elmar-chen** [comment]
private List levels;
改为：
private List<Byte> levels;

（加上泛型信息）

**Comment by xryg2276287715** [comment]
@elmar-chen @diecui1202 感谢回答，private List<Byte> levels是有的，应该是我粘贴问题时弄丢了。
--------
案例我再贴一次吧
-----
@Data
public class SimpleDTO implements Serializable {
    private static final long serialVersionUID = 3491623810140922257L;
    private Long id;
    private List<Byte> levels;
}
----
public interface SimpleProvider {
    boolean cxtest(SimpleDTO dto);
}
----
@Component
public class SimpleProviderImpl implements SimpleProvider {
    @Override
    public boolean cxtest(SimpleDTO dto) {
        Long id=dto.getId();
        List<Byte> leves=dto.getLevels();
        leves.stream().forEach(l-> System.out.println(l));

        return true;
    }
}
----
消费方（与服务不在同一个应用，消费方和服务都为<dubbo:protocol name="dubbo"）：
  SimpleDTO d=new SimpleDTO();
        d.setId(23L);
        d.setLevels(Arrays.asList((byte)-1,(byte)2));
        boolean res= simpleProvider.cxtest(d);
        System.out.println(res);
----
异常信息：
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) ~[?:1.8.0_151]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_151]
	at com.cx.provider.SimpleProviderImpl.cxtest(SimpleProviderImpl.java:15) ~[classes/:?]
	at com.alibaba.dubbo.common.bytecode.Wrapper9.invokeMethod(Wrapper9.java) ~[?:2.5.3]
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) ~[dubbo-2.5.3.jar:2.5.3]
	at com.cx.dubbo.filter.ResponseFilter.invoke(ResponseFilter.java:69) ~[cx-client-1.4.0-20180802.074711-8.jar:?]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.cx.dubbo.filter.AsyncTransmitFilter.invoke(AsyncTransmitFilter.java:25) ~[cx-client-1.4.0-20180802.074711-8.jar:?]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:65) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.filter.AccessLogFilter.invoke(AccessLogFilter.java:199) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:60) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:84) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:170) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52) ~[dubbo-2.5.3.jar:2.5.3]
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82) ~[dubbo-2.5.3.jar:2.5.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by elmar-chen** [comment]
I'm using dubbo 2.5.10 and it has no error with your code. Maybe you really need to create a demo project to demonstrate the issue.

**Comment by agmtopy** [comment]
老铁 @DaTa  是啥东西？

**Comment by xryg2276287715** [comment]
@agmtopy github的编辑器下Data自己转成了DaTa。lombok注解。 @elmar-chen 我用的是dubbo2.5.3，为了方便就直接放现有项目里面写了demo，这两天会单独创建项目试试。届时附上链接~

**Comment by elmar-chen** [comment]
@xryg2276287715 - debug了一下，这是Hessian早期版本对List<Byte/Short>的bug。dubbo 2.5.3使用到了早期的hessian版本，所以连带出错了。(但是Dubbo对Hessian进行了repackage，而不是引用jar包的形式，所以我不知道2.5.3的dubbo具体用了哪个版本的Hessian)

具体有差异的Hessian代码为：
2.5.3版内置Hessian:
`com.alibaba.com.caucho.hessian.io.Hessian2Input`
![image](https://user-images.githubusercontent.com/1620432/45464360-ddb2b080-b742-11e8-914d-36c047339ec8.png)
`com.alibaba.com.caucho.hessian.io.JavaDeserializer`
![image](https://user-images.githubusercontent.com/1620432/45464383-f15e1700-b742-11e8-95ef-9891d76d8ba9.png)

2.5.10版内置Hessian:
com.alibaba.com.caucho.hessian.io.JavaDeserializer
![image](https://user-images.githubusercontent.com/1620432/45464460-3a15d000-b743-11e8-8928-393e9d93a201.png)

com.alibaba.com.caucho.hessian.io.CollectionDeserializer
![image](https://user-images.githubusercontent.com/1620432/45464501-76493080-b743-11e8-9125-59d5eccbd375.png)

可以看到，2.5.3版的直接丢掉了泛型信息，这个Bug在2.5.10里面已经修复。

**Comment by xryg2276287715** [comment]
@elmar-chen 感谢~ 我抽空试下~

**Comment by elmar-chen** [comment]
@lovepoem would you guys mind to include a package-info.java in the hessian-lite project and state which release of hessian is repackaged? That would be helpful for debugging.

**Comment by beiwei30** [comment]
this is a hessian 2 which has many customization added from time to time.

```xml
<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>hessian-lite</artifactId>
    <version>3.2.4</version>
 <dependency>
```

I guess package.java is unnecessary, since we have version specified in its MANIFEST.MF:

```
Manifest-Version: 1.0
Implementation-Vendor: The Apache Software Foundation
Implementation-Title: Hessian Lite(Alibaba embed version)
Implementation-Version: 3.2.3
Implementation-Vendor-Id: com.alibaba
Built-By: ken.lj
Build-Jdk: 1.7.0_80
Specification-Vendor: The Apache Software Foundation
Specification-Title: Hessian Lite(Alibaba embed version)
Created-By: Apache Maven 3.5.0
Implementation-URL: https://github.com/apache/incubator-dubbo/hessian-
 lite
Specification-Version: 3.2
```

**Comment by elmar-chen** [comment]
@beiwei30  - you mean hessian-lite 3.2.4 is based on hessian 3.2.3?
