### ISSUE TITLE
Dubbo 2.6.2版本非spring项目上调用rmi协议提供的服务出错，而调用dubbo默认协议提供的服务正常

### ISSUE THREAD

**Issue by zlclovetb** [apache/incubator-dubbo#2504]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. spring项目用rmi协议启动服务
2. spring项目的客户端调用该服务正常
3. 非spring项目的客户端调用该服务出错
4. 重复第1步用dubbo默认协议启动服务
5. 重复3调用正常

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

调用正常返回结果

### Actual Result

调用失败

If there is an exception, please attach the exception trace:

```
2018-09-14 09:40:27,515 INFO  org.apache.struts.tiles.TilesRequestProcessor - Get Connection Succeed
2018-09-14 09:40:27,546 INFO  com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry -  [DUBBO] Register: consumer://192.168.20.30/com.paradm.docview.remote.core.IDocviewRemoteService?application=paradm-dubbo-consumer&category=consumers&check=false&dubbo=2.6.2&interface=com.paradm.docview.remote.core.IDocviewRemoteService&methods=deleteDmsAnnotation,deleteAnnotationComment,deleteDmsAnnotationDigitalSignature,createDvTaskWithThumb,createAnnotationComment,updateAnnotationComment,createDmsAnnotation,updateDmsAnnotation,raiseTaskPriority,createTask,getTask,createDmsAnnotationDigitalSignature,getDmsAnnotationList,downloadImage&pid=13852&revision=3.0.1&side=consumer&timestamp=1536889227525, dubbo version: 2.6.2, current host: 192.168.20.30
2018-09-14 09:40:27,583 INFO  com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry -  [DUBBO] Subscribe: consumer://192.168.20.30/com.paradm.docview.remote.core.IDocviewRemoteService?application=paradm-dubbo-consumer&category=providers,configurators,routers&check=false&dubbo=2.6.2&interface=com.paradm.docview.remote.core.IDocviewRemoteService&methods=deleteDmsAnnotation,deleteAnnotationComment,deleteDmsAnnotationDigitalSignature,createDvTaskWithThumb,createAnnotationComment,updateAnnotationComment,createDmsAnnotation,updateDmsAnnotation,raiseTaskPriority,createTask,getTask,createDmsAnnotationDigitalSignature,getDmsAnnotationList,downloadImage&pid=13852&revision=3.0.1&side=consumer&timestamp=1536889227525, dubbo version: 2.6.2, current host: 192.168.20.30
2018-09-14 09:40:27,676 INFO  com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry -  [DUBBO] Notify urls for subscribe url consumer://192.168.20.30/com.paradm.docview.remote.core.IDocviewRemoteService?application=paradm-dubbo-consumer&category=providers,configurators,routers&check=false&dubbo=2.6.2&interface=com.paradm.docview.remote.core.IDocviewRemoteService&methods=deleteDmsAnnotation,deleteAnnotationComment,deleteDmsAnnotationDigitalSignature,createDvTaskWithThumb,createAnnotationComment,updateAnnotationComment,createDmsAnnotation,updateDmsAnnotation,raiseTaskPriority,createTask,getTask,createDmsAnnotationDigitalSignature,getDmsAnnotationList,downloadImage&pid=13852&revision=3.0.1&side=consumer&timestamp=1536889227525, urls: [rmi://192.168.20.55:20889/com.paradm.docview.remote.core.IDocviewRemoteService?anyhost=true&application=dubbo&dubbo=2.6.2&generic=false&interface=com.paradm.docview.remote.core.IDocviewRemoteService&methods=deleteDmsAnnotation,deleteAnnotationComment,createDvTaskWithThumb,deleteDmsAnnotationDigitalSignature,createAnnotationComment,updateAnnotationComment,createTask,createDmsAnnotation,updateDmsAnnotation,raiseTaskPriority,getTask,downloadImage,getDmsAnnotationList,createDmsAnnotationDigitalSignature&pid=2572&revision=3.0.1&side=provider&timestamp=1536821513478, empty://192.168.20.30/com.paradm.docview.remote.core.IDocviewRemoteService?application=paradm-dubbo-consumer&category=configurators&check=false&dubbo=2.6.2&interface=com.paradm.docview.remote.core.IDocviewRemoteService&methods=deleteDmsAnnotation,deleteAnnotationComment,deleteDmsAnnotationDigitalSignature,createDvTaskWithThumb,createAnnotationComment,updateAnnotationComment,createDmsAnnotation,updateDmsAnnotation,raiseTaskPriority,createTask,getTask,createDmsAnnotationDigitalSignature,getDmsAnnotationList,downloadImage&pid=13852&revision=3.0.1&side=consumer&timestamp=1536889227525, empty://192.168.20.30/com.paradm.docview.remote.core.IDocviewRemoteService?application=paradm-dubbo-consumer&category=routers&check=false&dubbo=2.6.2&interface=com.paradm.docview.remote.core.IDocviewRemoteService&methods=deleteDmsAnnotation,deleteAnnotationComment,deleteDmsAnnotationDigitalSignature,createDvTaskWithThumb,createAnnotationComment,updateAnnotationComment,createDmsAnnotation,updateDmsAnnotation,raiseTaskPriority,createTask,getTask,createDmsAnnotationDigitalSignature,getDmsAnnotationList,downloadImage&pid=13852&revision=3.0.1&side=consumer&timestamp=1536889227525], dubbo version: 2.6.2, current host: 192.168.20.30
2018-09-14 09:40:27,677 ERROR com.alibaba.dubbo.registry.integration.RegistryDirectory - Unsupported protocol rmi in notified url: rmi://192.168.20.55:20889/com.paradm.docview.remote.core.IDocviewRemoteService?anyhost=true&application=dubbo&dubbo=2.6.2&generic=false&interface=com.paradm.docview.remote.core.IDocviewRemoteService&methods=deleteDmsAnnotation,deleteAnnotationComment,createDvTaskWithThumb,deleteDmsAnnotationDigitalSignature,createAnnotationComment,updateAnnotationComment,createTask,createDmsAnnotation,updateDmsAnnotation,raiseTaskPriority,getTask,downloadImage,getDmsAnnotationList,createDmsAnnotationDigitalSignature&pid=2572&revision=3.0.1&side=provider&timestamp=1536821513478 from registry 192.168.23.55:2181 to consumer 192.168.20.30, supported protocol: [dubbo, injvm, mock, redis, registry, thrift]
java.lang.IllegalStateException: Unsupported protocol rmi in notified url: rmi://192.168.20.55:20889/com.paradm.docview.remote.core.IDocviewRemoteService?anyhost=true&application=dubbo&dubbo=2.6.2&generic=false&interface=com.paradm.docview.remote.core.IDocviewRemoteService&methods=deleteDmsAnnotation,deleteAnnotationComment,createDvTaskWithThumb,deleteDmsAnnotationDigitalSignature,createAnnotationComment,updateAnnotationComment,createTask,createDmsAnnotation,updateDmsAnnotation,raiseTaskPriority,getTask,downloadImage,getDmsAnnotationList,createDmsAnnotationDigitalSignature&pid=2572&revision=3.0.1&side=provider&timestamp=1536821513478 from registry 192.168.23.55:2181 to consumer 192.168.20.30, supported protocol: [dubbo, injvm, mock, redis, registry, thrift]
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:364)
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:253)
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:223)
	at com.alibaba.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:414)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:274)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:260)
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:190)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:190)
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:159)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:305)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:286)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:106)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:65)
	at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:63)
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:394)
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:333)
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:163)
	at com.alibaba.dubbo.config.utils.ReferenceConfigCache.get(ReferenceConfigCache.java:115)
	at com.dcivision.workspace.common.RemoteServiceConfig.getBean(RemoteServiceConfig.java:168)
	at com.dcivision.workspace.common.RemoteServiceManager.getDvRemoteService(RemoteServiceManager.java:68)
	at com.dcivision.workspace.web.DocumentViewerAction.init(DocumentViewerAction.java:79)
	at com.dcivision.framework.web.AbstractMaintAction.execute(AbstractMaintAction.java:199)
	at com.dcivision.workspace.web.DocumentViewerAction.execute(DocumentViewerAction.java:69)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
	at com.dcivision.framework.MainRequestProcessor.processActionPerform(MainRequestProcessor.java:329)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
	at com.dcivision.framework.MainRequestProcessor.process(MainRequestProcessor.java:273)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1495)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:520)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dcivision.framework.web.LoginFilter.doFilter(LoginFilter.java:180)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
2018-09-14 09:40:27,677 ERROR com.alibaba.dubbo.registry.integration.RegistryDirectory - urls to invokers error .invokerUrls.size :1, invoker.size :0. urls :[rmi://192.168.20.55:20889/com.paradm.docview.remote.core.IDocviewRemoteService?anyhost=true&application=dubbo&dubbo=2.6.2&generic=false&interface=com.paradm.docview.remote.core.IDocviewRemoteService&methods=deleteDmsAnnotation,deleteAnnotationComment,createDvTaskWithThumb,deleteDmsAnnotationDigitalSignature,createAnnotationComment,updateAnnotationComment,createTask,createDmsAnnotation,updateDmsAnnotation,raiseTaskPriority,getTask,downloadImage,getDmsAnnotationList,createDmsAnnotationDigitalSignature&pid=2572&revision=3.0.1&side=provider&timestamp=1536821513478]
java.lang.IllegalStateException: urls to invokers error .invokerUrls.size :1, invoker.size :0. urls :[rmi://192.168.20.55:20889/com.paradm.docview.remote.core.IDocviewRemoteService?anyhost=true&application=dubbo&dubbo=2.6.2&generic=false&interface=com.paradm.docview.remote.core.IDocviewRemoteService&methods=deleteDmsAnnotation,deleteAnnotationComment,createDvTaskWithThumb,deleteDmsAnnotationDigitalSignature,createAnnotationComment,updateAnnotationComment,createTask,createDmsAnnotation,updateDmsAnnotation,raiseTaskPriority,getTask,downloadImage,getDmsAnnotationList,createDmsAnnotationDigitalSignature&pid=2572&revision=3.0.1&side=provider&timestamp=1536821513478]
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:258)
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:223)
	at com.alibaba.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:414)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:274)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:260)
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(ZookeeperRegistry.java:190)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:190)
	at com.alibaba.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:159)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:305)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:286)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:106)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:65)
	at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:63)
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:394)
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:333)
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:163)
	at com.alibaba.dubbo.config.utils.ReferenceConfigCache.get(ReferenceConfigCache.java:115)
	at com.dcivision.workspace.common.RemoteServiceConfig.getBean(RemoteServiceConfig.java:168)
	at com.dcivision.workspace.common.RemoteServiceManager.getDvRemoteService(RemoteServiceManager.java:68)
	at com.dcivision.workspace.web.DocumentViewerAction.init(DocumentViewerAction.java:79)
	at com.dcivision.framework.web.AbstractMaintAction.execute(AbstractMaintAction.java:199)
	at com.dcivision.workspace.web.DocumentViewerAction.execute(DocumentViewerAction.java:69)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
	at com.dcivision.framework.MainRequestProcessor.processActionPerform(MainRequestProcessor.java:329)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
	at com.dcivision.framework.MainRequestProcessor.process(MainRequestProcessor.java:273)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1495)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:520)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dcivision.framework.web.LoginFilter.doFilter(LoginFilter.java:180)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
2018-09-14 09:40:27,678 INFO  com.alibaba.dubbo.config.AbstractConfig -  [DUBBO] Refer dubbo service com.paradm.docview.remote.core.IDocviewRemoteService from url zookeeper://192.168.23.55:2181/com.alibaba.dubbo.registry.RegistryService?application=paradm-dubbo-consumer&check=false&dubbo=2.6.2&interface=com.paradm.docview.remote.core.IDocviewRemoteService&methods=deleteDmsAnnotation,deleteAnnotationComment,deleteDmsAnnotationDigitalSignature,createDvTaskWithThumb,createAnnotationComment,updateAnnotationComment,createDmsAnnotation,updateDmsAnnotation,raiseTaskPriority,createTask,getTask,createDmsAnnotationDigitalSignature,getDmsAnnotationList,downloadImage&pid=13852&register.ip=192.168.20.30&revision=3.0.1&side=consumer&timestamp=1536889227525, dubbo version: 2.6.2, current host: 192.168.20.30
2018-09-14 09:40:27,707 DEBUG com.alibaba.dubbo.remoting.transport.DecodeHandler -  [DUBBO] Decode decodeable message com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult, dubbo version: 2.6.2, current host: 192.168.20.30
2018-09-14 09:40:27,747 DEBUG com.alibaba.dubbo.remoting.transport.DecodeHandler -  [DUBBO] Decode decodeable message com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcResult, dubbo version: 2.6.2, current host: 192.168.20.30
2018-09-14 09:40:27,748 ERROR com.dcivision.workspace.core.WspDocumentManager - Failed to invoke the method getTask in the service com.paradm.docview.remote.core.IDocviewRemoteService. No provider available for the service com.paradm.docview.remote.core.IDocviewRemoteService from registry 192.168.23.55:2181 on the consumer 192.168.20.30 using the dubbo version 2.6.2. Please check if the providers have been started and registered.
com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method getTask in the service com.paradm.docview.remote.core.IDocviewRemoteService. No provider available for the service com.paradm.docview.remote.core.IDocviewRemoteService from registry 192.168.23.55:2181 on the consumer 192.168.20.30 using the dubbo version 2.6.2. Please check if the providers have been started and registered.
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:257)
	at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:56)
	at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:238)
	at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:75)
	at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
	at com.alibaba.dubbo.common.bytecode.proxy1.getTask(proxy1.java)
	at com.dcivision.workspace.core.WspDocumentManager.getDocviewTaskRemoteBean(WspDocumentManager.java:1213)
	at com.dcivision.workspace.web.DocumentViewerAction.init(DocumentViewerAction.java:84)
	at com.dcivision.framework.web.AbstractMaintAction.execute(AbstractMaintAction.java:199)
	at com.dcivision.workspace.web.DocumentViewerAction.execute(DocumentViewerAction.java:69)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:484)
	at com.dcivision.framework.MainRequestProcessor.processActionPerform(MainRequestProcessor.java:329)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:274)
	at com.dcivision.framework.MainRequestProcessor.process(MainRequestProcessor.java:273)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1495)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:520)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.dcivision.framework.web.LoginFilter.doFilter(LoginFilter.java:180)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cvictory** [comment]
Maybe your project lacks some dependency, pls check your dependency:   
```
         <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-rpc-rmi</artifactId>
        </dependency>
```

If it is no probelow, pls upload a demo for us to check what happened.

**Comment by zlclovetb** [comment]
> Maybe your project lacks some dependency, pls check your dependency:
> 
> ```
>          <dependency>
>             <groupId>org.apache.dubbo</groupId>
>             <artifactId>dubbo-rpc-rmi</artifactId>
>         </dependency>
> ```
> If it is no probelow, pls upload a demo for us to check what happened.

dubbo-rpc-rmi这个已经引入，我们是从dubbox上转过来的，之前是正常的。转到dubbo2.6.2就不行了

**Comment by zlclovetb** [comment]
> As your log said, the project support protocol:
> 
> ```
> supported protocol: [dubbo, injvm, mock, redis, registry, thrift]
> ```

？你意思是不支持

**Comment by cvictory** [comment]
You can debug this class ：  
 
org.apache.dubbo.common.extension.ExtensionLoader#loadExtensionClasses

**Comment by zlclovetb** [comment]
> You can debug this class ：
> 
> org.apache.dubbo.common.extension.ExtensionLoader#loadExtensionClasses

很容易测试出来，随便写一个main方法就重现了，经我测试发现，dubbo2.6.2要引入spring-context才能使用rmi协议。也就是说现在的dubbo一定要使用spring了吗？

**Comment by chengxj** [comment]
我的dubbo-2.6.7也出现了类似的情况
com.alibaba.dubbo.registry.integration.RegistryDirectory: Unsupported protocol http in notified url
