### ISSUE TITLE
java 10 master ut failed

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo#2543]
```
testListService(org.apache.dubbo.rpc.protocol.dubbo.telnet.ListTelnetHandlerTest)  Time elapsed: 0.026 sec  <<< ERROR!
org.apache.dubbo.rpc.RpcException: Fail to start server(url: dubbo://127.0.0.1:20885/demo?channel.readonly.sent=true&codec=dubbo&heartbeat=60000) Failed to bind NettyServer on /127.0.0.1:20885, cause: Address already in use
	at org.apache.dubbo.rpc.protocol.dubbo.telnet.ListTelnetHandlerTest.testListService(ListTelnetHandlerTest.java:105)
Caused by: org.apache.dubbo.remoting.RemotingException: Failed to bind NettyServer on /127.0.0.1:20885, cause: Address already in use
	at org.apache.dubbo.rpc.protocol.dubbo.telnet.ListTelnetHandlerTest.testListService(ListTelnetHandlerTest.java:105)
Caused by: java.net.BindException: Address already in use
```

https://api.travis-ci.org/v3/job/431310736/log.txt

**Comment by diecui1202** [comment]
same to #2532
