### ISSUE TITLE
java.lang.NoClassDefFoundError: com/alibaba/dubbo/remoting/exchange/Request

### ISSUE THREAD

**Issue by epubreader** [apache/incubator-dubbo#2555]
服务器一直报这个错， 但功能却是正常的， 不知道怎么解决

2018-09-25 16:58:03,544 WARN [com.alibaba.dubbo.remoting.exchange.support.header.HeartBeatTask] - < [DUBBO] Exception when heartbeat to remote channel /172.17.0.2:20888, dubbo version: 2.6.1, current host: 172.17.0.6>
java.lang.NoClassDefFoundError: com/alibaba/dubbo/remoting/exchange/Request
	at com.alibaba.dubbo.remoting.exchange.support.header.HeartBeatTask.run(HeartBeatTask.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Environment

* Dubbo version: 2.6.1
* Operating System version: ubuntu
* Java version: 1.8

**Comment by diecui1202** [comment]
I've check 2.6.1, the class com/alibaba/dubbo/remoting/exchange/Request is exist. Pls. check your server status, maybe it has been stopped, the classloader is also stopped.

Restart u app and check the problem again, or upgrade to 2.6.3?

**Comment by epubreader** [comment]
I have upgrade to 2.6.2, still found  NoClassDefFoundError: org/apache/zookeeper/proto/SetWatches

user-service_1     | 2018-09-25 18:02:17,915 DEBUG [org.apache.zookeeper.ClientCnxn] - <Got ping response for sessionid: 0x1660f14cd920023 after 0ms>
mgr_1              | 2018-09-25 18:02:17,966 DEBUG [org.apache.zookeeper.ClientCnxn] - <Got ping response for sessionid: 0x165c28790900315 after 0ms>
user-service_1     | 2018-09-25 18:02:18,241 INFO [org.apache.zookeeper.ClientCnxn] - <Opening socket connection to server 192.168.50.31/192.168.50.31:2181. Will not attempt to authenticate using SASL (unknown error)>
user-service_1     | 2018-09-25 18:02:18,242 INFO [org.apache.zookeeper.ClientCnxn] - <Socket connection established to 192.168.50.31/192.168.50.31:2181, initiating session>
user-service_1     | 2018-09-25 18:02:18,242 WARN [org.apache.zookeeper.ClientCnxn] - <Session 0x1660f14cd920028 for server 192.168.50.31/192.168.50.31:2181, unexpected error, closing socket connection and attempting reconnect>
user-service_1     | java.lang.NoClassDefFoundError: org/apache/zookeeper/proto/SetWatches
user-service_1     | 	at org.apache.zookeeper.ClientCnxn$SendThread.primeConnection(ClientCnxn.java:926)
user-service_1     | 	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:363)
user-service_1     | 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)

**Comment by zonghaishang** [comment]
`mvn dependency:tree > tree.log` , upload your tree.log

**Comment by epubreader** [comment]
it is tomcat issue, it restart twice
