### ISSUE TITLE
AbstractInterfaceConfigTest failed 

### ISSUE THREAD

**Issue by Jeff-Lv** [apache/incubator-dubbo#2637]
### Environment

* Dubbo version: 2.6.3
* Operating System version: window 7
* Java version: 1.8

### Steps to reproduce this issue

1. run test case of abstractInterfaceConfigTest

Pls. provide [GitHub address] to reproduce this issue.

### paased

What do you expected from the above steps？

### Failed

What actually happens?

```
[11/10/18 04:17:11:011 CST] main  INFO logger.LoggerFactory: using logger: com.alibaba.dubbo.common.logger.log4j.Log4jLoggerAdapter
[11/10/18 04:17:11:011 CST] main  INFO config.AbstractConfig:  [DUBBO] Use System Property dubbo.application.name to config dubbo, dubbo version: , current host: 192.168.81.1

junit.framework.ComparisonFailure: 
Expected :100
Actual   :null
 <Click to see difference>


	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at com.alibaba.dubbo.config.AbstractInterfaceConfigTest.checkApplication1(AbstractInterfaceConfigTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

**Comment by carryxyh** [comment]
Passed in my mac.

**Comment by Jeff-Lv** [comment]
> Passed in my mac.

![d9350a3f-eafe-4282-8e1f-40400b65e566](https://user-images.githubusercontent.com/6000915/46793794-1614d100-cd79-11e8-86e5-83dc864b8e48.png)

:) As the code, it will be loaded from os filesystem if filename is started with '/'. It will be invalid in windows.

**Comment by carryxyh** [comment]
Oh, I remember there is a pr to fix this issue.
Let me check.

**Comment by chickenlj** [comment]
@carryxyh If it's not easy to reach him, I think you can do it directly.

**Comment by Jeff-Lv** [comment]
@carryxyh cool.

**Comment by carryxyh** [comment]
> @carryxyh If it's not easy to reach him, I think you can do it directly.

No problem. fix it soon.

**Comment by chickenlj** [comment]
https://github.com/Jeff-Lv/incubator-dubbo/commit/7cd86a1d0cdc4101a3d1c66e92a1b321ed6ac739
@carryxyh I think the change made by Jeff-Lv is more reasonable.

**Comment by carryxyh** [comment]
@chickenlj 

I agree with this modification. Compared to our judgment of the environment information in the code, I agree more that the user should set different dubbo.properties.file according to the current environment. All we have to do is determine if the input dubbo.properties.file exists.

@Jeff-Lv 
We can reach a consensus on this issue, please submit a pr to optimize it.

**Comment by Jeff-Lv** [comment]
please check this PR https://github.com/apache/incubator-dubbo/pull/2607

时无两丶 <notifications@github.com> 于2018年10月11日周四 下午5:51写道：

**Comment by carryxyh** [comment]
Hi, @Jeff-Lv 
I have seen this pr.
I think there is no problem with modifying the part of this issue. But there are other parts of your pr, I am not very familiar, and may need someone to review.

Maybe he can help u : @chickenlj .
:)

**Comment by carryxyh** [comment]
Close via https://github.com/apache/incubator-dubbo/issues/2637
