### ISSUE TITLE
Dubbo made a mistake with redis as a registry center

### ISSUE THREAD

**Issue by PulauBusing** [apache/incubator-dubbo#2731]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

Dubbo USES redis as the registry times error below:

Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.RegistryFactory by name dubbo
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:499)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:506)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:325)
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:204)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:138)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:55)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:98)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:512)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:357)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:316)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:215)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at org.apache.dubbo.demo.provider.Provider.main(Provider.java:29)
[02/11/18 06:53:02:002 CST] main  WARN extension.ExtensionLoader:  [DUBBO] Failed to find extension named redis for type org.apache.dubbo.registry.RegistryFactory, will use default extension dubbo instead., dubbo version: , current host: 192.168.0.142
java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.RegistryFactory by name redis
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:499)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:506)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:325)
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:204)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:138)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:55)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:98)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:512)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:357)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:316)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:215)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:114)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:49)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at org.apache.dubbo.demo.provider.Provider.main(Provider.java:29)

I don't understand the core reason for this error. So I can't find the reason,and  I hope to get the answer . Thanks.

**Comment by carryxyh** [comment]
@PulauBusing 
你好，这个问题修复了么？

**Comment by PulauBusing** [comment]
> @PulauBusing
> 你好，这个问题修复了么？

@carryxyh 您好，果然是因为少了依赖，现在可以了，谢谢你啊
