### ISSUE TITLE
使用Main.main(args)方法运行demo报找不到spring容器

### ISSUE THREAD

**Issue by yupd** [apache/incubator-dubbo#2736]
### Environment

* Dubbo version: 2.6.4
* Operating System version: win7
* Java version: 1.8

### Steps to reproduce this issue

1. 修改com.alibaba.dubbo.demo.provider.Provider
```
    public static void main(String[] args) throws Exception {
        System.setProperty("java.net.preferIPv4Stack", "true");

//        ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext(new String[]{"META-INF/spring/dubbo-demo-provider.xml"});
//        context.start();
//        System.in.read(); // press any key to exit

        com.alibaba.dubbo.container.Main.main(args);

    }
```

### Actual Result

exception trace:

```
java.lang.IllegalStateException: No such extension com.alibaba.dubbo.container.Container by name spring
	at com.alibaba.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:482)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:489)
	at com.alibaba.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:309)
	at com.alibaba.dubbo.container.Main.main(Main.java:59)
	at com.alibaba.dubbo.demo.provider.Provider.main(Provider.java:29)
```

**Comment by carryxyh** [comment]
添加一个dubbo-container-spring依赖试试。

**Comment by yupd** [comment]
> 添加一个dubbo-container-spring依赖试试。

可以了，谢谢！
