### ISSUE TITLE
dubbo序列化问题【紧急，求回复 】

### ISSUE THREAD

**Issue by kingyoungfan** [apache/incubator-dubbo#277]
```
2016-06-30 18:52:20,673 WARN : log.warn: 50 - /temp/user
com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method findByMobile in the service com.ixiye.ucenter.UserService. Tried 3 times of the providers [192.168.3.106:20881] (1/1) from the registry 114.55.84.38:2181 on the consumer 192.168.3.106 using the dubbo version 2.5.3. Last error is: Failed to invoke remote method: findByMobile, provider: dubbo://192.168.3.106:20881/com.ixiye.ucenter.UserService?anyhost=true&application=posp&check=false&dubbo=2.8.4&generic=false&interface=com.ixiye.ucenter.UserService&loadbalance=roundrobin&methods=updateProfile,deleteProfile,save,update,updateUser,delete,saveProfile,findById,deleteUser,findByMobileAndPassword,findByMobile,saveUser&organization=ixiye&owner=yangyang&pid=23961&revision=1.0.0-SNAPSHOT&side=consumer&timestamp=1467283925787, cause: Fail to decode request due to: RpcInvocation [methodName=findByMobile, parameterTypes=null, arguments=null, attachments={path=com.ixiye.ucenter.UserService, input=193, dubbo=2.5.3, version=0.0.0}]
    at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:101)
    at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227)
    at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72)
    at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
    at com.alibaba.dubbo.common.bytecode.proxy0.findByMobile(proxy0.java)
    at com.ixiye.fula.service.impl.LoginServiceImpl.findByMobile(LoginServiceImpl.java:131)
    at com.ixiye.fula.posp.springmvc.TempApi.temp(TempApi.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
    at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:426)
    at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:414)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:549)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:527)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1216)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1187)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:421)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:493)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:930)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:358)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:866)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:113)
    at org.eclipse.jetty.server.Server.handle(Server.java:351)
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:594)
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1042)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:549)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:211)
    at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:424)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:506)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.dubbo.remoting.RemotingException: Fail to decode request due to: RpcInvocation [methodName=findByMobile, parameterTypes=null, arguments=null, attachments={path=com.ixiye.ucenter.UserService, input=193, dubbo=2.5.3, version=0.0.0}]
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:190)
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:110)
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)
    at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:96)
    at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
    at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
    at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
    at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
    ... 43 more
```

**Comment by kingyoungfan** [comment]
没人遇到过吗

**Comment by zondahuman** [comment]
方法什么都不往出来贴，不好分析吧，最好贴出来方法定义，还有dubbo默认序列化协议是hession，hession对于特殊对象，序列化不行这是他的一大劣势，解决办法：
1、自己转化下思路，比如转化为string类型的
2、不用hession协议，直接使用protobuf协议做序列化协议

**Comment by yangzhiw** [comment]
同遇到这个问题，请问怎么解决的啊，急

**Comment by justein** [comment]
@zondahuman 的方法试一下，建议换其他序列化方式

**Comment by ludvik** [comment]
看起来你用的是dubbo自己的序列化协议，decode的时候出错了。出这个问题的可能性很多，你可以换序列化协议试试，也可以把阐述里面的内容换换看，看下是哪里的问题。

**Comment by kingyoungfan** [comment]
@yangzhiw model实现Serializable接口。

**Comment by ralf0131** [comment]
I am closing this issue. Please provide more details if you still encounter it.

**Comment by wuxianglin** [comment]
also encounter this problem
i use dubbo2.5.9, serialization is fst(has compared with the latest version of dubbo, the same)
provider throw following exception:
"Decode rpc invocation failed: java.lang.String cannot be cast to java.util.Map"

I have check the source code
`public Object decode(Channel channel, InputStream input) throws IOException {
        ObjectInput in = CodecSupport.getSerialization(channel.getUrl(), serializationType)
                .deserialize(channel.getUrl(), input);

        setAttachment(Constants.DUBBO_VERSION_KEY, in.readUTF());
        setAttachment(Constants.PATH_KEY, in.readUTF());
        setAttachment(Constants.VERSION_KEY, in.readUTF());

        setMethodName(in.readUTF());
        try {
            Object[] args;
            Class<?>[] pts;
            String desc = in.readUTF();
            if (desc.length() == 0) {
                pts = DubboCodec.EMPTY_CLASS_ARRAY;
                args = DubboCodec.EMPTY_OBJECT_ARRAY;
            } else {
                pts = ReflectUtils.desc2classArray(desc);
                args = new Object[pts.length];
                for (int i = 0; i < args.length; i++) {
                    try {
                        args[i] = in.readObject(pts[i]);
                    } catch (Exception e) {
                        if (log.isWarnEnabled()) {
                            log.warn("Decode argument failed: " + e.getMessage(), e);
                        }
                    }
                }
            }
            setParameterTypes(pts);

            Map<String, String> map = (Map<String, String>) in.readObject(Map.class);**-------------this line throw exception**
            if (map != null && map.size() > 0) {
                Map<String, String> attachment = getAttachments();
                if (attachment == null) {
                    attachment = new HashMap<String, String>();
                }
                attachment.putAll(map);
                setAttachments(attachment);
            }
            //decode argument ,may be callback
            for (int i = 0; i < args.length; i++) {
                args[i] = decodeInvocationArgument(channel, this, pts, i, args[i]);
            }

            setArguments(args);

        } catch (ClassNotFoundException e) {
            throw new IOException(StringUtils.toString("Read invocation data failed.", e));
        }
        return this;
    }`


the line which deserializa attachment encounter error

**Comment by web1992** [comment]
@wuxianglin  maybe your `consumer` dubbo version is different with `provider` dubbo version

**Comment by wuxianglin** [comment]
hi,
     I am sure about that consumer dubbo version is the same as provider dubbo version
     Do you need other information?and this problem occured in certain percent. 
      It do consumed me for a long time.


      you can contact me by my dingding phone number: 13811340858
      appreciate concacting with you and talking about this problem.
     
      






At 2019-03-17 22:27:52, "web" <notifications@github.com> wrote:


@wuxianglin maybe your consumer dubbo version is different with provider dubbo version

**Comment by wuxianglin** [comment]
@web1992 ,I am sure that consumer dubbo version is the same with provider dubbo version
