### ISSUE TITLE
Dubbo线程池满JStack日志中出现很多ValidationFilter的ClassLoader.loadClass线程BLOCK

### ISSUE THREAD

**Issue by cdfive** [apache/incubator-dubbo#2770]
### 环境
* Dubbo version: 2.6.0
* Operating System version: Linux version 4.17.3-1.el7.elrepo.x86_64
* Java version: jdk1.8.0_45

dubbo应用配置：
<dubbo:protocol name="dubbo" port="xxx"  dispatcher="all" threadpool="fixed" threads="500"/>
应用部署了5个节点

provider端配置：
<dubbo:service interface="xxx" ref="xxxService" timeout="x'x'x" retries="0" validation="true" />
其中，配置了validation="true"，在方法的请求参数中配合@NotNull(message = "id不能为空")使用；
该应用创建时间较早，目前新的应用已没有使用这种方式验证参数；

### 描述
线上某dubbo应用日志里最近出现了很多线程池满的情况，查看用户目录dubbo自动dump的Dubbo_JStack.log日志，有很多BLOCKED的线程堆栈信息打印了ClassLoader.loadClass
JValidator.validate(JValidator.java:241)；

命令：
grep "JValidator.validate(JValidator.java:241)" Dubbo_JStack.log.2018-11-10_11\:31\:36 | wc -l
不同日志文件，有5-200左右；
同时jstack日志里也有很多业务代码读写数据以及codis缓存等占用线程，用grep查询200-300左右；

依赖：
<dependency>
    <groupId>javax.validation</groupId>
    <artifactId>validation-api</artifactId>
    <version>1.1.0.Final</version>
</dependency>

在dubbo钉钉群咨询，
配置了<dubbo:provider filter="-validation" />，没有修改java代码，重启应用后观察，
应用仍有线程池满的jstack日志生生成，数量有减少，查询jstack日志里面大部分为业务代码读写数据以及
codis缓存等占用线程，分析跟慢查询、sql写法以及索引有关，待以后应用和数据库优化；
5个节点的日志里均没有再出现上述JValidator.validate的日志；

jstack日志：
```
"DubboServerHandler-10.1.5.43:20879-thread-489" Id=568 BLOCKED on java.lang.Object@1d72d35e owned by "DubboServerHandler-10.1.5.43:20879-thread-264" Id=340
	at java.lang.ClassLoader.loadClass(ClassLoader.java:404)
	-  blocked on java.lang.Object@1d72d35e
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.alibaba.dubbo.validation.support.jvalidation.JValidator.validate(JValidator.java:241)
	at com.alibaba.dubbo.validation.filter.ValidationFilter.invoke(ValidationFilter.java:48)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:61)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:64)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:41)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.winxuan.zipkin.dubbo.BraveProviderFilter.invoke(BraveProviderFilter.java:53)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:71)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:131)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:37)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:37)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:98)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:168)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:50)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:79)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	...

	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@48557073
```

通过arthas执行thread -b：
```
$ thread -b
"DubboServerHandler-10.1.5.43:20879-thread-178" Id=236 RUNNABLE
    at java.lang.ClassLoader.loadClass(ClassLoader.java:404)
    -  locked java.lang.Object@1d72d35e <---- but blocks 93 other threads!
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at com.alibaba.dubbo.validation.support.jvalidation.JValidator.validate(JValidator.java:241)
    at com.alibaba.dubbo.validation.filter.ValidationFilter.invoke(ValidationFilter.java:48)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
    at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:61)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
    at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:64)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
    at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:41)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
    at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:77)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
    at com.winxuan.zipkin.dubbo.BraveProviderFilter.invoke(BraveProviderFilter.java:53)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
    at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:71)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
    at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:131)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
    at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:37)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
    at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:37)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:68)
    at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:98)
    at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
    at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:168)
    at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:50)
    at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:79)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

    Number of locked synchronizers = 1
    - java.util.concurrent.ThreadPoolExecutor$Worker@2b9ae523
```

**Comment by edwardlee03** [comment]
1、从描述看，你现在还没确定`线程池满`的根源。建议把`Dubbo_JStack.log`放上来，把相应的IP地址替换一下，以便大家一起分析。
2、参数验证功能不成熟，不建议使用。
![image](https://user-images.githubusercontent.com/1811851/48315778-79fb1580-e615-11e8-8ae3-25b00de16062.png)

**Comment by cdfive** [comment]
> 1、从描述看，你现在还没确定`线程池满`的根源。建议把`Dubbo_JStack.log`放上来，把相应的IP地址替换一下，以便大家一起分析。
> 2、参数验证功能不成熟，不建议使用。
> ![image](https://user-images.githubusercontent.com/1811851/48315778-79fb1580-e615-11e8-8ae3-25b00de16062.png)

感谢回复~ 验证参数在文档也看到了，有少数应用用了这个，目前已修改为程序中进行参数验证。
Dubbo_JStack.log发dubbo钉钉群了的；
线程池配置固定500，有1个文件里接近500个线程有这行日志
com.alibaba.dubbo.validation.support.jvalidation.JValidator.validate(JValidator.java:241)
其它日志文件，大概有5-200个左右，其它线程在在处理业务。

**Comment by carryxyh** [comment]
@cdfive 
你好，建议你试试master版本的代码。
master版本是2.7.0-SNAPSHOT。是一个没有发布的版本，但是不影响你测试这个问题。
最新的代码中优化了这个地方，增加了缓存，可能会好一些。

具体的提交：
https://github.com/apache/incubator-dubbo/commit/ab86c4572604cd4d4eecfa884af1c209cd3b84d6

**Comment by cdfive** [comment]
目前把validation="true"去掉，没有再出现这个问题了；
线上应用换2.7.0-SNAPSHOT版本暂时不方便，目前大部分应用都是在接口代码里做的参数验证；
等RELEASE版发布了，JSR303验证这种方式我们在调研下哈；
感谢两位回复~
