### ISSUE TITLE
Duplicate monitor configs

### ISSUE THREAD

**Issue by lix909** [apache/incubator-dubbo#2773]
dubbo2.5.1 版本 使用XML配置 报Caused by: java.lang.IllegalStateException: Duplicate monitor configs 
XML: 只配了一条<dubbo:monitor protocol="${dubbo.monitor.protocol:registry}" />

ERROR
Caused by: java.lang.IllegalStateException: Duplicate monitor configs: <dubbo:monitor protocol="dubbo" id="com.alibaba.dubbo.config.MonitorConfig" /> and <dubbo:monitor protocol="dubbo" id="com.alibaba.dubbo.config.MonitorConfig" />
    at com.alibaba.dubbo.config.spring.ReferenceBean.afterPropertiesSet(ReferenceBean.java:157)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1631)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1568)
    ... 31 more

DEBUG:
{com.alibaba.dubbo.config.MonitorConfig=<dubbo:monitor protocol="dubbo" id="com.alibaba.dubbo.config.MonitorConfig" />, .:monitor=<dubbo:monitor protocol="dubbo" id="com.alibaba.dubbo.config.MonitorConfig" />}
![image](https://user-images.githubusercontent.com/21310676/48321083-c3218880-e65a-11e8-9276-b2d9d11d1800.png)

**Comment by beiwei30** [comment]
cannot reproduce, pls. try the latest bits.
