### ISSUE TITLE
dubbo-demo consumer failed to subscribe from zookeeper

### ISSUE THREAD

**Issue by k3gu** [apache/incubator-dubbo#2785]
### 1.dubbo-demo version:
dubbo-demo-2.7.0-SNAPSHOT

### 2.consumer configuration:
<dubbo:application name="demo-consumer"/>
<dubbo:registry address="zookeeper://192.168.0.104:2181"/>

### 4.errors:
```
idea console:
org.apache.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service org.apache.dubbo.demo.DemoService. No provider available for the service org.apache.dubbo.demo.DemoService from registry 192.168.0.104:2181 on the consumer 192.168.0.104 using the dubbo version 2.7.0-SNAPSHOT. Please check if the providers have been started and registered.
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.checkInvokers(AbstractClusterInvoker.java:266)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:57)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:242)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:75)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:70)
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java)
	at org.apache.dubbo.demo.consumer.Consumer.main(Consumer.java:41)
```
```
zookeeper:
Unable to read additional data from client sessionid 0x10001ccc1cc000a, likely client has closed socket
```
### 5.others
```
a.provider connect to zookeeper successful.
b.Its successful to call provider.sayHello with consumer directly.
<dubbo:reference id="demoService" check="false" interface="org.apache.dubbo.demo.DemoService"
                     timeout="2000" url="dubbo://localhost:8001"/>
```

Thanks for reading.

**Comment by k3gu** [comment]
2.6.5 runs well.
```
<parent>
        <groupId>com.alibaba</groupId>
        <artifactId>dubbo-demo</artifactId>
        <version>2.6.5</version>
</parent>
```
