### ISSUE TITLE
监听的时候报错

### ISSUE THREAD

**Issue by DamonChow** [apache/incubator-dubbo#283]
```
[ERROR] [2016-07-14 22:08:27,061] org.apache.curator.framework.imps.CuratorFrameworkImpl - Watcher exceptionorg.apache.curator.framework.imps.CuratorFrameworkImpl.logError(CuratorFrameworkImpl.java:555)
java.lang.IllegalArgumentException: Path cannot be null
        at org.apache.zookeeper.common.PathUtils.validatePath(PathUtils.java:45)
        at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1572)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:214)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl$3.call(GetChildrenBuilderImpl.java:203)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.pathInForeground(GetChildrenBuilderImpl.java:199)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:191)
        at org.apache.curator.framework.imps.GetChildrenBuilderImpl.forPath(GetChildrenBuilderImpl.java:38)
        at com.alibaba.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient$CuratorWatcherImpl.process(CuratorZookeeperClient.java:119)
        at org.apache.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:67)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:522)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)
```

**Comment by ralf0131** [comment]
Hi, please check your path, from the stack trace you provided, there is nothing to do on Dubbo side. I am closing it now.
