### ISSUE TITLE
enhance org.apache.dubbo.common.concurrent.CompletableFutureTaskTest#testCustomExecutor

### ISSUE THREAD

**Issue by beiwei30** [apache/incubator-dubbo#2899]
org.apache.dubbo.common.concurrent.CompletableFutureTaskTest#testCustomExecutor need to enhance. Recently Traivs CI reports the following error:

```
org.apache.dubbo.common.logger.slf4j.Slf4jLoggerTest
testLocationAwareLogger(org.apache.dubbo.common.logger.slf4j.Slf4jLoggerTest)  Time elapsed: 0.251 sec  <<< ERROR!
org.mockito.exceptions.misusing.UnfinishedVerificationException: 

Missing method call for verify(mock) here:
-> at org.apache.dubbo.common.concurrent.CompletableFutureTaskTest.testCustomExecutor(CompletableFutureTaskTest.java:95)

Example of correct verification:
    verify(mock).doSomething()

Also, this error might show up because you verify either of: final/private/equals()/hashCode() methods.
Those methods *cannot* be stubbed/verified.
Mocking methods declared on non-public parent classes is not supported.

	at org.apache.dubbo.common.logger.slf4j.Slf4jLoggerTest.testLocationAwareLogger(Slf4jLoggerTest.java:34)
```

**Comment by beiwei30** [comment]
@biyuhao will be on this issue.
