### ISSUE TITLE
服务注册失败重试问题

### ISSUE THREAD

**Issue by freelingchang** [apache/incubator-dubbo#291]
前些天我们的zookeeper 有个节点(应用只配置了一个节点)卡了1分钟左右，导致小部分服务状态丢失，当zk恢复正常后服务并没有重新注册去，请问怎么调整注册(非调用)重试时间间隔和总次数?谢谢~

以下是provider日志信息

```
2016-07-14 17:22:41.385 [main-SendThread(10.0.0.52:2181)] WARN  org.apache.zookeeper.ClientCnxn - Session 0x155e8b67af300a3 for server 10.0.0.52/10.0.0.52:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Connection reset by peer
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.7.0_79]
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.7.0_79]
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.7.0_79]
    at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.7.0_79]
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.7.0_79]
    at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68) ~[zookeeper-3.4.6.jar:3.4.6-156
9965]
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366) ~[zookeeper-3.4.6.jar:3
.4.6-1569965]
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar:3.4.6-1569965]
2016-07-14 17:22:41.487 [main-EventThread] INFO  o.a.curator.framework.state.ConnectionStateManager - State change: SUSPENDED
2016-07-14 17:22:42.458 [main-SendThread(10.0.0.52:2182)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server 10.0.0.52/10.0.0.52:2182. Will not attempt to authenticate using SASL (unknown error)
2016-07-14 17:22:42.460 [main-SendThread(10.0.0.52:2182)] INFO  org.apache.zookeeper.ClientCnxn - Socket connec
tion established to 10.0.0.52/10.0.0.52:2182, initiating session
2016-07-14 17:22:42.462 [main-SendThread(10.0.0.52:2182)] INFO  org.apache.zookeeper.ClientCnxn - Session estab lishment complete on server 10.0.0.52/10.0.0.52:2182, sessionid = 0x155e8b67af300a3, negotiated timeout = 40000
2016-07-14 17:22:42.463 [main-EventThread] INFO  o.a.curator.framework.state.ConnectionStateManager - State change: RECONNECTED
2016-07-14 17:22:42.499 [DubboRegistryFailedRetryTimer-thread-1] INFO  c.a.dubbo.registry.zookeeper.ZookeeperRegistry -  [DUBBO] Notify urls for subscribe url provider://***], dubbo version: 2.8.4, current host: 10.0.0.122
2016-07-14 17:23:17.457 [New I/O worker #2] WARN  c.alibaba.dubbo.remoting.transport.AbstractServer -  [DUBBO] All clients has discontected from /10.0.0.122:20991. You can graceful shutdown now., dubbo version: 2.8.4, current host: 10.0.0.122
```

后面一直重复

```
2016-07-14 17:25:31.172 [New I/O worker #1] WARN  c.alibaba.dubbo.remoting.transport.AbstractServer -  [DUBBO] All clients has discontected from /10.0.0.122:20991. You can graceful shutdown now., dubbo version: 2.8.4, current host: 10.0.0.122
```

**Comment by duguyixiaono1** [comment]
遇到过相同的问题，后来有什么解决方案吗？ @freelingchang

**Comment by ralf0131** [comment]
I am afraid currently Dubbo does not support retry on service registration. I think this can be an improvement.

**Comment by beiwei30** [comment]
现在应该没有这个问题，你试试最新版本。
