### ISSUE TITLE
dubbo exception: no route to host

### ISSUE THREAD

**Issue by wy545** [apache/incubator-dubbo#3050]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

线上dubbo偶尔会抛出异常，异常信息如下：
com.caucho.hessian.client.HessianRuntimeException: java.net.NoRouteToHostException: No route to host
是不是dubbo本身存在一些问题？求大神指教

**Comment by wy545** [comment]
可能是网络问题，目前使用的hessian协议，不知道是不是这个原因

**Comment by carryxyh** [comment]
你们使用的是HessianProtocol吧。
建议如上，先排查一下网络问题吧。

**Comment by wy545** [comment]
网上各种搜了一遍，也有其他网友使用的heassian出现这个问题的。。异常信息如下：
` ERROR c.n.l.k.c.d.t.a.p.TradeProductAdapter  [T:1358299442]  query product config error Exception [productRateRequestVo=ChannelRateRequestVo(channelCode=quhua_kaola, userCreditLevelAlias=A, productCode=quhua_kaola)]
com.caucho.hessian.client.HessianRuntimeException: java.net.NoRouteToHostException: No route to host
        at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:281) ~[hessian-4.0.38.jar:na]
        at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:171) ~[hessian-4.0.38.jar:na]
        at com.sun.proxy.$Proxy71.queryProductRateByChannelCode(Unknown Source) ~[na:na]
        at com.alibaba.dubbo.common.bytecode.Wrapper1.invokeMethod(Wrapper1.java) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:46) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:72) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.AbstractProxyProtocol$2.doInvoke(AbstractProxyProtocol.java:93) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.8.4.jar:2.8.4]
        at com.netease.loan.logtrack.dubbo.DubboMdcFilter.invoke(DubboMdcFilter.java:41) ~[log-track-spring-boot-starter-1.0-20180723.072233-4.jar:na]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke$sentryProxy(MockClusterInvoker.java:72) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) ~[dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.common.bytecode.proxy1.queryProductRateByChannelCode(proxy1.java) ~[dubbo-2.8.4.jar:2.8.4]
        at com.netease.loan.kylin.core.domain.trade.adapter.pixiu.TradeProductAdapter.queryProductRateByChannelCodeAndUserCreditLevel$sentryProxy4(TradeProductAdapter.java:130) [kylin-core-1.0.0-SNAPSHOT.jar:na]
        at com.netease.loan.kylin.core.domain.trade.adapter.pixiu.TradeProductAdapter.queryProductRateByChannelCodeAndUserCreditLevel(TradeProductAdapter.java) [kylin-core-1.0.0-SNAPSHOT.jar:na]
        at com.netease.loan.kylin.core.domain.trade.service.biz.impl.ProductBizServiceImpl.queryProductRate$sentryProxy1(ProductBizServiceImpl.java:56) [kylin-core-1.0.0-SNAPSHOT.jar:na]
        at com.netease.loan.kylin.core.domain.trade.service.biz.impl.ProductBizServiceImpl.queryProductRate(ProductBizServiceImpl.java) [kylin-core-1.0.0-SNAPSHOT.jar:na]
        at com.netease.loan.kylin.core.domain.trade.service.biz.impl.PaymentBizServiceImpl.createDebitAndRepayments(PaymentBizServiceImpl.java:259) [kylin-core-1.0.0-SNAPSHOT.jar:na]
        at com.netease.loan.kylin.core.domain.trade.service.biz.impl.PaymentBizServiceImpl.executePayment$sentryProxy1(PaymentBizServiceImpl.java:151) [kylin-core-1.0.0-SNAPSHOT.jar:na]
        at com.netease.loan.kylin.core.domain.trade.service.biz.impl.PaymentBizServiceImpl.executePayment(PaymentBizServiceImpl.java) [kylin-core-1.0.0-SNAPSHOT.jar:na]
        at com.netease.loan.kylin.core.domain.trade.service.facade.impl.PaymentFacadeServiceImpl.executePayment$sentryProxy1(PaymentFacadeServiceImpl.java:99) [kylin-core-1.0.0-SNAPSHOT.jar:na]
        at com.netease.loan.kylin.core.domain.trade.service.facade.impl.PaymentFacadeServiceImpl.executePayment(PaymentFacadeServiceImpl.java) [kylin-core-1.0.0-SNAPSHOT.jar:na]
        at com.netease.loan.kylin.platform.quhua.adapter.trade.PaymentAdapter.executePayment$sentryProxy1(PaymentAdapter.java:136) [PaymentAdapter.class:na]
        at com.netease.loan.kylin.platform.quhua.adapter.trade.PaymentAdapter.executePayment(PaymentAdapter.java) [PaymentAdapter.class:na]
        at com.netease.loan.kylin.platform.quhua.adapter.trade.PaymentAdapter.ExecuteCampaignIfExists(PaymentAdapter.java:744) [PaymentAdapter.class:na]
        at com.netease.loan.kylin.platform.quhua.adapter.trade.PaymentAdapter.executePaymentForActiveUser(PaymentAdapter.java:672) [PaymentAdapter.class:na]
        at com.netease.loan.kylin.platform.quhua.adapter.trade.PaymentAdapter.executeActiveAndPayment$sentryProxy6(PaymentAdapter.java:321) [PaymentAdapter.class:na]
        at com.netease.loan.kylin.platform.quhua.adapter.trade.PaymentAdapter.executeActiveAndPayment(PaymentAdapter.java) [PaymentAdapter.class:na]
        at com.netease.loan.kylin.platform.quhua.controller.trade.epay.EpayPaymentController.activateAndLoanOut$sentryProxy1(EpayPaymentController.java:53) [EpayPaymentController.class:na]
        at com.netease.loan.kylin.platform.quhua.controller.trade.epay.EpayPaymentController.activateAndLoanOut(EpayPaymentController.java) [EpayPaymentController.class:na]
        at com.netease.loan.kylin.platform.quhua.controller.trade.epay.EpayPaymentController$$FastClassBySpringCGLIB$$8b834790.invoke(<generated>) [EpayPaymentController.class:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.15.RELEASE.jar:4.3.15.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) [spring-aop-4.3.15.RELEASE.jar:4.3.15.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) [spring-aop-4.3.15.RELEASE.jar:4.3.15.RELEASE]
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:97) [spring-aop-4.3.15.RELEASE.jar:4.3.15.RELEASE]
        at com.netease.loan.kylin.platform.quhua.utils.log.ApiLogAspect.doLog(ApiLogAspect.java:66) [ApiLogAspect.class:na]
        at com.netease.loan.kylin.platform.quhua.utils.log.ApiLogAspect.allControllerMethod$sentryProxy1(ApiLogAspect.java:41) [ApiLogAspect.class:na]
        at com.netease.loan.kylin.platform.quhua.utils.log.ApiLogAspect.allControllerMethod(ApiLogAspect.java) [ApiLogAspect.class:na]
        at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source) ~[na:na]
`

**Comment by beiwei30** [comment]
看堆栈是网络问题。在 fail over 的情况下应该会重试。
