### ISSUE TITLE
Could not start demo in latest master branch

### ISSUE THREAD

**Issue by ralf0131** [apache/incubator-dubbo#3071]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: MacOS
* Java version: 11.0.1

### Steps to reproduce this issue

1. Run org.apache.dubbo.demo.provider.Provider

### Expected Result

Provider should start.

### Actual Result

```
Caused by: java.lang.IllegalStateException: Failed to connect to config center (zookeeper): 127.0.0.1:2181 in 30000ms.
	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfiguration.initWith(ZookeeperDynamicConfiguration.java:79)
	at org.apache.dubbo.configcenter.AbstractDynamicConfiguration.<init>(AbstractDynamicConfiguration.java:46)
	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfiguration.<init>(ZookeeperDynamicConfiguration.java:62)
	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfigurationFactory.createDynamicConfiguration(ZookeeperDynamicConfigurationFactory.java:29)
	at org.apache.dubbo.configcenter.AbstractDynamicConfigurationFactory.getDynamicConfiguration(AbstractDynamicConfigurationFactory.java:33)
	at org.apache.dubbo.config.ConfigCenterConfig.startDynamicConfiguration(ConfigCenterConfig.java:105)
	at org.apache.dubbo.config.ConfigCenterConfig.init(ConfigCenterConfig.java:82)
	at org.apache.dubbo.config.spring.ConfigCenterBean.afterPropertiesSet(ConfigCenterBean.java:98)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1688)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
	... 12 more
```

People may not install zookeeper locally, we need to restore the behavior to use multicast as default registry.

**Comment by khanimteyaz** [comment]
@ralf0131 are you referring to incubator-dubbo/dubbo-demo/dubbo-demo-provider's Provider example? I just run it and it seems to be working fine ? If this is project you are referring then would you see I am missing something here?
