### ISSUE TITLE
java.lang.NoClassDefFoundError: org/nustaq/extension/VersionInfo

### ISSUE THREAD

**Issue by cholf** [apache/incubator-dubbo#3198]
ERROR: 2019-01-09 18:05:10.132 10.18.34.227 [com.alibaba.dubbo.common.logger.log4j.Log4jLogger.java:91 Log4jLogger::error()] [DUBBO] Failed to setChangedClassInfo /changedclass, cause: org/nustaq/extension/VersionInfo, dubbo version: 2.6.0.2, current host: 10.18.34.227
java.lang.NoClassDefFoundError: org/nustaq/extension/VersionInfo
at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.wrapChangedClassInfo(ZookeeperRegistry.java:158)
at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.setChangedClassInfo(ZookeeperRegistry.java:142)
at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.getDisabledProviderSet(ZookeeperRegistry.java:121)
at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.<init>(ZookeeperRegistry.java:92)
at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistryFactory.createRegistry(ZookeeperRegistryFactory.java:37)
at com.alibaba.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:95)
at com.alibaba.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:281)
at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:98)
at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:75)
at com.alibaba.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:394)
at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:333)
at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:163)

**Comment by beiwei30** [comment]
it looks like not a dubbo issue. there's no method like **setChangedClassInfo** in ZookeeperRegistry.

**Comment by kyle1970** [comment]
miss fst lib.

**Comment by cholf** [comment]
> it looks like not a dubbo issue. there's no method like **setChangedClassInfo** in ZookeeperRegistry.
com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry,  pre_key is "com.alibaba.dubbo."
