### ISSUE TITLE
DubboServerHandler parking to wait

### ISSUE THREAD

**Issue by luoye1989hzx** [apache/incubator-dubbo#3261]
DubboServerHandler-172.16.20.113:20835-thread-399 - priority:5 - threadId:0x00007fb748117800 - nativeId:0x202 - nativeId (decimal):514 - state:WAITING
stackTrace:
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000000833e9318> (a java.util.concurrent.SynchronousQueue$TransferStack)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
at java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

哪些原因会导致这个错误

线程池达到最大值后，后续请求会被block，会导致内存不断增加吗

**Comment by carryxyh** [comment]
getTask在队列里没有任务的时候会阻塞的。

> 线程池达到最大值后，后续请求会被block，会导致内存不断增加吗

当然不会。会产生一条pool exhausted的异常并且直接返回。

**Comment by luoye1989hzx** [comment]
线程池已经被打满，我们配置了400个，已经被耗尽，而且内存会逐渐升高

**Comment by goto456** [comment]
> 

后来找到原因了吗？确定是线程池打满造成的吗？我也遇到了类似的问题
