### ISSUE TITLE
dubbo-registry/dubbo-registry-zookeeper/test 测试类启动注册失败。

### ISSUE THREAD

**Issue by cyf123456** [apache/incubator-dubbo#3325]
dubbo-registry-zookeeper 中启动测试类注册 zookeeper服务失败，报错内容如下：

Disconnected from the target VM, address: '127.0.0.1:60916', transport: 'socket'
Exception in thread "main" java.lang.NoSuchMethodError: org.junit.platform.commons.util.ReflectionUtils.getDefaultClassLoader()Ljava/lang/ClassLoader;
	at org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry.loadTestEngines(ServiceLoaderTestEngineRegistry.java:31)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:42)
	at com.intellij.junit5.JUnit5IdeaTestRunner.createListeners(JUnit5IdeaTestRunner.java:39)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by tswstarplanet** [comment]
I just try to run the test cases and it does not throw the exception. Would you please check your environment configuration and try again?

**Comment by cyf123456** [comment]
就是 dubbo-registry-zookeeper/ test类，里边就一个测试类，我测试的是注册，方法如下：
 @Test
    public void testRegister() {
        Set<URL> registered;

        for (int i = 0; i < 2; i++) {
            zookeeperRegistry.register(serviceUrl);
            registered = zookeeperRegistry.getRegistered();
            assertThat(registered.contains(serviceUrl), is(true));
        }

        registered = zookeeperRegistry.getRegistered();
        assertThat(registered.size(), is(1));
    }

**Comment by kexianjun** [comment]
> 就是 dubbo-registry-zookeeper/ test类，里边就一个测试类，我测试的是注册，方法如下：
> @test
> public void testRegister() {
> Set registered;
> 
> ```
>     for (int i = 0; i < 2; i++) {
>         zookeeperRegistry.register(serviceUrl);
>         registered = zookeeperRegistry.getRegistered();
>         assertThat(registered.contains(serviceUrl), is(true));
>     }
> 
>     registered = zookeeperRegistry.getRegistered();
>     assertThat(registered.size(), is(1));
> }
> ```

I just run it locally, it has passed. pls update your code to the latest branch and run it again.
