### ISSUE TITLE
HessianProtocolException

### ISSUE THREAD

**Issue by Imtonoo** [apache/incubator-dubbo#337]
spring 3.2.4 dubbo 2.5.3 resin服务器

```
[11:19:40.462] [16-10-26 11:19:40.462] {resin-port-8081-1287} javax.servlet.ServletException: com.caucho.hessian.io.HessianProtocolException: downFile: expected long at 0x7a (z)
                                        at com.alibaba.dubbo.rpc.protocol.hessian.HessianProtocol$HessianHandler.handle(HessianProtocol.java:80)
                                        at com.alibaba.dubbo.remoting.http.servlet.DispatcherServlet.service(DispatcherServlet.java:64)
                                        at javax.servlet.http.HttpServlet.service(HttpServlet.java:97)
                                        at com.caucho.server.dispatch.ServletFilterChain.doFilter(ServletFilterChain.java:109)
                                        at com.caucho.server.webapp.WebAppFilterChain.doFilter(WebAppFilterChain.java:156)
                                        at com.caucho.server.dispatch.ServletInvocation.service(ServletInvocation.java:289)
                                        at com.caucho.server.http.HttpRequest.handleRequest(HttpRequest.java:838)
                                        at com.caucho.network.listen.TcpSocketLink.dispatchRequest(TcpSocketLink.java:1349)
                                        at com.caucho.network.listen.TcpSocketLink.handleRequest(TcpSocketLink.java:1305)
                                        at com.caucho.network.listen.TcpSocketLink.handleRequestsImpl(TcpSocketLink.java:1289)
                                        at com.caucho.network.listen.TcpSocketLink.handleRequests(TcpSocketLink.java:1197)
                                        at com.caucho.network.listen.TcpSocketLink.handleAcceptTaskImpl(TcpSocketLink.java:993)
                                        at com.caucho.network.listen.ConnectionTask.runThread(ConnectionTask.java:117)
                                        at com.caucho.network.listen.ConnectionTask.run(ConnectionTask.java:93)
                                        at com.caucho.network.listen.SocketLinkThreadLauncher.handleTasks(SocketLinkThreadLauncher.java:169)
                                        at com.caucho.network.listen.TcpSocketAcceptThread.run(TcpSocketAcceptThread.java:61)
                                        at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
                                        at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
                                      Caused by: com.caucho.hessian.io.HessianProtocolException: downFile: expected long at 0x7a (z)
                                        at com.caucho.hessian.io.HessianInput.error(HessianInput.java:1695)
                                        at com.caucho.hessian.io.HessianInput.expect(HessianInput.java:1681)
                                        at com.caucho.hessian.io.HessianInput.readLong(HessianInput.java:562)
                                        at com.caucho.hessian.io.BasicDeserializer.readObject(BasicDeserializer.java:172)
                                        at com.caucho.hessian.io.HessianInput.readObject(HessianInput.java:1078)
                                        at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:296)
                                        at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:198)
                                        at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:139)
                                        at com.alibaba.dubbo.rpc.protocol.hessian.HessianProtocol$HessianHandler.handle(HessianProtocol.java:78)
                                        ... 17 more
```
这是什么原因引起的啊

**Comment by lovepoem** [comment]
I know a reason for this: One of your business interface has two methods with the same names.

**Comment by lovepoem** [comment]
Now the hessian protocol cannot support that：one server interface  multiple methods with the same name (overload)

I will close it now, if you have any question, free feel to reopen it
