### ISSUE TITLE
dubbo 基于 hessian 协议下载文件 频繁超时问题

### ISSUE THREAD

**Issue by Imtonoo** [apache/incubator-dubbo#344]
日志如下：
多线程下载文件 频繁出现超时链接，每次都是10秒，dubbo服务配置文件超时时间是6000

```java
线程====9====第1次失败等待用时=====10
com.caucho.hessian.client.HessianConnectionException: 500: java.net.SocketTimeoutException: Read timed out
	at com.caucho.hessian.client.HessianURLConnection.sendRequest(HessianURLConnection.java:142)
	at com.caucho.hessian.client.HessianProxy.sendRequest(HessianProxy.java:305)
	at com.caucho.hessian.client.HessianProxy.invoke(HessianProxy.java:173)
	at com.sun.proxy.$Proxy0.downFileByPath(Unknown Source)
	at com.test.imtonoo.Test$downByPath.run(Test.java:52)
Caused by: java.net.SocketTimeoutException: Read timed out
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at com.caucho.hessian.client.HessianURLConnection.sendRequest(HessianURLConnection.java:122)
	... 4 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.caucho.hessian.client.HessianURLConnection.sendRequest(HessianURLConnection.java:109)
	... 4 more
```

**Comment by oldratlee** [comment]
dubbo的超时实现是基本功能，一般不会有bug。

首先给出你的服务配置，及你超时打印代码。最好能给一个能复现家个问题的最简代码工程，这样方便排除不是你配置或是超时打印代码的问题。


另外，可以确认一下你功能的配置中是不是有你没有发现的超时配置，比如搜索一下整个工程所有文件的timeout关键字：

```sh
grep timeout -ri .
```

**Comment by huang-gz** [comment]
Hessian 的请求发送完成后客户端才开始记录超时，可能是 4 秒发送完请求，接下来 6 秒等待服务端返回，服务端六秒没有完成返回，则客户端报超时
