### ISSUE TITLE
consumer can't received provider's error message when ExceedPayloadLimitException happens in provider

### ISSUE THREAD

**Issue by TuChenH** [apache/incubator-dubbo#3488]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.2
* Operating System version: Linux
* Java version: 1.8

### Steps to reproduce this issue

1. 服务端这边传了一个11M大小的json数据给调用端
2. 因为dubbo默认只能传8M一下的数据,所以服务端这边报错了(这是正常的):
```
java.io.IOException: Data length too large: 11120658, max payload: 8388608, channel: NettyChannel [channel=[id: 0x8e01a04d, /
```
3. 不正常的是服务端虽然报错,但是调用端一直还在等待服务端的响应,直至超时报错

4. 我看代码 服务端这边报错后会去通知调用端,通知的参数又带上了这个11M的json数据
然后又会走到`ExchangeCodec.encodeResponse()`  这个方法里面里面会去校验数据大小,导致通知还是报这个错误

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
java.io.IOException: Data length too large: 9887729, max payload: 8388608, channel: NettyChannel [channel=[id: 0x8e01a04d, /172.19.200.45:36472 => /172.19.200.45:18512]]
	at com.alibaba.dubbo.remoting.transport.AbstractCodec.checkPa
	yload(AbstractCodec.java:49)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encodeResponse(ExchangeCodec.java:285)
	at com.alibaba.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:77)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:39)
	at com.alibaba.dubbo.remoting.transport.netty.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:81)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:66)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
	at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
	at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:99)
	at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
	at org.jboss.netty.channel.Channels.write(Channels.java:704)
	at org.jboss.netty.channel.Channels.write(Channels.java:671)
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:348)
	at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:98)
	at com.alibaba.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:51)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:171)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
, result=null] to /172.19.200.45:36472, cause: Data length too large: 11120658, max payload: 8388608, channel: NettyChannel [channel=[id: 0x8e01a04d, /172.19.200.45:36472 => /172.19.200.45:18512]], dubbo version: 2.5.3, current host: 172.19.200.45
com.alibaba.dubbo.remoting.RemotingException: Failed to send message Response [id=412, version=2.0.0, status=50, event=false, error=Failed to send response: Response [id=412, version=2.0.0, status=20, event=false, error=null, result=RpcResult [result=
```

**Comment by xxlv** [comment]
在master上我并没有重现该问题，相信是版本的原因。

**Comment by chickenlj** [comment]
Please upgrade to the latest 2.6.x version.

Or upgrade to 2.7.0 with only a few changes, check [how to upgrade to 2.7.0](http://dubbo.apache.org/zh-cn/docs/user/versions/version-270.html)

**Comment by TuChenH** [comment]
> Please upgrade to the latest 2.6.x version.
> 
> Or upgrade to 2.7.0 with only a few changes, check [how to upgrade to 2.7.0](http://dubbo.apache.org/zh-cn/docs/user/versions/version-270.html)

is this a bug in my version? can you show the log that which version has fix this bug  ? 
forgive my pool english , thank you!

**Comment by chickenlj** [comment]
> is this a bug in my version? c
I'm afraid so, feel free to use the language you are familiar with, Chinese is totally ok.

https://github.com/apache/incubator-dubbo/blob/master/dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/exchange/codec/ExchangeCodec.java#L303

**Comment by zpLiuHH** [comment]
我使用的master分支在执行maven install 执行到该段测试方法时也有这个问题，修改了DEFAULT_PAYLOAD也不管用，错误还是会出现。
