### ISSUE TITLE
No such extension org.apache.dubbo.metadata.store.MetadataReportFactory by name redis

### ISSUE THREAD

**Issue by foreveryang321** [apache/incubator-dubbo#3514]
### Environment

* Dubbo version: 2.7.0
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

```yaml
dubbo:
  application:
    name: ${spring.application.nam}
    qos-enable: false
  registry:
    address: zookeeper://192.168.56.101:2181
    client: curator
    simplified: true
  metadata-report:
    address: redis://192.168.56.101:6379
```

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

```
java.lang.IllegalStateException: No such extension org.apache.dubbo.metadata.store.MetadataReportFactory by name redis
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:514)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:521)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:344)
	at org.apache.dubbo.metadata.store.MetadataReportFactory$Adaptive.getMetadataReport(MetadataReportFactory$Adaptive.java)
	at org.apache.dubbo.metadata.integration.MetadataReportService.<init>(MetadataReportService.java:54)
	at org.apache.dubbo.metadata.integration.MetadataReportService.instance(MetadataReportService.java:67)
	at org.apache.dubbo.config.AbstractInterfaceConfig.getMetadataReportService(AbstractInterfaceConfig.java:387)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:568)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:402)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:363)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:345)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:318)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:112)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:58)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:886)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1242)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1230)
```

**Comment by chickenlj** [comment]
Yes, it's missed. 
For 2.7.0, please add `dubbo-metadata-redis` dependency to solve this problem.
