### ISSUE TITLE
Something wrong with dubbo-demo-annotation

### ISSUE THREAD

**Issue by kexianjun** [apache/incubator-dubbo#3561]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: latest master branch
* Operating System version: xxx
* Java version: 1.8

### Steps to reproduce this issue

1. run org.apache.dubbo.demo.provider.Application
2. run org.apache.dubbo.demo.consumer.Application

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

work fine

### Actual Result

consumer side throws an exception

If there is an exception, please attach the exception trace:

```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceComponent': Injection of @org.apache.dubbo.config.annotation.Reference dependencies is failed; nested exception is java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.demo.DemoService. No provider available for the service org.apache.dubbo.demo.DemoService from the url multicast://224.5.6.7:1234/org.apache.dubbo.registry.RegistryService?anyhost=true&application=dubbo-demo-annotation-consumer&bean.name=ServiceBean:org.apache.dubbo.demo.DemoService&check=true&default.check=true&default.init=false&default.injvm=false&default.lazy=false&default.sticky=false&dubbo=2.0.2&generic=false&group=&init=false&injvm=false&interface=org.apache.dubbo.demo.DemoService&lazy=false&methods=sayHello&pid=20456&register.ip=10.200.182.127&remote.application=dubbo-demo-annotation-provider&remote.timestamp=1549878480376&side=consumer&sticky=false&timestamp=1551085801200 to the consumer 10.200.182.127 use dubbo version 
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor.postProcessPropertyValues(AnnotationInjectedBeanPostProcessor.java:133)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1268)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at org.apache.dubbo.demo.consumer.Application.main(Application.java:36)
Caused by: java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.demo.DemoService. No provider available for the service org.apache.dubbo.demo.DemoService from the url multicast://224.5.6.7:1234/org.apache.dubbo.registry.RegistryService?anyhost=true&application=dubbo-demo-annotation-consumer&bean.name=ServiceBean:org.apache.dubbo.demo.DemoService&check=true&default.check=true&default.init=false&default.injvm=false&default.lazy=false&default.sticky=false&dubbo=2.0.2&generic=false&group=&init=false&injvm=false&interface=org.apache.dubbo.demo.DemoService&lazy=false&methods=sayHello&pid=20456&register.ip=10.200.182.127&remote.application=dubbo-demo-annotation-provider&remote.timestamp=1549878480376&side=consumer&sticky=false&timestamp=1551085801200 to the consumer 10.200.182.127 use dubbo version 
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:398)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:306)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:230)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.init(ReferenceAnnotationBeanPostProcessor.java:162)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.access$100(ReferenceAnnotationBeanPostProcessor.java:146)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.buildInvocationHandler(ReferenceAnnotationBeanPostProcessor.java:140)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.buildProxy(ReferenceAnnotationBeanPostProcessor.java:122)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:116)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:49)
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor.getInjectedObject(AnnotationInjectedBeanPostProcessor.java:342)
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor$AnnotatedFieldElement.inject(AnnotationInjectedBeanPostProcessor.java:522)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.apache.dubbo.config.spring.beans.factory.annotation.AnnotationInjectedBeanPostProcessor.postProcessPropertyValues(AnnotationInjectedBeanPostProcessor.java:129)
	... 12 more
```

**Comment by tswstarplanet** [comment]
What system did you use? I have tried it, and everything is ok. Is it something wrong with your system ?

**Comment by kexianjun** [comment]
> What system did you use? I have tried it, and everything is ok. Is it something wrong with your system ?

Win 10. provider and consumer run in the same machine. I debug this, seems same issue as #3401

**Comment by balderdasher** [comment]
Same system,same issue.

**Comment by DOnlyone** [comment]
Same system,same issue.how to fix?

**Comment by kexianjun** [comment]
pls config unicast to true，like
```java
<dubbo:application name="demo-consumer">
        <dubbo:parameter key="unicast" value="false" />
</dubbo:application>
```
or
```java
<dubbo:consumer>
        <dubbo:parameter key="unicast" value="false" />
</dubbo:consumer>
```

**Comment by dengkang** [comment]
When I run dubbo-demo/dubbo-demo-annotation, I run the provider and consumer on a single computer at the same time.
Using the protocol="multicast" as the registry, the same exception occurred: Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceComponent': Injection of @Reference dependencies is failed; nested exception Is java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.demo.DemoService. No provider available for the service org.apache.dubbo.demo.DemoService from the url multicast://224.5.6.7 :1234/org.apache.dubbo.registry.RegistryService?application=dubbo-demo-annotation-consumer&dubbo=2.0.2&interface=org.apache.dubbo.demo.DemoService&lazy=false&methods=sayHello&pid=4720&register.ip=127.0.0.1&side= Consumer&sticky=false&timestamp=1563670839437 to the consumer 127.0.0.1 use dubbo version . Then I added the parameter @Reference(parameters = {"unicast","false"}) to the interface introduced in the consumer project, and the project runs normally. The strange thing is that when I remove the parameters, I can't reproduce the exception again and still run normally.

**Comment by kexianjun** [comment]
> When I run dubbo-demo/dubbo-demo-annotation, I run the provider and consumer on a single computer at the same time.
> Using the protocol="multicast" as the registry, the same exception occurred: Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceComponent': Injection of @reference dependencies is failed; nested exception Is java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.demo.DemoService. No provider available for the service org.apache.dubbo.demo.DemoService from the url multicast://224.5.6.7 :1234/org.apache.dubbo.registry.RegistryService?application=dubbo-demo-annotation-consumer&dubbo=2.0.2&interface=org.apache.dubbo.demo.DemoService&lazy=false&methods=sayHello&pid=4720&register.ip=127.0.0.1&side= Consumer&sticky=false&timestamp=1563670839437 to the consumer 127.0.0.1 use dubbo version . Then I added the parameter @reference(parameters = {"unicast","false"}) to the interface introduced in the consumer project, and the project runs normally. The strange thing is that when I remove the parameters, I can't reproduce the exception again and still run normally.

pls check if the cache in dir /{user home}/.dubbo has an impact

**Comment by dengkang** [comment]
> > When I run dubbo-demo/dubbo-demo-annotation, I run the provider and consumer on a single computer at the same time.
> > Using the protocol="multicast" as the registry, the same exception occurred: Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceComponent': Injection of @reference dependencies is failed; nested exception Is java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.demo.DemoService. No provider available for the service org.apache.dubbo.demo.DemoService from the url multicast://224.5.6.7 :1234/org.apache.dubbo.registry.RegistryService?application=dubbo-demo-annotation-consumer&dubbo=2.0.2&interface=org.apache.dubbo.demo.DemoService&lazy=false&methods=sayHello&pid=4720&register.ip=127.0.0.1&side= Consumer&sticky=false&timestamp=1563670839437 to the consumer 127.0.0.1 use dubbo version . Then I added the parameter @reference(parameters = {"unicast","false"}) to the interface introduced in the consumer project, and the project runs normally. The strange thing is that when I remove the parameters, I can't reproduce the exception again and still run normally.
> 
> pls check if the cache in dir /{user home}/.dubbo has an impact

Sure enough. Using @Reference(parameters = {"unicast","false"}) , the cache file dubbo-registry-dubbo-demo-annotation-consumer-224.5.6.7 is generated under \user\.dubbo. Removing the cache file exception reappears. Thank you

**Comment by dengkang** [comment]
> > When I run dubbo-demo/dubbo-demo-annotation, I run the provider and consumer on a single computer at the same time.
> > Using the protocol="multicast" as the registry, the same exception occurred: Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceComponent': Injection of @reference dependencies is failed; nested exception Is java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.demo.DemoService. No provider available for the service org.apache.dubbo.demo.DemoService from the url multicast://224.5.6.7 :1234/org.apache.dubbo.registry.RegistryService?application=dubbo-demo-annotation-consumer&dubbo=2.0.2&interface=org.apache.dubbo.demo.DemoService&lazy=false&methods=sayHello&pid=4720&register.ip=127.0.0.1&side= Consumer&sticky=false&timestamp=1563670839437 to the consumer 127.0.0.1 use dubbo version . Then I added the parameter @reference(parameters = {"unicast","false"}) to the interface introduced in the consumer project, and the project runs normally. The strange thing is that when I remove the parameters, I can't reproduce the exception again and still run normally.
> 
> pls check if the cache in dir /{user home}/.dubbo has an impact

Sure enough. Using @Reference(parameters = {"unicast","false"}) , the cache file dubbo-registry-dubbo-demo-annotation-consumer-224.5.6.7 is generated under  /{user home}/.dubbo. Removing the cache file exception reappears. Thank you

**Comment by szkb** [comment]
> > When I run dubbo-demo/dubbo-demo-annotation, I run the provider and consumer on a single computer at the same time.
> > Using the protocol="multicast" as the registry, the same exception occurred: Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'demoServiceComponent': Injection of @reference dependencies is failed; nested exception Is java.lang.IllegalStateException: Failed to check the status of the service org.apache.dubbo.demo.DemoService. No provider available for the service org.apache.dubbo.demo.DemoService from the url multicast://224.5.6.7 :1234/org.apache.dubbo.registry.RegistryService?application=dubbo-demo-annotation-consumer&dubbo=2.0.2&interface=org.apache.dubbo.demo.DemoService&lazy=false&methods=sayHello&pid=4720&register.ip=127.0.0.1&side= Consumer&sticky=false&timestamp=1563670839437 to the consumer 127.0.0.1 use dubbo version . Then I added the parameter @reference(parameters = {"unicast","false"}) to the interface introduced in the consumer project, and the project runs normally. The strange thing is that when I remove the parameters, I can't reproduce the exception again and still run normally.
> 
> pls check if the cache in dir /{user home}/.dubbo has an impact

I have the same question with you.
