### ISSUE TITLE
本地dubbo启动接口注册到局域网

### ISSUE THREAD

**Issue by MrXuCh** [apache/incubator-dubbo#3595]
1.本地启动dubbo服务,zk也是本地的 项目配合文件用的注册地址也是127.0.0.1 但是启动控制层时接口注册地址连接的是局域网地址,导致接口注册不上.
![image](https://user-images.githubusercontent.com/29686600/53775674-6b22d080-3f2e-11e9-8514-d9c25f6cb506.png)
![image](https://user-images.githubusercontent.com/29686600/53775697-7c6bdd00-3f2e-11e9-8f67-22476d4dc3ed.png)
![image](https://user-images.githubusercontent.com/29686600/53775711-8beb2600-3f2e-11e9-8362-8ee5787a9af0.png)

log日志,部分用了...遮盖了业务接口名字

2019-03-05 09:52:54.484 [main] INFO  o.s.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -
				Bean 'jxlCollectController' of type [cn.fintecher.dsIntegration.api.....Controller] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2019-03-05 09:52:54.506 [main] INFO  com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry -
				 [DUBBO] Register: consumer://192.168.44.1/cn.fintecher.dsIntegration.service.......Service?application=dubbo-consumer&category=consumers&check=false&dubbo=2.5.3&interface=cn.fintecher.dsIntegration.service......Service&methods=report,collect&pid=2188&revision=1.0.0&side=consumer&timeout=50000&timestamp=155175....&version=1.0.0, dubbo version: 2.5.3, current host: 192.168.44.1
2019-03-05 09:52:54.516 [main] INFO  com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry -
				 [DUBBO] Subscribe: consumer://192.168.44.1/cn.fintecher.dsIntegration.service......Service?application=dubbo-consumer&category=providers,configurators,routers&dubbo=2.5.3&interface=cn.fintecher.dsIntegration.service.......Service&methods=report,collect&pid=2188&revision=1.0.0&side=consumer&timeout=50000&timestamp=1551750774502&version=1.0.0, dubbo version: 2.5.3, current host: 192.168.44.1
2019-03-05 09:52:54.542 [main] INFO  com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry -
				 [DUBBO] Notify urls for subscribe url consumer://192.168.44.1/cn.fintecher.dsIntegration.service.......Service?application=dubbo-consumer&category=providers,configurators,routers&dubbo=2.5.3&interface=cn.fintecher.dsIntegration.service......Service&methods=report,collect&pid=2188&revision=1.0.0&side=consumer&timeout=50000&timestamp=1551750....2&version=1.0.0, urls: [empty://192.168.44.1/cn.fintecher.dsIntegration.service.juxinli.IJxlCreditInveService?application=dubbo-consumer&category=providers&dubbo=2.5.3&interface=cn.fintecher.dsIntegration.service.juxinli.IJxlCreditInveService&methods=report,collect&pid=2188&revision=1.0.0&side=consumer&timeout=50000&timestamp=1551750774502&version=1.0.0, empty://192.168.44.1/cn.fintecher.dsIntegration.service.juxinli.IJxlCreditInveService?application=dubbo-consumer&category=configurators&dubbo=2.5.3&interface=cn.fintecher.dsIntegration.service.juxinli.IJxlCreditInveService&methods=report,collect&pid=2188&revision=1.0.0&side=consumer&timeout=50000&timestamp=1551750774502&version=1.0.0, empty://192.168.44.1/cn.fintecher.dsIntegration.service.juxinli.IJxlCreditInveService?application=dubbo-consumer&category=routers&dubbo=2.5.3&interface=cn.fintecher.dsIntegration.service.juxinli.IJxlCreditInveService&methods=report,collect&pid=2188&revision=1.0.0&side=consumer&timeout=50000&timestamp=1551750774502&version=1.0.0], dubbo version: 2.5.3, current host: 192.168.44.1
2019-03-05 09:52:54.542 [main] ERROR com.alibaba.dubbo.common.logger.Logger -
				 [DUBBO] Failed to init remote service reference at filed ....Service in class cn.fintecher.dsIntegration.api.....Controller, cause: Failed to check the status of the service cn.fintecher.dsIntegration.service.juxinli.IJxlCreditInveService. No provider available for the service cn.fintecher.dsIntegration.service......Service:1.0.0 from the url zookeeper://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=dubbo-consumer&dubbo=2.5.3&interface=cn.fintecher.dsIntegration.service.juxinli.IJxlCreditInveService&methods=report,collect&pid=2188&revision=1.0.0&side=consumer&timeout=50000&timestamp=15....502&version=1.0.0 to the consumer 192.168.44.1 use dubbo version 2.5.3, dubbo version: 2.5.3, current host: 192.168.44.1
java.lang.IllegalStateException: Failed to check the status of the service cn.fintecher.dsIntegration.service.....Service. No provider available for the service cn.fintecher.dsIntegration.service.....Service:1.0.0 from the url zookeeper://127.0.0.1:2181/com.alibaba.dubbo.registry.RegistryService?application=dubbo-consumer&dubbo=2.5.3&interface=cn.fintecher.dsIntegration.service......Service&methods=report,collect&pid=2188&revision=1.0.0&side=consumer&timeout=50000&timestamp=1551750774502&version=1.0.0 to the consumer 192.168.44.1 use dubbo version 2.5.3
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:420)
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:300)
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:138)
	at com.alibaba.dubbo.config.spring.AnnotationBean.refer(AnnotationBean.java:302)
	at com.alibaba.dubbo.config.spring.AnnotationBean.postProcessBeforeInitialization(AnnotationBean.java:233)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at cn.fintecher.dsIntegration.Client.main(Client.java:23)

**Comment by beiwei30** [comment]
pls. check the latest code on the master branch, this issue should have been fixed.
