### ISSUE TITLE
Explicit target call  with explicit group , RemotingException(Not found exported service)  happens.

### ISSUE THREAD

**Issue by guxingke** [apache/incubator-dubbo#3648]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.0
* Operating System version: macOS Mojave 10.14.3 18D42 x86_64
* Java version: 1.8.0_202

### Steps to reproduce this issue
1.  boot (https://github.com/guxingke/demo/blob/master/dubbo-demo/p2p-group-bug-demo/src/main/java/com/gxk/demo/boot/BugServerApp.java)
2. boot (https://github.com/guxingke/demo/blob/master/dubbo-demo/p2p-group-bug-demo/src/main/java/com/gxk/demo/boot/ClientApp.java)

### Expected Result
like "Hello dubbo, response from provider: 192.168.136.176:52159"

### Actual Result
nothing, but exception. 

If there is an exception, please attach the exception trace:

```
[NettyServerWorker-3-1] INFO org.apache.dubbo.rpc.protocol.dubbo.CallbackServiceCodec -  [DUBBO] Not found exported service: com.gxk.demo.service.HelloService:20880 in [test/com.gxk.demo.service.HelloService:20880], may be version or group mismatch , channel: consumer: /192.168.136.176:51666 --> provider: /192.168.136.176:20880, message:RpcInvocation [methodName=hello, parameterTypes=[class java.lang.String], arguments=null, attachments={path=com.gxk.demo.service.HelloService, dubbo=2.0.2, interface=com.gxk.demo.service.HelloService, version=0.0.0}], dubbo version: 2.7.0, current host: 192.168.136.176
org.apache.dubbo.remoting.RemotingException: Not found exported service: com.gxk.demo.service.HelloService:20880 in [test/com.gxk.demo.service.HelloService:20880], may be version or group mismatch , channel: consumer: /192.168.136.176:51666 --> provider: /192.168.136.176:20880, message:RpcInvocation [methodName=hello, parameterTypes=[class java.lang.String], arguments=null, attachments={path=com.gxk.demo.service.HelloService, dubbo=2.0.2, interface=com.gxk.demo.service.HelloService, version=0.0.0}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:223)
	at org.apache.dubbo.rpc.protocol.dubbo.CallbackServiceCodec.decodeInvocationArgument(CallbackServiceCodec.java:270)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:134)
	at org.apache.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation.decode(DecodeableRpcInvocation.java:70)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboCodec.decodeBody(DubboCodec.java:132)
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:125)
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.decode(ExchangeCodec.java:85)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.decode(DubboCountCodec.java:46)
	at org.apache.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalDecoder.decode(NettyCodecAdapter.java:95)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by guxingke** [comment]
it fixed by [pr3558](https://github.com/apache/incubator-dubbo/pull/3558)
