### ISSUE TITLE
java.lang.IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by Python-IBM** [apache/incubator-dubbo#3726]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: v2.6.5
* Operating System version: Linux
* Java version: v1.8

### Steps to reproduce this issue
1. use hessian protocol 2.HTTP request response exception

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

I hope the request succeeds.

### Actual Result

What actually happens?

java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0]
	at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:302) ~[hessian-4.0.37.jar!/:3.1.0]
	at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:198) ~[hessian-4.0.37.jar!/:3.1.0]
	at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:139) ~[hessian-4.0.37.jar!/:3.1.0]
	at com.alibaba.dubbo.rpc.protocol.hessian.HessianProtocol$HessianHandler.handle(HessianProtocol.java:182) ~[dubbo-2.6.5.jar!/:2.6.5]
	at com.alibaba.dubbo.remoting.http.servlet.DispatcherServlet.service(DispatcherServlet.java:61) ~[dubbo-2.6.5.jar!/:2.6.5]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) ~[javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[?:?]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401) ~[?:?]
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) ~[?:?]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) ~[?:?]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) ~[?:?]
	at org.mortbay.jetty.Server.handle(Server.java:326) ~[?:?]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) ~[?:?]
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) ~[?:?]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) ~[?:?]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) ~[?:?]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) ~[?:?]
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410) ~[?:?]
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) ~[?:?]

**Comment by Python-IBM** [comment]
Windows returned successfully, Linux returned unsuccessfully
