### ISSUE TITLE
release 2.7.1 with nacos failed

### ISSUE THREAD

**Issue by zhengqigo** [apache/incubator-dubbo#3747]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: Windows 10
* Java version: 1.8

If there is an exception, please attach the exception trace:

```
java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.RegistryFactory by name nacos
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:516)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:523)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:347)
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:273)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:187)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:61)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:55)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:106)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:559)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:417)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:375)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:337)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:319)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:113)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:59)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
```

**Comment by zhengqigo** [comment]
@chickenlj @beiwei30

**Comment by mercyblitz** [comment]
Could you please give more information?

**Comment by zhengqigo** [comment]
![registry_2 7 1](https://user-images.githubusercontent.com/35255955/55213432-33a5fc00-522e-11e9-998e-311d55f9d3c9.png)
![registry_2 7 1](https://user-images.githubusercontent.com/35255955/55213436-34d72900-522e-11e9-9c86-53e1256bb4f4.png)

**Comment by zhengqigo** [comment]
@mercyblitz

**Comment by zhengqigo** [comment]
#3797
