### ISSUE TITLE
服务端从2.5.8升级到2.7.1后，Version.getIntVersion报错，响应失败

### ISSUE THREAD

**Issue by penghcn** [apache/incubator-dubbo#3784]
Fail to encode response: Response [id=399, version=client, status=20, event=false, error=null, result=RpcResult [result=cn.pengh.core.rpc.DubboResponse@4c2638bf, exception=null]], send bad_response info instead, cause: For input string: "", dubbo version: 2.7.1, current host: 192.168.8.29
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_101]
	at java.lang.Integer.parseInt(Integer.java:592) ~[?:1.8.0_101]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_101]
	at org.apache.dubbo.common.Version.parseInt(Version.java:128) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.Version.getIntVersion(Version.java:113) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.Version.isSupportResponseAttachment(Version.java:102) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboCodec.encodeResponseData(DubboCodec.java:194) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encodeResponse(ExchangeCodec.java:283) [dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:71) [dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:38) [dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:70) [dubbo-2.7.1.jar:2.7.1]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-all-4.1.32.Final.jar:4.1.32.Final]

**Comment by lexburner** [comment]
Maybe the value of `version` is null caused this parse exception, can you reproduce the exception? It is better to provide your test GitHub repository.

**Comment by chickenlj** [comment]
What's exactly is your `version's` value used on the provider side? Could you please help find its value by set breakpoint at this point?

```java
at org.apache.dubbo.common.Version.isSupportResponseAttachment(Version.java:102) ~[dubbo-2.7.1.jar:2.7.1]
at org.apache.dubbo.rpc.protocol.dubbo.DubboCodec.encodeResponseData(DubboCodec.java:194) ~[dubbo-2.7.1.jar:2.7.1]
at 
```

**Comment by chickenlj** [comment]
I cannot reproduce the problem, before you can submit more information I think we cannot make any progress on this issue.

**Comment by chickenlj** [comment]
Reopen if necessary.

**Comment by DreamYa0** [comment]
I also encountered this problem and silently returned to version 2.6.2.

**Comment by penghcn** [comment]
该bug还未修复。早期的version从文件获取，当 version = "\"\""  时，isSupportResponseAttachment 中的代码块if (StringUtils.isEmpty(version)) {
            return false;
        } 就失效了。也就是会报错如下：
11/28 15:03:45.504 WARN org.apache.dubbo.remoting.exchange.codec.ExchangeCodec [NettyServerWorker-6-7]  [DUBBO] Fail to encode response: Response [id=0, version=client, status=20, event=false, error=null, result=AppResponse [value=cn.pengh.core.rpc.RpcResponse@49995603, exception=null]], send bad_response info instead, cause: For input string: "", dubbo version: 2.7.3, current host: 192.168.6.46
java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_201]
    at java.lang.Integer.parseInt(Integer.java:592) ~[?:1.8.0_201]
    at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_201]
    at org.apache.dubbo.common.Version.parseInt(Version.java:133) ~[dubbo-2.7.3.jar:2.7.3]
    at org.apache.dubbo.common.Version.getIntVersion(Version.java:118) ~[dubbo-2.7.3.jar:2.7.3]
    at org.apache.dubbo.common.Version.isSupportResponseAttachment(Version.java:102) ~[dubbo-2.7.3.jar:2.7.3]
    at org.apache.dubbo.rpc.protocol.dubbo.DubboCodec.encodeResponseData(DubboCodec.java:195) ~[dubbo-2.7.3.jar:2.7.3]
    at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encodeResponse(ExchangeCodec.java:283) [dubbo-2.7.3.jar:2.7.3]
    at org.apache.dubbo.remoting.exchange.codec.ExchangeCodec.encode(ExchangeCodec.java:71) [dubbo-2.7.3.jar:2.7.3]
    at org.apache.dubbo.rpc.protocol.dubbo.DubboCountCodec.encode(DubboCountCodec.java:40) [dubbo-2.7.3.jar:2.7.3]
    at org.apache.dubbo.remoting.transport.netty4.NettyCodecAdapter$InternalEncoder.encode(NettyCodecAdapter.java:70) [dubbo-2.7.3.jar:2.7.3]
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:303) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at org.apache.dubbo.remoting.transport.netty4.NettyServerHandler.write(NettyServerHandler.java:103) [dubbo-2.7.3.jar:2.7.3]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:56) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1102) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1149) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1073) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.43.Final.jar:4.1.43.Final]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by penghcn** [comment]
version = "\\"\\""
