### ISSUE TITLE
curator客户端在zookeeper重启后一直抛异常

### ISSUE THREAD

**Issue by smartwjw** [apache/incubator-dubbo#38]
```
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
    at com.netflix.curator.ConnectionState.getZooKeeper(ConnectionState.java:101)
    at com.netflix.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:107)
    at com.netflix.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:448)
```

**Comment by htynkn** [comment]
Verify this with:
1. dubbo 2.6.2
2. zookeeper 3.4.12
3. curator-framework 2.12.0

All good. Consider this issue is raised at 2014, so close this issue now. If you try latest version and still able to reproduce issue, please raise a new issue
