### ISSUE TITLE
java 1.8早期版本使用2.7以上dubbo 启动异常

### ISSUE THREAD

**Issue by ylylc** [apache/incubator-dubbo#3835]
### Environment

* Dubbo version: 2.7
* Operating System version: Mac OS
* Java version: 1.8._05

### 启动异常

```
java.lang.UnsupportedOperationException: null
        at java.util.concurrent.CopyOnWriteArrayList$COWIterator.set(CopyOnWriteArrayList.java:1185)
        at java.util.Collections.sort(Collections.java:170)
        at org.apache.dubbo.rpc.cluster.RouterChain.sort(RouterChain.java:87)
        at org.apache.dubbo.rpc.cluster.RouterChain.initWithRouters(RouterChain.java:67)
```

**Comment by ylylc** [comment]
升级到,jdk版本后问题解决，但是这个对于使用1.8早期版本及之前版本的同学是个坑。CopyOnWriteArrayList 在此之前是不支持Collects.sorts。
```
 public void addRouters(List<Router> routers) {
        List<Router> newRouters = new CopyOnWriteArrayList<>();
        newRouters.addAll(builtinRouters);
        newRouters.addAll(routers);
        CollectionUtils.sort(routers);//这里使用 Collections.sort（）
        this.routers = newRouters;
    }
```

**Comment by kexianjun** [comment]
Dubbo 2.7 及以上版本只支持 java 8
>Requirements: Java 8+ required
参考 [release note](https://github.com/apache/incubator-dubbo/releases)

**Comment by ylylc** [comment]
嗯好的，java 8 前期的一些版本也不支持
