### ISSUE TITLE
dubbo 2.7.1是否与curator-recipes-2.13.0不兼容？

### ISSUE THREAD

**Issue by onethin** [apache/incubator-dubbo#3866]
### Environment

* Dubbo version: 2.71
* Operating System version: Windows 10
* Java version: Oracle JDK 1.8.1_191

### Steps to reproduce this issue
使用curator版本2.13.0，作为dubbo:refenence，应用启动报错如下异常：
2019-04-12 15:40:24.145 ERROR ZookeeperDynamicConfiguration-thread-1 TreeCache.handleException:760 []
java.lang.NullPointerException: null
	at java.lang.String.<init>(String.java:515) ~[?:1.8.0_191]
	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient$CuratorWatcherImpl.childEvent(CuratorZookeeperClient.java:298) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:741) [curator-recipes-2.13.0.jar:?]
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:735) [curator-recipes-2.13.0.jar:?]
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.13.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by yintiefu** [comment]
遇到同样的问题

**Comment by ZM227** [comment]
同问，升降curator和zk的版本依然无法解决问题

**Comment by cvictory** [comment]
@ZM227 @yintiefu  can you try to in 2.7.2-SNAPSHOT?
