### ISSUE TITLE
Direct Provider,Throw Exception:Failed to invoke remote method,may be version or group mismatch

### ISSUE THREAD

**Issue by gaofeicm** [apache/incubator-dubbo#3912]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: Windows 10 Version 1903
* Java version: 1.8.0

### Steps to reproduce this issue

1. create 'provider' project
2. create interface.
![image](https://user-images.githubusercontent.com/25575562/56564818-7d8dc200-65e1-11e9-8e5e-827253472f8b.png)
2. create class implements step2 interface
![image](https://user-images.githubusercontent.com/25575562/56564933-b9c12280-65e1-11e9-9dee-7f1bf1ed99ed.png)
3. application.properties file add 
![image](https://user-images.githubusercontent.com/25575562/56564980-d78e8780-65e1-11e9-8e9d-ba3505d62d4c.png)
4. boot file add ‘@EnableAutoConfiguration’ annotation
![image](https://user-images.githubusercontent.com/25575562/56565159-508ddf00-65e2-11e9-9bda-ddccd7819afe.png)
5. create 'consumer' project
6. copy step2 interface to project
![image](https://user-images.githubusercontent.com/25575562/56565251-8b901280-65e2-11e9-9fa3-8b6e7ed65333.png)
7. boot file add ‘@EnableAutoConfiguration’ annotation
![image](https://user-images.githubusercontent.com/25575562/56565376-cb56fa00-65e2-11e9-8a54-6b76d2e539f9.png)
8. user @Reference annotation injection interface
![image](https://user-images.githubusercontent.com/25575562/56565422-e590d800-65e2-11e9-9ee6-ad630a15b46f.png)
9. run

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

success call 'provider' project function

### Actual Result
throw exception:
```
2019-04-23 16:20:47.605 ERROR 2380 --- [nio-9185-exec-5] scms.viSvc.service.SpViCaseService       : caseNo:1904231620475912,Failed to invoke remote method: add, provider: dubbo://192.0.0.66:12345/scms.viSvc.service.SpViCaseServiceInterface?application=scms.viSvc&default.lazy=false&default.sticky=false&dubbo=2.0.2&group=test&interface=scms.viSvc.service.SpViCaseServiceInterface&lazy=false&methods=add&pid=2380&qos.enable=false&register.ip=192.0.0.66&revision=1.0.0&side=consumer&sticky=false&timestamp=1556007474371&version=1.0.0, cause: org.apache.dubbo.remoting.RemotingException: Not found exported service: test/scms.viSvc.service.SpViCaseServiceInterface:1.0.0:12345 in [a/scms.dataSvc.cases.service.SpViCaseServiceInterface:1.0.0:12345, test/scms.dataSvc.cases.service.SpViCaseServiceInterface:1.0.0:12345], may be version or group mismatch , channel: consumer: /192.0.0.66:54541 --> provider: /192.0.0.66:12345, message:RpcInvocation [methodName=add, parameterTypes=[class java.lang.String], arguments=[{}], attachments={path=scms.viSvc.service.SpViCaseServiceInterface, input=462, dubbo=2.0.2, interface=scms.viSvc.service.SpViCaseServiceInterface, version=1.0.0, group=test}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: test/scms.viSvc.service.SpViCaseServiceInterface:1.0.0:12345 in [a/scms.dataSvc.cases.service.SpViCaseServiceInterface:1.0.0:12345, test/scms.dataSvc.cases.service.SpViCaseServiceInterface:1.0.0:12345], may be version or group mismatch , channel: consumer: /192.0.0.66:54541 --> provider: /192.0.0.66:12345, message:RpcInvocation [methodName=add, parameterTypes=[class java.lang.String], arguments=[{}], attachments={path=scms.viSvc.service.SpViCaseServiceInterface, input=462, dubbo=2.0.2, interface=scms.viSvc.service.SpViCaseServiceInterface, version=1.0.0, group=test}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:248)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:103)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:200)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
'provider' project and 'consumer' project thow same exception.
how to fix it?

**Comment by gaofeicm** [comment]
if step9 write this,it success
![image](https://user-images.githubusercontent.com/25575562/56566854-3a821d80-65e6-11e9-86a6-309d0e7b9b30.png)

**Comment by kexianjun** [comment]
yes, your should make the interface the same between prodiver and consumer
