### ISSUE TITLE
dubbo-demo-api-provider启动报错

### ISSUE THREAD

**Issue by wangkun001** [apache/incubator-dubbo#4002]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.1
* Operating System version: win7
* Java version: 1.8

### Steps to reproduce this issue

1. 在idea中右键run application

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

[08/05/19 21:39:04:471 CST] main  WARN config.AbstractConfig:  [DUBBO] There's no valid metadata config found, if you are using the simplified mode of registry url, please make sure you have a metadata address configured properly., dubbo version: , current host: 10.4.31.197
Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.Protocol by name dubbo
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:517)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:524)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:348)
	at org.apache.dubbo.config.ServiceConfig.findConfigedPorts(ServiceConfig.java:725)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:535)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:431)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:389)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:352)
	at org.apache.dubbo.demo.provider.Application.main(Application.java:39)

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by Leishunyu** [comment]
Can you give a more detailed configuration?like pom.xml

**Comment by wangkun001** [comment]
> Can you give a more detailed configuration?like pom.xml

idea中Reimport就没问题了，不好意思浪费你时间了，谢谢！！！
