### ISSUE TITLE
使用 zkclient 报错

### ISSUE THREAD

**Issue by huey2672** [apache/incubator-dubbo#4084]
### Environment

* Dubbo version: 2.7.1
* Operating System version: macOS 10.13.2
* Java version: 1.8.0_172

### Steps to reproduce this issue

使用 ZooKeeper 作为注册中心，参考文档 http://dubbo.apache.org/zh-cn/docs/user/references/registry/zookeeper.html 在服务提供方配置 zkclient 为 ZooKeeper 的客户端：
<dubbo:registry address="${dubbo.registry.address}" client="zkclient"/>
工程启动则会报错。
如果去掉 client 属性配置或者配置 client="curator"，则能正常启动。
引入的 maven 依赖如下：
```
<dependency>
	<groupId>com.101tec</groupId>
	<artifactId>zkclient</artifactId>
	<version>0.10</version>
</dependency>
<dependency>
	<groupId>org.apache.curator</groupId>
	<artifactId>curator-framework</artifactId>
	<version>2.12.0</version>
</dependency>
<dependency>
	<groupId>org.apache.curator</groupId>
	<artifactId>curator-recipes</artifactId>
	<version>2.12.0</version>
</dependency>
```

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.remoting.zookeeper.ZookeeperTransporter by name zkclient
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:516)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:523)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:347)
	at org.apache.dubbo.remoting.zookeeper.ZookeeperTransporter$Adaptive.connect(ZookeeperTransporter$Adaptive.java)
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.<init>(ZookeeperRegistry.java:71)
	at org.apache.dubbo.registry.zookeeper.ZookeeperRegistryFactory.createRegistry(ZookeeperRegistryFactory.java:42)
	at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:100)
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:273)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:187)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:106)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:55)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:61)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:559)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:417)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:375)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:337)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:319)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:113)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:59)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.huey.hello.dubbo.MainApp.main(MainApp.java:8)
```

**Comment by Leishunyu** [comment]
dubbo 2.7.1 remove zkclient achieve I wiil change the blog

**Comment by web1992** [comment]
Dubbo 使用 SPI 去加载实现类，

Dubbo 对 zk 的实现进行了抽象化，方便切换实现类。 默认实现是 curator ，代码如下：

```java
@SPI("curator")
public interface ZookeeperTransporter {

    @Adaptive({Constants.CLIENT_KEY, Constants.TRANSPORTER_KEY})
    ZookeeperClient connect(URL url);

}
```
因此去掉 client 的时候，不会报错。
