### ISSUE TITLE
管理控制台安装,启动tomcat时报异常

### ISSUE THREAD

**Issue by chaice** [apache/incubator-dubbo#440]
INFO: Illegal access: this web application instance has been stopped already.  Could not load com.alibaba.dubbo.common.utils.NetUtils.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1777)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
        at com.alibaba.dubbo.common.logger.support.FailsafeLogger.appendContextMessage(FailsafeLogger.java:39)
        at com.alibaba.dubbo.common.logger.support.FailsafeLogger.warn(FailsafeLogger.java:107)
        at com.alibaba.dubbo.config.ReferenceConfig$1.finalize(ReferenceConfig.java:106)
        at java.lang.System$2.invokeFinalize(System.java:1270)
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98)
        at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210)

**Comment by kimmking** [comment]
请提供更多信息：
比如配置信息、更多log信息

**Comment by ouyangshixiong** [comment]
jdk8不支持，换个jdk试试。

**Comment by diecui1202** [comment]
Now the dubbo ops has been refactored, it's a spring boot application, u can try it.

Feel free to reopen it.
