### ISSUE TITLE
线上一直报这个错误，是BUG？

### ISSUE THREAD

**Issue by why7282** [apache/incubator-dubbo#523]
```
11:06:17.917 [pool-15-thread-1] WARN  62 warn com.alibaba.dubbo.validation.support.jvalidation.JValidator -  [DUBBO] com.hebao.bixia.core.kaniu.service.UserLocationService_GetUserLocationInfoParameter: frozen class (cannot edit), dubbo version: 2.8.4, current host: 192.168.100.2
java.lang.RuntimeException: com.xxx.core.xxx.service.UserLocationService_GetUserLocationInfoParameter: frozen class (cannot edit)
        at javassist.ClassPool.checkNotFrozen(ClassPool.java:619) ~[javassist-3.22.0-CR1.jar:?]
        at javassist.ClassPool.makeClass(ClassPool.java:861) ~[javassist-3.22.0-CR1.jar:?]
        at javassist.ClassPool.makeClass(ClassPool.java:838) ~[javassist-3.22.0-CR1.jar:?]
        at com.alibaba.dubbo.validation.support.jvalidation.JValidator.getMethodParameterBean(JValidator.java:166) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.validation.support.jvalidation.JValidator.validate(JValidator.java:100) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.validation.filter.ValidationFilter.invoke(ValidationFilter.java:49) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:72) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52) [dubbo-2.8.4.jar:2.8.4]
        at com.alibaba.dubbo.common.bytecode.proxy17.getUserLocationInfo(proxy17.java) [dubbo-2.8.4.jar:2.8.4]
        at com.hebao.bixia.mq.kaniu.service.impl.LocationInfoInitServiceImpl.initLocation(LocationInfoInitServiceImpl.java:56) [mq.jar:?]
        at com.hebao.bixia.mq.task.AutoRejectTask.run(AutoRejectTask.java:55) [mq.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
^C
```

**Comment by chickenlj** [comment]
2.8.4？用的dubbox吗？JValidator在类名生成的类名有$，有frozen class异常，该问题在新的dubbo版本中会修复

**Comment by why7282** [comment]
是用的是dubbox，不过我再想dubbo应该也存在这个问题，我现在是web项目调用rpc接口不会报这个错，非web项目有些项目调用dubbo rpc接口一直报这个错， 是dubbo的BUG？

**Comment by yangqun123** [comment]
我也遇到这个错误了，不过我的dubbo版本是2.5.3的，楼主这个问题解决了没？

**Comment by ralf0131** [comment]
dup with #796

This issue has already been fixed. See https://github.com/apache/incubator-dubbo/commit/cae7c4cee89d2a11e957ae153eb9d5e567a0170a
