### ISSUE TITLE
FailbackRegistry

### ISSUE THREAD

**Issue by jinyingone** [apache/incubator-dubbo#587]
private final ScheduledExecutorService retryExecutor
这个应该是static的字段
如果发送zk永远都连不上,就会造成启动非常多的后台线程,导致这个服务死掉

**Comment by qinliujie** [comment]
@jinyingone 按理说，不会存在这种情况，有相应的堆栈截图么？

**Comment by jinyingone** [comment]
没有截图
复现步骤:
<dubbo:registry username="${username}" password="${password}"
                    address="${address}" protocol="${protocol}"
                    group="${group}"/>
<dubbo:monitor protocol="registry"/>
zk register 配置上用户名和密码,其中密码中含有@这个特殊字符,zk地址采用域名的方式,不直接使用ip
monitor采用默认地址

请求dubbo服务,会注册monitor register,但是无法注册成功,因为密码中有@这个特殊字符,造成host无法解析,每次register都无法注册成功,请求多了以后,重试线程就会特别多,造成堆栈溢出

**Comment by jinyingone** [comment]
其中一个线程状态:
DubboRegistryFailedRetryTimer-thread-1" daemon prio=10 tid=0x00007f4a64001000 nid=0x2f0a waiting on condition [0x00007f4b63d33000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000684800260> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1090)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:807)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

**Comment by beiwei30** [comment]
we now switch to use HashedWheelTimer in FailbackRegistry. This issue should not valid any longer.
