### ISSUE TITLE
2.5.4版本 优雅停机，服务端kill pid后，还是接受了一部分请求，造成客户端超时,又遇到吗

### ISSUE THREAD

**Issue by xiedingyuan** [apache/incubator-dubbo#631]
服务端日志：
```
Caused by: com.alibaba.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2017-09-11 21:43:54.928, end time: 2017-09-11 21:45:24.935, client elapsed: 0 ms, server elapsed: 90007 ms, timeout: 90000 ms, request: Request [id=22696127, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=createOrder, parameterTypes=[class com.ninefbank.smallpay.trade.message.request.PayTradeOrderCreateReq], arguments=[com.ninefbank.smallpay.trade.message.request.PayTradeOrderCreateReq@11c97031[certType=], attachments={TingyunID=p35OnrDoP8k|y876Pcd-Q_U#svB-GMpYmCk;c=1;x=7e84aaeef05514e0;e=76ac90f4c885c89b;s=1505137434928, path=com.ninefbank.smallpay.trade.order.service.IMerOrderTranService, interface=com.ninefbank.smallpay.trade.order.service.IMerOrderTranService, timeout=90000, version=1.0}]], channel: 10.31.151.158:0 -> /10.30.251.152:20880
        at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:188)
```
客户端日志：
```
Caused by: com.alibaba.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2017-09-11 21:43:54.928, end time: 2017-09-11 21:45:24.935, client elapsed: 0 ms, server elapsed: 90013 ms, timeout: 90000 ms, request: Request [id=25710328, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=createOrder, parameterTypes=[class com.ninefbank.smallpay.trade.message.request.PayTradeOrderCreateReq], arguments=[com.ninefbank.smallpay.trade.message.request.PayTradeOrderCreateReq@539757ca[] attachments={TingyunID=p35OnrDoP8k|y876Pcd-Q_U#svB-GMpYmCk;c=1;x=326451ffd339ce24;e=a97d6890c3831cb6;s=1505137434924, path=com.ninefbank.smallpay.trade.order.service.IMerOrderTranService, interface=com.ninefbank.smallpay.trade.order.service.IMerOrderTranService, timeout=90000, version=1.0}]], channel: 10.80.52.206:0 -> /10.30.251.152:20880
        at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:188)
```

**Comment by chickenlj** [comment]
停机脚本是怎么写的？provider端的对应的停机日志能贴一下吗

**Comment by Kerwindu** [comment]
直接kill pid应该是不行的，安全kill才可以优雅停机吧。

**Comment by itbasketplayer** [comment]
文档介绍是kill pid方式，可以优雅停机。
服务提供方
  ● 停止时，先标记为不接收新请求，新请求过来时直接报错，让客户端重试其它机器。
  ● 然后，检测线程池中的线程是否正在运行，如果有，等待所有线程执行完成，除非超时，则强制关闭。
服务消费方
  ● 停止时，不再发起新的调用请求，所有新的调用在客户端即报错。
  ● 然后，检测有没有请求的响应还没有返回，等待响应返回，除非超时，则强制关闭。
感觉你的场景是，消费端A请求服务提供方B，B依赖服务端C，C停机

**Comment by xiedingyuan** [comment]
kill 2771,kill加pid。com.alibaba.dubbo.remoting.RemotingException: Failed to send message Response [id=22965603, version=2.0.0, status=20, event=false, error=null, result=RpcResult [result=com.ninefbank.smallpay.trade.message.response.PayTradeOrderCreateRes@526c9c0b, exception=null]] to /10.31.151.158:53732, cause: null
        at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:114)
        at com.alibaba.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:54)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:171)
        at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
        at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:81)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
        at org.jboss.netty.channel.socket.nio.NioWorker.cleanUpWriteBuffer(NioWorker.java:643)
        at org.jboss.netty.channel.socket.nio.NioWorker.writeFromUserCode(NioWorker.java:370)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:137)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:76)
        at org.jboss.netty.channel.Channels.write(Channels.java:632)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:70)
        at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:99)
        at org.jboss.netty.channel.Channels.write(Channels.java:611)
        at org.jboss.netty.channel.Channels.write(Channels.java:578)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:251)
        at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:101)
        ... 7 more

**Comment by xiedingyuan** [comment]
dubbo destroy 的日志没有打印

**Comment by ralf0131** [comment]
Please check the latest version of Dubbo, it should solve your issue.
