### ISSUE TITLE
当pojo中存在orm注解时，会导致序列化失败

### ISSUE THREAD

**Issue by janwenjohn** [apache/incubator-dubbo#70]
Pojo中存在orm注解时，如@Entity，@Table，@GenericGenerato，@Id，@GeneratedValue，@Column等，会导致deserialization失败，后台堆栈：

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.service.test.Consumer#0' defined in class path resource [dubbo-consumer.xml]: Invocation of init method failed; nested exception is java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to com.service.test.bo.TestBO
[01/08/14 01:13:12:012 CST] DubboSharedHandler-thread-1  INFO dubbo.DubboProtocol:  [DUBBO] disconected from /10.1.4.130:20880,url:dubbo://10.1.4.130:20880/com.service.test.service.TestService?anyhost=true&application=consumer-of-helloworld-app&check=false&codec=dubbo&dubbo=2.4.9&heartbeat=60000&interface=com.service.test.service.TestService&methods=addValue,findAllTest,delTest,addTest&pid=1740&serialization=hessian2&side=consumer&timestamp=1406869991616, dubbo version: 2.4.9, current host: 10.1.4.130
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1512)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:296)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:293)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:628)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
    at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
    at com.alibaba.dubbo.container.spring.SpringContainer.start(SpringContainer.java:50)
    at com.alibaba.dubbo.container.Main.main(Main.java:80)
    at ConsumerLaunch.main(ConsumerLaunch.java:23)
Caused by: java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to com.service.test.bo.TestBO
    at com.service.test.Consumer.start(Consumer.java:23)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1638)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1579)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1509)
    ... 14 more
```

**Comment by diecui1202** [comment]
@janwenjohn Are you there? Could you please provide a demo for us to reproduce this problem?

Anyway, thanks for your participate, feel free to reopen it. &READY-TO-CLOSE&
