### ISSUE TITLE
启动脚本在rh7/centos7下nc检测dubbo端口失败问题

### ISSUE THREAD

**Issue by zhangzacks** [apache/incubator-dubbo#799]
rh6/centos6自带nc工具为nc-***,脚本可正常执行.
rh7/centos7系统自带的nc工具nmap-ncat.***检测dubbo端口失败(start.sh脚本中的COUNT=`echo status | nc -i 1 $SERVER_HOST $SERVER_PORT | grep -c OK`),应用无法正常给出OK响应,脚本执行报出.Ncat: Connection refused.
应用日志堆栈如下:
- | 2017-11-01 00:15:03.249 | WARN | localhost | DubboServerHandler-192.168.36.150:21881-thread-2 | c.a.d.r.t.d.ChannelEventRunnable > 62 |  |  |  [DUBBO] ChannelEventRunnable handle RECEIVED operation error, channel is NettyChannel [channel=[id: 0x81c3bd40, /127.0.0.1:59354 :> /127.0.0.1:21881]], message is status, dubbo version: dap-1.0, current host: 127.0.0.1 | 
com.alibaba.dubbo.remoting.RemotingException: Failed to send message OK
dubbo> to /127.0.0.1:59354, cause: null
        at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:108)
        at com.alibaba.dubbo.remoting.transport.AbstractPeer.send(AbstractPeer.java:51)
        at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:185)
        at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:52)
        at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException: null
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
        at org.jboss.netty.channel.Channels.write(Channels.java:725)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
        at com.alibaba.dubbo.remoting.transport.netty.NettyHandler.writeRequested(NettyHandler.java:99)
        at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
        at org.jboss.netty.channel.Channels.write(Channels.java:704)
        at org.jboss.netty.channel.Channels.write(Channels.java:671)
        at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:348)
        at com.alibaba.dubbo.remoting.transport.netty.NettyChannel.send(NettyChannel.java:98)
        ... 7 common frames omitted

**Comment by eyougo** [comment]
echo status | nc -i 1 $SERVER_HOST $SERVER_PORT | grep -c OK

rh7/centos7自带的nc是nmap ncat，不是netcat。

-i参数在netcat中表示发送接收之间的间隔，但是ncat中表示idle-timeout，发送status之后ncat会立即读入EOF结束，不会再接收response，所以收不到OK。

改为 (echo status;sleep 1) | nc $SERVER_HOST $SERVER_PORT   可正常运行。

**Comment by XiaoDongJi** [comment]
@eyougo 按照你说得方法 还是不行
tarting the demo-provider ....Ncat: Connection refused.
.Ncat: Connection refused.
.Ncat: Connection refused.

**Comment by beiwei30** [comment]
it's not dubbo bug, pls. try to figure out this particular netcat on rh7 works with dubbo qos.
