### ISSUE TITLE
JSON.json(Locale) throw StackOverflowError

### ISSUE THREAD

**Issue by takeseem** [apache/incubator-dubbo#906]
fix from dubbo:master, 2.5.7 : GenericJSONConverter主要是用在日志部分输出，所以当我们输出locale对象时就发生stack溢出。
```
java.lang.StackOverflowError
	at com.alibaba.dubbo.common.json.JSONWriter.valueString(JSONWriter.java:189)
	at com.alibaba.dubbo.common.json.GenericJSONConverter$7.encode(GenericJSONConverter.java:100)
	at com.alibaba.dubbo.common.json.GenericJSONConverter.writeValue(GenericJSONConverter.java:338)
	at com.alibaba.dubbo.common.json.GenericJSONConverter.writeValue(GenericJSONConverter.java:347)
	at com.alibaba.dubbo.common.json.GenericJSONConverter.writeValue(GenericJSONConverter.java:395)
	at com.alibaba.dubbo.common.json.GenericJSONConverter.writeValue(GenericJSONConverter.java:347)
	at com.alibaba.dubbo.common.json.GenericJSONConverter.writeValue(GenericJSONConverter.java:395)
```

**Comment by takeseem** [comment]
老项目有时候伤不起！依赖关系有时候太多了！

fix see #906，locale的字符串反序列化为Locale对象，我想应该是ok的

比如jackson的测试代码
```
public static void main(String[] args) throws IOException {
	ObjectMapper mapper = new ObjectMapper();
	String json = mapper.writeValueAsString(Locale.US);
	System.out.println(json);
	System.out.println(mapper.readValue(json, Locale.class));
}
```

**Comment by qinliujie** [comment]
2.5.7 我们已经废弃掉这个了，你再确定一下？

**Comment by takeseem** [comment]
我们自己基于原来的accesslog自己加上了一点东西。后面我们会改用fastjson。不过这个遗留代码既然还保留，最好是修复下这个bug，就怕类似我这样用了几年的dubbo时，遗留代码兼容性上有问题。

**Comment by wangchengran** [comment]
telnet调用接口时，接口出参的字段含有枚举时，同样会出现StackOverFlowError的问题
